# Generated by Django 4.2.30 on 2026-04-22 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        help_text="Primary key of the related object"
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        blank=True,
                        help_text="Previous status (null for initial status)",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("to_status", models.CharField(help_text="New status", max_length=50)),
                (
                    "remarks",
                    models.TextField(
                        blank=True, help_text="Reason or notes for the status change"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of the user", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        help_text="Browser/client user agent",
                        max_length=500,
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        help_text="User who made the status change",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="status_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        help_text="The model type this status change belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_histories",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Status History",
                "verbose_name_plural": "Status Histories",
                "db_table": "status_history",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="status_hist_content_0e65da_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="status_hist_created_f5bb05_idx"
                    ),
                    models.Index(
                        fields=["changed_by"], name="status_hist_changed_5c1c22_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MasterLookup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        db_index=True,
                        help_text="Category code (e.g., 'commodity', 'expert_category')",
                        max_length=50,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code within category", max_length=50
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        help_text="Display name in English", max_length=255
                    ),
                ),
                (
                    "name_ml",
                    models.CharField(
                        blank=True,
                        help_text="Display name in Malayalam",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Optional description"),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order for display (lower = first)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this lookup is active",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata as JSON",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent lookup for hierarchical data",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="core.masterlookup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Master Lookup",
                "verbose_name_plural": "Master Lookups",
                "db_table": "master_lookup",
                "ordering": ["category", "display_order", "name_en"],
                "indexes": [
                    models.Index(
                        fields=["category", "is_active"],
                        name="master_look_categor_a5aba2_idx",
                    )
                ],
                "unique_together": {("category", "code")},
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("soft_delete", "Soft Delete"),
                            ("restore", "Restore"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("failed_login", "Failed Login"),
                            ("password_change", "Password Change"),
                            ("password_reset", "Password Reset"),
                            ("export", "Data Export"),
                            ("import", "Data Import"),
                        ],
                        help_text="Type of action performed",
                        max_length=20,
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        blank=True,
                        help_text="Primary key of the affected object",
                        max_length=50,
                    ),
                ),
                (
                    "object_repr",
                    models.CharField(
                        blank=True,
                        help_text="String representation of the object",
                        max_length=255,
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        default=dict,
                        help_text='Changed fields: {"field": {"old": x, "new": y}}',
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="Client IP address", null=True
                    ),
                ),
                (
                    "location",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Location data from IP: {"city": "Thrissur", "region": "Kerala", "country": "India", ...}',
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        help_text="Browser/client user agent",
                        max_length=500,
                    ),
                ),
                (
                    "request_path",
                    models.CharField(
                        blank=True, help_text="API endpoint path", max_length=500
                    ),
                ),
                (
                    "request_method",
                    models.CharField(
                        blank=True,
                        help_text="HTTP method (GET, POST, etc.)",
                        max_length=10,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        help_text="Model type of the affected object",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who performed the action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "db_table": "audit_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="audit_logs_user_id_fbfd51_idx",
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="audit_logs_content_b0ef47_idx",
                    ),
                    models.Index(
                        fields=["action"], name="audit_logs_action_31f574_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="audit_logs_created_262184_idx"
                    ),
                    models.Index(
                        fields=["ip_address"], name="audit_logs_ip_addr_919cb4_idx"
                    ),
                ],
            },
        ),
    ]
