# Generated by Django 4.2.30 on 2026-05-25 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_add_location_to_audit_log"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="masterlookup",
            options={
                "ordering": ["category", "display_order", "code"],
                "verbose_name": "Master Lookup",
                "verbose_name_plural": "Master Lookups",
            },
        ),
        migrations.RemoveField(
            model_name="masterlookup",
            name="name_en",
        ),
        migrations.RemoveField(
            model_name="masterlookup",
            name="name_ml",
        ),
    ]
