# Generated by Django 4.2.30 on 2026-09-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_auditlog_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Create"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("soft_delete", "Soft Delete"),
                    ("restore", "Restore"),
                    ("login", "Login"),
                    ("logout", "Logout"),
                    ("failed_login", "Failed Login"),
                    ("password_change", "Password Change"),
                    ("password_reset", "Password Reset"),
                    ("export", "Data Export"),
                    ("import", "Data Import"),
                    ("document_upload", "Document Upload"),
                    ("document_delete", "Document Delete"),
                    ("fpo_profile_change", "FPO Profile Change"),
                    ("fpo_submit", "FPO Application Submitted"),
                    ("fpo_status_change", "FPO Status Change"),
                    ("tier_recalculation", "Tier Recalculation"),
                    ("fpo_user_invite", "FPO User Invited"),
                    ("fpo_user_activate", "FPO User Activated"),
                    ("fpo_user_deactivate", "FPO User Deactivated"),
                    ("dpr_config_change", "DPR Config Changed"),
                    ("dpr_ai_value_override", "DPR AI/System Value Overridden"),
                ],
                help_text="Type of action performed",
                max_length=30,
            ),
        ),
    ]
