"""
Core Utilities
==============

Utility functions, constants, and messages for the KAU-FPO Platform.

Usage:
    from apps.core.utils import (
        # Constants
        District, UserRole, FPOStatus, DocumentType,
        # Messages
        AuthMessages, FPOMessages, msg,
        # Responses
        success_response, error_response,
        # Validators
        validate_kerala_pincode, validate_indian_phone,
        # Helpers
        generate_application_id, get_client_ip,
    )
"""

# Constants (NO DB queries)
from .constants import (
    District,
    DISTRICTS_BILINGUAL,
    get_district_name,
    UserRole,
    ROLE_HIERARCHY,
    FPOStatus,
    FPO_STATUS_TRANSITIONS,
    can_transition_fpo_status,
    DocumentType,
    REQUIRED_DOCUMENTS,
    OPTIONAL_DOCUMENTS,
    NotificationType,
    NotificationChannel,
    DeliveryStatus,
    Language,
    DEFAULT_LANGUAGE,
    ALLOWED_DOCUMENT_EXTENSIONS,
    ALLOWED_IMAGE_EXTENSIONS,
    MAX_FILE_SIZE_MB,
    MAX_FILE_SIZE_BYTES,
    KERALA_PINCODE_PREFIX,
    KERALA_PINCODES_RANGE,
    KERALA_BOUNDS,
    INDIAN_PHONE_REGEX,
    PAN_REGEX,
    GST_REGEX,
    IFSC_REGEX,
    MIN_FPO_MEMBERS,
    MIN_FPO_SHARE_CAPITAL,
    DEFAULT_PAGE_SIZE,
    MAX_PAGE_SIZE,
    CACHE_TTL_SHORT,
    CACHE_TTL_MEDIUM,
    CACHE_TTL_LONG,
    ResponseCode,
)

# Messages (NO DB queries)
from .messages import (
    AuthMessages,
    FPOMessages,
    DocumentMessages,
    ValidationMessages,
    CommonMessages,
    NotificationMessages,
    get_message,
    msg,
    get_both_messages,
)

# Responses
from .responses import (
    StandardResponse,
    success_response,
    error_response,
    created_response,
    not_found_response,
    validation_error_response,
)

# Validators
from .validators import (
    validate_indian_phone,
    validate_kerala_pincode,
    validate_pan,
    validate_gst,
    validate_ifsc,
    validate_kerala_coordinates,
    validate_file_extension,
    validate_file_size,
    validate_bank_account_number,
    validate_email_format,
    validate_kerala_district,
    IndianPhoneValidator,
    KeralaPincodeValidator,
    PANValidator,
    GSTValidator,
    IFSCValidator,
    KeralaCoordinatesValidator,
    FileValidator,
)

# Helpers
from .helpers import (
    generate_uuid,
    generate_short_uuid,
    generate_application_id,
    generate_otp,
    generate_token,
    is_valid_uuid,
    get_current_datetime,
    get_current_date,
    format_datetime,
    format_date,
    days_until,
    add_days,
    is_past_date,
    is_future_date,
    slugify,
    truncate,
    mask_email,
    mask_phone,
    clean_string,
    get_client_ip,
    get_user_agent,
    get_language_from_request,
    get_file_extension,
    generate_unique_filename,
    get_upload_path,
    format_file_size,
    safe_get,
    remove_none_values,
    flatten_dict,
    chunk_list,
    hash_string,
    hash_file,
)

# Pagination
from .pagination import (
    StandardPagination,
    LargeResultsPagination,
    SmallResultsPagination,
)

# Cache
from .cache import (
    cache_key,
    cache_key_pattern,
    get_cache,
    set_cache,
    delete_cache,
    delete_cache_pattern,
    get_or_set_cache,
    cache_many,
    get_cache_many,
    delete_cache_many,
    cached,
    user_cache_key,
    fpo_cache_key,
    lookup_cache_key,
    template_cache_key,
    invalidate_user_cache,
    invalidate_fpo_cache,
    invalidate_lookup_cache,
    invalidate_template_cache,
)

__all__ = [
    # Constants
    'District',
    'DISTRICTS_BILINGUAL',
    'get_district_name',
    'UserRole',
    'ROLE_HIERARCHY',
    'FPOStatus',
    'FPO_STATUS_TRANSITIONS',
    'can_transition_fpo_status',
    'DocumentType',
    'REQUIRED_DOCUMENTS',
    'OPTIONAL_DOCUMENTS',
    'NotificationType',
    'NotificationChannel',
    'DeliveryStatus',
    'Language',
    'DEFAULT_LANGUAGE',
    'ALLOWED_DOCUMENT_EXTENSIONS',
    'ALLOWED_IMAGE_EXTENSIONS',
    'MAX_FILE_SIZE_MB',
    'MAX_FILE_SIZE_BYTES',
    'KERALA_PINCODE_PREFIX',
    'KERALA_PINCODES_RANGE',
    'KERALA_BOUNDS',
    'MIN_FPO_MEMBERS',
    'MIN_FPO_SHARE_CAPITAL',
    'DEFAULT_PAGE_SIZE',
    'MAX_PAGE_SIZE',
    'ResponseCode',
    # Messages
    'AuthMessages',
    'FPOMessages',
    'DocumentMessages',
    'ValidationMessages',
    'CommonMessages',
    'NotificationMessages',
    'get_message',
    'msg',
    'get_both_messages',
    # Responses
    'StandardResponse',
    'success_response',
    'error_response',
    'created_response',
    'not_found_response',
    'validation_error_response',
    # Validators
    'validate_indian_phone',
    'validate_kerala_pincode',
    'validate_pan',
    'validate_gst',
    'validate_ifsc',
    'validate_kerala_coordinates',
    'validate_file_extension',
    'validate_file_size',
    'validate_bank_account_number',
    'validate_email_format',
    'validate_kerala_district',
    'IndianPhoneValidator',
    'KeralaPincodeValidator',
    'PANValidator',
    'GSTValidator',
    'IFSCValidator',
    'KeralaCoordinatesValidator',
    'FileValidator',
    # Helpers
    'generate_uuid',
    'generate_short_uuid',
    'generate_application_id',
    'generate_otp',
    'generate_token',
    'is_valid_uuid',
    'get_current_datetime',
    'get_current_date',
    'format_datetime',
    'format_date',
    'slugify',
    'truncate',
    'mask_email',
    'mask_phone',
    'clean_string',
    'get_client_ip',
    'get_user_agent',
    'get_language_from_request',
    'get_file_extension',
    'generate_unique_filename',
    'format_file_size',
    'safe_get',
    'remove_none_values',
    # Pagination
    'StandardPagination',
    'LargeResultsPagination',
    'SmallResultsPagination',
    # Cache
    'cache_key',
    'get_cache',
    'set_cache',
    'delete_cache',
    'get_or_set_cache',
    'cached',
    'invalidate_user_cache',
    'invalidate_fpo_cache',
    'invalidate_lookup_cache',
    'invalidate_template_cache',
]
