# Generated by Django 4.2.30 on 2026-04-28 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("database", "0001_seed_initial_translations"),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="ISO 639-1 language code (e.g., 'en', 'ml', 'ta')",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Language name in English (e.g., 'English', 'Malayalam')",
                        max_length=50,
                    ),
                ),
                (
                    "native_name",
                    models.CharField(
                        help_text="Language name in native script (e.g., 'English', 'മലയാളം')",
                        max_length=50,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Only active languages are available for selection",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Default language for new users and fallback",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order in language selector dropdown"
                    ),
                ),
                (
                    "is_rtl",
                    models.BooleanField(
                        default=False, help_text="Right-to-left text direction"
                    ),
                ),
                (
                    "locale",
                    models.CharField(
                        blank=True,
                        help_text="Full locale code (e.g., 'en_US', 'ml_IN')",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "Language",
                "verbose_name_plural": "Languages",
                "db_table": "languages",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="TranslationCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Category code (e.g., 'ui', 'validation', 'auth')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Category name for display", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="What this category contains"
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Translation Category",
                "verbose_name_plural": "Translation Categories",
                "db_table": "translation_categories",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        help_text="Translation key (e.g., 'login_success', 'required_field')",
                        max_length=255,
                    ),
                ),
                (
                    "value",
                    models.TextField(
                        help_text="Translated text. Use {{variable}} for dynamic content"
                    ),
                ),
                (
                    "context",
                    models.TextField(
                        blank=True,
                        help_text="Context/notes for translators (e.g., 'Shown on login page after successful authentication')",
                    ),
                ),
                (
                    "variables",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of variable names used (e.g., ['user_name', 'fpo_name'])",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Has this translation been reviewed and approved by KAU?",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When was this translation verified?",
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Category this translation belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="translations",
                        to="database.translationcategory",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="database.language",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who verified this translation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_translations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Translation",
                "verbose_name_plural": "Translations",
                "db_table": "translations",
                "indexes": [
                    models.Index(
                        fields=["category", "key", "language"],
                        name="translation_categor_2fe8e0_idx",
                    ),
                    models.Index(
                        fields=["language", "is_verified"],
                        name="translation_languag_bcd529_idx",
                    ),
                ],
                "unique_together": {("category", "key", "language")},
            },
        ),
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Template code (e.g., 'fpo_approved', 'password_reset', 'user_registered')",
                        max_length=50,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Template name for display in admin panel",
                        max_length=100,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("in_app", "In-App Notification"),
                            ("push", "Push Notification"),
                        ],
                        help_text="Notification channel",
                        max_length=10,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        help_text="Email subject line (only for email channel). Use {{variables}} for dynamic content.",
                        max_length=255,
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Template body. Use {{variable}} for dynamic content. HTML allowed for email channel."
                    ),
                ),
                (
                    "variables",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of variable names used (e.g., ['user_name', 'application_id', 'fpo_name'])",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="When and why this template is used (for admin reference)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Only active templates are used for sending notifications",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_templates",
                        to="database.language",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Template",
                "verbose_name_plural": "Notification Templates",
                "db_table": "notification_templates",
                "indexes": [
                    models.Index(
                        fields=["code", "channel", "language", "is_active"],
                        name="notificatio_code_9faf23_idx",
                    ),
                    models.Index(
                        fields=["is_active", "channel"],
                        name="notificatio_is_acti_14a94b_idx",
                    ),
                ],
                "unique_together": {("code", "channel", "language")},
            },
        ),
    ]
