# Generated by Django 4.2.30 on 2026-05-07 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("database", "0003_refactor_notification_templates"),
    ]

    operations = [
        migrations.CreateModel(
            name="InAppNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Notification title (rendered subject)",
                        max_length=500,
                    ),
                ),
                (
                    "body",
                    models.TextField(help_text="Notification body (rendered content)"),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether the user has read this notification",
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the user read this notification",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "In-App Notification",
                "verbose_name_plural": "In-App Notifications",
                "db_table": "in_app_notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationChannelSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("in_app", "In-App Notification"),
                            ("push", "Push Notification"),
                            ("whatsapp", "WhatsApp"),
                        ],
                        help_text="Notification channel this config applies to",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Enable or disable this channel globally",
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        default=dict,
                        help_text="Channel-specific settings. Sensitive fields (passwords, API keys) are AES-encrypted before storage.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Channel Setting",
                "verbose_name_plural": "Notification Channel Settings",
                "db_table": "notification_channel_settings",
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("in_app", "In-App Notification"),
                            ("push", "Push Notification"),
                            ("whatsapp", "WhatsApp"),
                        ],
                        db_index=True,
                        help_text="Channel used to deliver this notification",
                        max_length=20,
                    ),
                ),
                (
                    "rendered_subject",
                    models.CharField(
                        blank=True,
                        help_text="Final rendered subject line (email only)",
                        max_length=500,
                    ),
                ),
                (
                    "rendered_body",
                    models.TextField(
                        help_text="Final rendered body after variable substitution"
                    ),
                ),
                (
                    "recipient",
                    models.CharField(
                        blank=True,
                        help_text="Email address, phone number, or device token used for delivery",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("retrying", "Retrying"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Delivery status",
                        max_length=20,
                    ),
                ),
                (
                    "failure_reason",
                    models.TextField(
                        blank=True, help_text="Error message if delivery failed"
                    ),
                ),
                (
                    "retry_count",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Number of retry attempts made"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the notification was successfully delivered",
                        null=True,
                    ),
                ),
                (
                    "context",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Variable context used to render the template",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Log",
                "verbose_name_plural": "Notification Logs",
                "db_table": "notification_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RenameIndex(
            model_name="notificationtemplate",
            new_name="notificatio_templat_683123_idx",
            old_name="notif_tmpl_lookup_idx",
        ),
        migrations.RenameIndex(
            model_name="notificationtemplate",
            new_name="notificatio_is_acti_f33840_idx",
            old_name="notif_tmpl_active_idx",
        ),
        migrations.AlterField(
            model_name="notificationtemplate",
            name="body",
            field=models.TextField(
                help_text="Template body. Use {{variable_name}} for dynamic content. HTML allowed for email."
            ),
        ),
        migrations.AlterField(
            model_name="notificationtemplate",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Timestamp when record was created",
            ),
        ),
        migrations.AlterField(
            model_name="notificationtemplate",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp when record was last updated"
            ),
        ),
        migrations.AlterField(
            model_name="notificationtemplatecode",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Timestamp when record was created",
            ),
        ),
        migrations.AlterField(
            model_name="notificationtemplatecode",
            name="name",
            field=models.CharField(
                help_text="Human-readable name shown in admin (e.g. 'FPO Application Approved')",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="notificationtemplatecode",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp when record was last updated"
            ),
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="language",
            field=models.ForeignKey(
                help_text="Language the notification was rendered in",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notification_logs",
                to="database.language",
            ),
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="template_code",
            field=models.ForeignKey(
                help_text="Template definition used",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="logs",
                to="database.notificationtemplatecode",
            ),
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="user",
            field=models.ForeignKey(
                help_text="Recipient user",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notification_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="inappnotification",
            name="log",
            field=models.OneToOneField(
                help_text="Source notification log entry",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="in_app_notification",
                to="database.notificationlog",
            ),
        ),
        migrations.AddField(
            model_name="inappnotification",
            name="user",
            field=models.ForeignKey(
                help_text="User who receives this notification",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="in_app_notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="notificationlog",
            index=models.Index(
                fields=["user", "channel", "status"],
                name="notificatio_user_id_3a513d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationlog",
            index=models.Index(
                fields=["status", "retry_count"], name="notificatio_status_8f2656_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationlog",
            index=models.Index(
                fields=["created_at"], name="notificatio_created_45a1e0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inappnotification",
            index=models.Index(
                fields=["user", "is_read"], name="in_app_noti_user_id_75f459_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inappnotification",
            index=models.Index(
                fields=["user", "created_at"], name="in_app_noti_user_id_e618a7_idx"
            ),
        ),
    ]
