# Generated by Django 4.2.30 on 2026-05-07 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("database", "0004_add_notification_system_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "label_key",
                    models.CharField(
                        help_text="Translation key from the 'menu' category — e.g. 'menu.notifications'",
                        max_length=100,
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        help_text="Frontend route — e.g. '/admin/notifications'",
                        max_length=200,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon name for the frontend — e.g. 'bell', 'building', 'globe'",
                        max_length=50,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Sort order within the same level (lower = first)",
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent item — null means top-level",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="database.menuitem",
                    ),
                ),
                (
                    "roles",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Roles (Django Groups) that can see this menu item",
                        related_name="menu_items",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu Item",
                "verbose_name_plural": "Menu Items",
                "db_table": "menu_items",
                "ordering": ["order", "label_key"],
            },
        ),
    ]
