# Generated by Django 4.2.30 on 2026-05-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0007_user_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="must_change_password",
            field=models.BooleanField(default=False),
        ),
    ]
