# Generated by Django 4.2.30 on 2026-05-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0008_user_profile_must_change_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationtemplate",
            name="whatsapp_template_language",
            field=models.CharField(
                blank=True,
                default="en",
                help_text="WhatsApp template language code (e.g. en, ml). Must match Meta-approved language.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="notificationtemplate",
            name="whatsapp_template_name",
            field=models.CharField(
                blank=True,
                help_text="Meta-approved WhatsApp template name (e.g. kau_fpo_password_reset). WhatsApp channel only.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="notificationtemplatecode",
            name="channel",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("sms", "SMS"),
                    ("in_app", "In-App Notification"),
                    ("push", "Push Notification"),
                    ("whatsapp", "WhatsApp"),
                ],
                help_text="Delivery channel for this definition",
                max_length=10,
            ),
        ),
    ]
