# Generated by Django 4.2.30 on 2026-05-20 05:36

import apps.database.models.fpo
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("database", "0009_whatsapp_template_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="FPO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag. True means record is deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Public UUID identifier (use this in APIs instead of PK)",
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("name_ml", models.CharField(blank=True, max_length=255)),
                ("registration_number", models.CharField(max_length=100, unique=True)),
                ("cin_number", models.CharField(blank=True, max_length=21)),
                ("date_of_registration", models.DateField()),
                (
                    "registered_under",
                    models.CharField(
                        choices=[
                            ("companies_act", "Companies Act 2013"),
                            (
                                "cooperative_act",
                                "Kerala Co-operative Societies Act 1969",
                            ),
                            ("producer_companies_act", "Producer Companies Act"),
                            ("societies_act", "Societies Registration Act 1860"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("pan_number", models.CharField(max_length=10)),
                ("gst_number", models.CharField(blank=True, max_length=15)),
                (
                    "district",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("TVM", "Thiruvananthapuram"),
                            ("KLM", "Kollam"),
                            ("PTA", "Pathanamthitta"),
                            ("ALP", "Alappuzha"),
                            ("KTM", "Kottayam"),
                            ("IDK", "Idukki"),
                            ("EKM", "Ernakulam"),
                            ("TSR", "Thrissur"),
                            ("PKD", "Palakkad"),
                            ("MLP", "Malappuram"),
                            ("KZD", "Kozhikode"),
                            ("WYD", "Wayanad"),
                            ("KNR", "Kannur"),
                            ("KSD", "Kasaragod"),
                        ],
                        max_length=3,
                    ),
                ),
                ("block_taluk", models.CharField(blank=True, max_length=100)),
                ("village_town", models.CharField(blank=True, max_length=100)),
                ("address_line1", models.CharField(blank=True, max_length=255)),
                ("address_line2", models.CharField(blank=True, max_length=255)),
                ("pincode", models.CharField(blank=True, max_length=6)),
                ("office_phone", models.CharField(blank=True, max_length=10)),
                ("office_email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                ("email_verified", models.BooleanField(default=False)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="GPS latitude — sent by frontend from browser location or geocoded from address",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="GPS longitude — sent by frontend from browser location or geocoded from address",
                        max_digits=9,
                        null=True,
                    ),
                ),
                ("signatory_name", models.CharField(blank=True, max_length=255)),
                ("signatory_designation", models.CharField(blank=True, max_length=100)),
                ("signatory_phone", models.CharField(blank=True, max_length=10)),
                ("signatory_email", models.EmailField(blank=True, max_length=254)),
                ("signatory_aadhaar_last4", models.CharField(blank=True, max_length=4)),
                ("total_members", models.PositiveIntegerField(blank=True, null=True)),
                ("male_members", models.PositiveIntegerField(blank=True, null=True)),
                ("female_members", models.PositiveIntegerField(blank=True, null=True)),
                ("sc_st_members", models.PositiveIntegerField(blank=True, null=True)),
                ("primary_commodities", models.JSONField(blank=True, default=list)),
                ("secondary_commodities", models.JSONField(blank=True, default=list)),
                (
                    "annual_turnover",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("bank_name", models.CharField(blank=True, max_length=100)),
                ("bank_branch", models.CharField(blank=True, max_length=100)),
                ("account_number", models.CharField(blank=True, max_length=18)),
                ("ifsc_code", models.CharField(blank=True, max_length=11)),
                ("description", models.TextField(blank=True)),
                (
                    "current_step",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Last completed wizard step (1-4). Frontend uses this to resume registration.",
                    ),
                ),
                (
                    "application_id",
                    models.CharField(blank=True, max_length=30, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("info_required", "Additional Info Required"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("suspended", "Suspended"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        blank=True,
                        help_text="Cached from FPOTierHistory — never set directly (BR-107)",
                        max_length=1,
                    ),
                ),
                (
                    "max_secondary_users",
                    models.PositiveIntegerField(
                        default=15,
                        help_text="Max secondary users for this FPO. Configurable by KAU Admin.",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Phase 2: sub-admin row-level security anchor",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_fpos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who deleted this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "primary_user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fpo",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "FPO",
                "verbose_name_plural": "FPOs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TierCriteria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag. True means record is deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Public UUID identifier (use this in APIs instead of PK)",
                        unique=True,
                    ),
                ),
                ("criteria_name", models.CharField(max_length=200)),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Scoring weight, e.g. 20.00 = 20%",
                        max_digits=5,
                    ),
                ),
                (
                    "threshold_a",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Minimum score for Tier A",
                        max_digits=5,
                    ),
                ),
                (
                    "threshold_b",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Minimum score for Tier B",
                        max_digits=5,
                    ),
                ),
                (
                    "threshold_c",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Minimum score for Tier C",
                        max_digits=5,
                    ),
                ),
                (
                    "threshold_d",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Minimum score for Tier D",
                        max_digits=5,
                    ),
                ),
                (
                    "is_visible_to_fpo",
                    models.BooleanField(
                        default=False,
                        help_text="Whether FPOs can see this criterion on their dashboard",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who deleted this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Tier Criteria",
                "ordering": ["-weight"],
            },
        ),
        migrations.CreateModel(
            name="FPOTierHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("A", "Tier A"),
                            ("B", "Tier B"),
                            ("C", "Tier C"),
                            ("D", "Tier D"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "financial_year",
                    models.CharField(help_text="e.g. 2025-26", max_length=7),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fpo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tier_history",
                        to="database.fpo",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "FPO Tier Histories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FPOOwnershipClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "supporting_doc_ids",
                    models.JSONField(
                        default=list,
                        help_text="List of FPODocument IDs submitted as supporting evidence",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True)),
                (
                    "claimant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fpo_claims",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fpo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ownership_claims",
                        to="database.fpo",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_claims",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApplicationStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                ("from_status", models.CharField(blank=True, max_length=20)),
                ("to_status", models.CharField(max_length=20)),
                ("notes", models.TextField(blank=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fpo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="database.fpo",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Application Status Histories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FPOUserMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag. True means record is deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Public UUID identifier (use this in APIs instead of PK)",
                        unique=True,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("primary", "Primary User"),
                            ("secondary", "Secondary User"),
                        ],
                        default="secondary",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who deleted this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fpo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="database.fpo",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fpo_membership",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["joined_at"],
                "unique_together": {("fpo", "user")},
            },
        ),
        migrations.CreateModel(
            name="FPODocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag. True means record is deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Public UUID identifier (use this in APIs instead of PK)",
                        unique=True,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("fpo_reg_cert", "FPO Registration Certificate"),
                            ("bank_details", "Bank Account Details"),
                            ("signatory_id", "Authorized Signatory ID"),
                            ("pan_card", "PAN Card"),
                            ("gst_cert", "GST Certificate"),
                            ("annual_report", "Annual Report"),
                            ("member_list", "Member List"),
                            ("board_resolution", "Board Resolution"),
                            ("moa_aoa", "MOA/AOA"),
                            ("other", "Other Document"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.database.models.fpo.fpo_document_upload_path
                    ),
                ),
                ("file_size", models.PositiveIntegerField(help_text="Size in bytes")),
                ("mime_type", models.CharField(max_length=100)),
                ("is_verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who deleted this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fpo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="database.fpo",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["fpo", "document_type"],
                        name="database_fp_fpo_id_3b4822_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="fpo",
            index=models.Index(fields=["status"], name="database_fp_status_c2c5f1_idx"),
        ),
        migrations.AddIndex(
            model_name="fpo",
            index=models.Index(
                fields=["district"], name="database_fp_distric_2a89cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fpo",
            index=models.Index(fields=["tier"], name="database_fp_tier_27a1ff_idx"),
        ),
        migrations.AddIndex(
            model_name="fpo",
            index=models.Index(
                fields=["pan_number"], name="database_fp_pan_num_77d0c1_idx"
            ),
        ),
    ]
