# Generated by Django 4.2.30 on 2026-05-25 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0011_fpo_permission_matrix"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fpoaction",
            name="label_en",
        ),
        migrations.RemoveField(
            model_name="fpoaction",
            name="label_ml",
        ),
    ]
