# Generated by Django 4.2.30 on 2026-06-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0014_unified_role_permission"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fpo",
            name="max_secondary_users",
        ),
        migrations.RemoveField(
            model_name="fpo",
            name="registered_under",
        ),
        migrations.AddField(
            model_name="fpo",
            name="accountant_available",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fpo",
            name="ceo_available",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fpo",
            name="directors_under_35",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fpo",
            name="facilitating_agency_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="fpo",
            name="legal_structure",
            field=models.CharField(
                blank=True,
                help_text="MasterLookup category='legal_structure'",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="fpo",
            name="legal_structure_detail",
            field=models.CharField(
                blank=True,
                help_text="State CSA act name when legal_structure='state_specific_csa'",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="fpo",
            name="promoting_agency",
            field=models.CharField(
                blank=True,
                help_text="MasterLookup category='promoting_agency'",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="fpo",
            name="total_directors",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fpo",
            name="women_directors",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fpo",
            name="cin_number",
            field=models.CharField(
                blank=True,
                help_text="Companies Act / Producer Companies only. MCA21 21-char format.",
                max_length=21,
            ),
        ),
        migrations.AlterField(
            model_name="fpo",
            name="date_of_registration",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fpo",
            name="district",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TVM", "Thiruvananthapuram"),
                    ("KLM", "Kollam"),
                    ("PTA", "Pathanamthitta"),
                    ("ALP", "Alappuzha"),
                    ("KTM", "Kottayam"),
                    ("IDK", "Idukki"),
                    ("EKM", "Ernakulam"),
                    ("TRS", "Thrissur"),
                    ("PKD", "Palakkad"),
                    ("MLP", "Malappuram"),
                    ("KZD", "Kozhikode"),
                    ("WYD", "Wayanad"),
                    ("KNR", "Kannur"),
                    ("KSD", "Kasaragod"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="fpo",
            name="registration_number",
            field=models.CharField(
                blank=True,
                help_text="For non-Companies Act FPOs. Unique when non-empty.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="fpo",
            name="signatory_designation",
            field=models.CharField(
                blank=True,
                help_text="MasterLookup category='signatory_designation'",
                max_length=100,
            ),
        ),
    ]
