# Generated by Django 4.2.30 on 2026-06-16 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("database", "0015_fpo_model_kau_changes"),
    ]

    operations = [
        migrations.CreateModel(
            name="TierCriterion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("max_marks", models.PositiveSmallIntegerField()),
                (
                    "scoring_type",
                    models.CharField(
                        choices=[
                            ("computed", "Computed automatically"),
                            ("single_select", "Single select"),
                            ("boolean", "Yes / No"),
                            ("numeric_range", "Numeric range"),
                            ("additive_bool", "Additive Yes/No"),
                            ("percentage", "System calculated percentage"),
                            ("multi_select", "Multi select"),
                            ("conditional", "Conditional logic"),
                        ],
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["domain__order", "order"],
            },
        ),
        migrations.CreateModel(
            name="TierDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=5, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("max_marks", models.PositiveSmallIntegerField()),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="TierQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_no", models.PositiveSmallIntegerField(unique=True)),
                ("text", models.TextField()),
                (
                    "input_type",
                    models.CharField(
                        choices=[
                            ("number", "Numeric input"),
                            ("boolean", "Yes / No"),
                            ("single_select", "Single select dropdown"),
                            ("multi_select", "Multi select checkboxes"),
                            ("computed", "Auto-computed — no user input"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "answer_config",
                    models.JSONField(
                        default=dict,
                        help_text='For single_select/boolean: {"options": [{"value": "yes", "label": "Yes", "score": 5}]}\nFor number/multi_select: {"score_ranges": [...]} or {"options": [...]}\nFor computed: {"source": "date_of_registration"}',
                    ),
                ),
                ("is_conditional", models.BooleanField(default=False)),
                ("condition_value", models.CharField(blank=True, max_length=50)),
                ("is_required", models.BooleanField(default=True)),
                (
                    "has_upload",
                    models.BooleanField(
                        default=False, help_text="Q6, Q17, Q27 require document upload"
                    ),
                ),
                ("upload_label", models.CharField(blank=True, max_length=200)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "condition_on",
                    models.ForeignKey(
                        blank=True,
                        help_text="Show this question only when condition_on question has condition_value",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dependent_questions",
                        to="database.tierquestion",
                    ),
                ),
                (
                    "criterion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="database.tiercriterion",
                    ),
                ),
            ],
            options={
                "ordering": ["question_no"],
            },
        ),
        migrations.AddField(
            model_name="tiercriterion",
            name="domain",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="criteria",
                to="database.tierdomain",
            ),
        ),
        migrations.CreateModel(
            name="FPOAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag. True means record is deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Public UUID identifier (use this in APIs instead of PK)",
                        unique=True,
                    ),
                ),
                (
                    "financial_year",
                    models.CharField(help_text="e.g. 2025-26", max_length=7),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("submitted", "Submitted")],
                        default="draft",
                        max_length=10,
                    ),
                ),
                (
                    "total_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("tier_assigned", models.CharField(blank=True, max_length=1)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who deleted this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fpo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="database.fpo",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-financial_year"],
                "unique_together": {("fpo", "financial_year")},
            },
        ),
        migrations.CreateModel(
            name="AssessmentAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answer",
                    models.JSONField(
                        help_text='Stored as JSON: "yes", 5000, ["local_market","trader"], etc.'
                    ),
                ),
                (
                    "score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="database.fpoassessment",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="database.tierquestion",
                    ),
                ),
            ],
            options={
                "ordering": ["question__question_no"],
                "unique_together": {("assessment", "question")},
            },
        ),
    ]
