# Generated by Django 4.2.30 on 2026-06-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0016_tier_assessment_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tiercriterion",
            name="code",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
