# Generated by Django 4.2.30 on 2026-06-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0017_fix_tiercriterion_code_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="fpoassessment",
            name="domain_scores",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='{"I": 17.0, "II": 13.0, ...} — stored on submit',
            ),
        ),
    ]
