# Generated by Django 4.2.30 on 2026-06-16 15:20

import apps.database.models.fpo
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0018_add_domain_scores_to_assessment"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssessmentUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_no", models.PositiveSmallIntegerField()),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.database.models.fpo.AssessmentUpload._upload_path
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploads",
                        to="database.fpoassessment",
                    ),
                ),
            ],
            options={
                "ordering": ["question_no", "uploaded_at"],
            },
        ),
    ]
