# Generated by Django 4.2.30 on 2026-06-16 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0020_add_scheme_expert_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.JSONField(
                        default=dict, help_text='{"en": "...", "ml": "..."}'
                    ),
                ),
                (
                    "body",
                    models.JSONField(
                        default=dict, help_text='{"en": "...", "ml": "..."}'
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("announcement", "Announcement"), ("news", "News")],
                        default="announcement",
                        max_length=20,
                    ),
                ),
                ("published_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order", "-published_date"],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question",
                    models.JSONField(
                        default=dict, help_text='{"en": "...", "ml": "..."}'
                    ),
                ),
                (
                    "answer",
                    models.JSONField(
                        default=dict, help_text='{"en": "...", "ml": "..."}'
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("fpo_general", "FPO General"),
                            ("schemes", "Schemes & Financial Support"),
                            ("platform_usage", "Platform Usage"),
                        ],
                        max_length=30,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["category", "order"],
            },
        ),
        migrations.CreateModel(
            name="SiteBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("block_key", models.CharField(max_length=100, unique=True)),
                (
                    "content",
                    models.JSONField(
                        default=dict, help_text='{"en": "...", "ml": "..."}'
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["block_key"],
            },
        ),
    ]
