# Generated by Django 4.2.30 on 2026-06-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0021_add_cms_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fpo",
            name="application_id",
            field=models.CharField(
                blank=True, default=None, max_length=30, null=True, unique=True
            ),
        ),
    ]
