# Generated by Django 4.2.30 on 2026-06-30 11:32

import apps.database.models.cms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0022_fix_application_id_null"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuickLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Admin label — not shown publicly", max_length=200
                    ),
                ),
                ("url", models.URLField(max_length=500)),
                (
                    "logo",
                    models.ImageField(
                        upload_to=apps.database.models.cms._quick_link_logo_path
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
