# Generated by Django 4.2.30 on 2026-06-30 12:18

import apps.database.models.cms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0023_add_quick_link_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quicklink",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.database.models.cms._quick_link_logo_path,
            ),
        ),
    ]
