# Generated by Django 4.2.30 on 2026-07-01 09:07

import apps.database.models.cms
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0030_add_visitor_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag. True means record is deleted.'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public UUID identifier (use this in APIs instead of PK)', unique=True),
        ),
        migrations.AlterField(
            model_name='documentlibrary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created'),
        ),
        migrations.AlterField(
            model_name='documentlibrary',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documentlibrary',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True),
        ),
        migrations.AlterField(
            model_name='documentlibrary',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documentlibrary',
            name='file',
            field=models.FileField(upload_to=apps.database.models.cms._document_library_path),
        ),
        migrations.AlterField(
            model_name='documentlibrary',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='documentlibrary',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag. True means record is deleted.'),
        ),
        migrations.AlterField(
            model_name='documentlibrary',
            name='is_view_only',
            field=models.BooleanField(default=False, help_text='True = view only, no download button'),
        ),
        migrations.AlterField(
            model_name='documentlibrary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated'),
        ),
        migrations.AlterField(
            model_name='documentlibrary',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documentlibrary',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public UUID identifier (use this in APIs instead of PK)', unique=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='faq',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='faq',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag. True means record is deleted.'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='faq',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public UUID identifier (use this in APIs instead of PK)', unique=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created'),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag. True means record is deleted.'),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated'),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public UUID identifier (use this in APIs instead of PK)', unique=True),
        ),
        migrations.AlterField(
            model_name='newssource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created'),
        ),
        migrations.AlterField(
            model_name='newssource',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='newssource',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True),
        ),
        migrations.AlterField(
            model_name='newssource',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='newssource',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='newssource',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag. True means record is deleted.'),
        ),
        migrations.AlterField(
            model_name='newssource',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.database.models.cms._news_source_logo_path),
        ),
        migrations.AlterField(
            model_name='newssource',
            name='name',
            field=models.CharField(help_text='Admin label — e.g. "The Hindu"', max_length=200),
        ),
        migrations.AlterField(
            model_name='newssource',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated'),
        ),
        migrations.AlterField(
            model_name='newssource',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='newssource',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public UUID identifier (use this in APIs instead of PK)', unique=True),
        ),
        migrations.AlterField(
            model_name='quicklink',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created'),
        ),
        migrations.AlterField(
            model_name='quicklink',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quicklink',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True),
        ),
        migrations.AlterField(
            model_name='quicklink',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quicklink',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag. True means record is deleted.'),
        ),
        migrations.AlterField(
            model_name='quicklink',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated'),
        ),
        migrations.AlterField(
            model_name='quicklink',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quicklink',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public UUID identifier (use this in APIs instead of PK)', unique=True),
        ),
        migrations.AlterField(
            model_name='siteblock',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created'),
        ),
        migrations.AlterField(
            model_name='siteblock',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='siteblock',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True),
        ),
        migrations.AlterField(
            model_name='siteblock',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='siteblock',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag. True means record is deleted.'),
        ),
        migrations.AlterField(
            model_name='siteblock',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated'),
        ),
        migrations.AlterField(
            model_name='siteblock',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='siteblock',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public UUID identifier (use this in APIs instead of PK)', unique=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='designation',
            field=models.CharField(help_text='Full title — e.g. "Hon. Chief Minister"', max_length=300),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag. True means record is deleted.'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.database.models.cms._team_member_photo_path),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public UUID identifier (use this in APIs instead of PK)', unique=True),
        ),
        migrations.AlterField(
            model_name='visitorcount',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
