# Generated by Django 4.2.30 on 2026-07-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0032_fpo_claim_origin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fpo",
            name="district",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TVM", "Thiruvananthapuram"),
                    ("KLM", "Kollam"),
                    ("PTA", "Pathanamthitta"),
                    ("ALP", "Alappuzha"),
                    ("KTM", "Kottayam"),
                    ("IDK", "Idukki"),
                    ("EKM", "Ernakulam"),
                    ("TSR", "Thrissur"),
                    ("PKD", "Palakkad"),
                    ("MLP", "Malappuram"),
                    ("KZD", "Kozhikode"),
                    ("WYD", "Wayanad"),
                    ("KNR", "Kannur"),
                    ("KSD", "Kasaragod"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="fpo",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("under_review", "Under Review"),
                    ("info_required", "Additional Info Required"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("suspended", "Suspended"),
                    ("claimed", "Claimed (Ownership Transferred)"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="fpoownershipclaim",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("docs_requested", "Documents Requested"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=15,
            ),
        ),
    ]
