# Generated by Django 4.2.30 on 2026-07-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0033_claim_docs_requested_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationtemplate",
            name="sms_dlt_template_id",
            field=models.CharField(
                blank=True,
                help_text="DLT-registered template ID from TRAI portal. Required for SMS delivery in India. SMS channel only.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="fpodocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("fpo_reg_cert", "FPO Registration Certificate"),
                    ("bank_details", "Bank Account Details"),
                    ("signatory_id", "Authorized Signatory ID"),
                    ("pan_card", "PAN Card"),
                    ("gst_cert", "GST Certificate"),
                    ("annual_report", "Annual Report"),
                    ("member_list", "Member List"),
                    ("board_resolution", "Board Resolution"),
                    ("moa_aoa", "MOA/AOA"),
                    ("other", "Other Document"),
                    ("claim_support", "Ownership Claim Supporting Document"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="fpoownershipclaim",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("docs_requested", "Documents Requested"),
                    ("docs_submitted", "Documents Submitted"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=15,
            ),
        ),
    ]
