# Generated by Django 4.2.30 on 2026-07-23 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0034_sms_dlt_template_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fpo',
            name='origin_claim_email',
            field=models.EmailField(blank=True, help_text='Email used to submit the ownership claim that created this FPO', max_length=254),
        ),
    ]
