# Generated by Django 4.2.30 on 2026-07-24 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0035_fpo_origin_claim_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="fpoownershipclaim",
            name="matched_field",
            field=models.CharField(
                blank=True,
                help_text="The identity field that triggered duplicate detection (e.g. pan_number, gst_number)",
                max_length=50,
            ),
        ),
    ]
