# Generated by Django 4.2.30 on 2026-07-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0036_fpoownershipclaim_matched_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fpo',
            name='annual_turnover',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
    ]
