# Generated by Django 4.2.30 on 2026-08-21 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("database", "0041_buyerdirectory_chatconversation_dprproject_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIServiceConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag. True means record is deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Public UUID identifier (use this in APIs instead of PK)",
                        unique=True,
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("dpr_narratives", "DPR Narrative Generation"),
                            ("chatbot", "AI Chatbot"),
                            ("marketing", "Marketing Strategy AI"),
                            ("translate", "Auto-Translate AI"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Admin toggle — when False the feature returns fallback/placeholder response",
                    ),
                ),
                (
                    "monthly_cap_inr",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Monthly spend limit in INR. 0 = no cap.",
                        max_digits=10,
                    ),
                ),
                (
                    "alert_at_pct",
                    models.IntegerField(
                        default=80,
                        help_text="Send alert email when usage reaches this % of monthly cap",
                    ),
                ),
                (
                    "current_month_cost_inr",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Cumulative cost this calendar month (INR)",
                        max_digits=10,
                    ),
                ),
                (
                    "current_month_tokens",
                    models.BigIntegerField(
                        default=0, help_text="Total tokens used this calendar month"
                    ),
                ),
                (
                    "current_month_calls",
                    models.IntegerField(
                        default=0, help_text="Total API calls made this calendar month"
                    ),
                ),
                (
                    "alert_sent",
                    models.BooleanField(
                        default=False,
                        help_text="True once the 80% alert email has been sent this month — reset monthly",
                    ),
                ),
                (
                    "auto_disabled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this service was auto-disabled due to budget cap — cleared on monthly reset",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who deleted this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Service Config",
                "verbose_name_plural": "AI Service Configs",
                "ordering": ["service"],
            },
        ),
        migrations.CreateModel(
            name="AIUsageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag. True means record is deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Public UUID identifier (use this in APIs instead of PK)",
                        unique=True,
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("dpr_narratives", "DPR Narrative Generation"),
                            ("chatbot", "AI Chatbot"),
                            ("marketing", "Marketing Strategy AI"),
                            ("translate", "Auto-Translate AI"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "model_used",
                    models.CharField(
                        default="claude-sonnet-4-6",
                        help_text="Exact model ID used for this call",
                        max_length=100,
                    ),
                ),
                ("input_tokens", models.IntegerField(default=0)),
                ("output_tokens", models.IntegerField(default=0)),
                ("total_tokens", models.IntegerField(default=0)),
                (
                    "cost_usd",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                (
                    "cost_inr",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "reference_id",
                    models.CharField(
                        blank=True,
                        help_text="e.g. DPRProject ID or ChatConversation ID",
                        max_length=100,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who deleted this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fpo",
                    models.ForeignKey(
                        blank=True,
                        help_text="Which FPO triggered this call (null for system-level calls)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_usage_logs",
                        to="database.fpo",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_usage_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Usage Log",
                "verbose_name_plural": "AI Usage Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["service", "created_at"],
                        name="database_ai_service_006f0a_idx",
                    ),
                    models.Index(
                        fields=["fpo", "created_at"],
                        name="database_ai_fpo_id_6f99a7_idx",
                    ),
                ],
            },
        ),
    ]
