# Generated by Django 5.2.17 on 2026-08-20 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0041_agroclimaticzone_buyerdirectory_and_more"),
        ("database", "0041_buyerdirectory_chatconversation_dprproject_and_more"),
    ]

    operations = []
