# Generated by Django 4.2.30 on 2026-08-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0042_ai_service_config_usage_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiserviceconfig",
            name="api_key_encrypted",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Anthropic API key — stored encrypted. Set via admin API.",
            ),
        ),
        migrations.AddField(
            model_name="aiserviceconfig",
            name="usd_to_inr_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=84,
                help_text="USD → INR conversion rate for cost tracking",
                max_digits=8,
            ),
        ),
    ]
