# Generated by Django 5.2.17 on 2026-08-31 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0043_cbboassignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="governmentofficialprofile",
            name="assigned_block",
            field=models.CharField(
                blank=True,
                help_text="Block/taluk code, MasterLookup category: block — set when jurisdiction_type=block",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="governmentofficialprofile",
            name="assigned_district",
            field=models.CharField(
                blank=True,
                help_text="District code from constants.py — set when jurisdiction_type=district or block",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="governmentofficialprofile",
            name="jurisdiction_type",
            field=models.CharField(
                choices=[
                    ("district", "District"),
                    ("block", "Block"),
                    ("state", "State"),
                ],
                max_length=20,
            ),
        ),
    ]
