# Generated by Django 4.2.30 on 2026-08-24
#
# DPR v1 removal. Tables were dropped manually via SQL prior to this migration
# (see context/phase2/Dpr/DPR_V2_CONTEXT.md).
#
# All operations are wrapped in SeparateDatabaseAndState with empty
# database_operations, so this migration only updates Django's model
# state without attempting DDL against already-dropped tables.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0043_ai_service_config_api_key"),
    ]

    state_operations = [
        migrations.RemoveField(model_name="dprcalculation", name="created_by"),
        migrations.RemoveField(model_name="dprcalculation", name="deleted_by"),
        migrations.RemoveField(model_name="dprcalculation", name="project"),
        migrations.RemoveField(model_name="dprcalculation", name="updated_by"),
        migrations.RemoveField(model_name="dprdocument", name="created_by"),
        migrations.RemoveField(model_name="dprdocument", name="deleted_by"),
        migrations.RemoveField(model_name="dprdocument", name="project"),
        migrations.RemoveField(model_name="dprdocument", name="updated_by"),
        migrations.RemoveField(model_name="dprmasterconfig", name="created_by"),
        migrations.RemoveField(model_name="dprmasterconfig", name="deleted_by"),
        migrations.RemoveField(model_name="dprmasterconfig", name="updated_by"),
        migrations.RemoveField(model_name="dprproject", name="created_by"),
        migrations.RemoveField(model_name="dprproject", name="deleted_by"),
        migrations.RemoveField(model_name="dprproject", name="fpo"),
        migrations.RemoveField(model_name="dprproject", name="primary_commodity"),
        migrations.RemoveField(model_name="dprproject", name="updated_by"),
        migrations.AlterUniqueTogether(name="dprsection", unique_together=None),
        migrations.RemoveField(model_name="dprsection", name="created_by"),
        migrations.RemoveField(model_name="dprsection", name="deleted_by"),
        migrations.RemoveField(model_name="dprsection", name="project"),
        migrations.RemoveField(model_name="dprsection", name="updated_by"),
        migrations.DeleteModel(name="DPRAIContent"),
        migrations.DeleteModel(name="DPRCalculation"),
        migrations.DeleteModel(name="DPRDocument"),
        migrations.DeleteModel(name="DPRMasterConfig"),
        migrations.DeleteModel(name="DPRProject"),
        migrations.DeleteModel(name="DPRSection"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=state_operations,
            database_operations=[],
        ),
    ]
