# Generated by Django 5.2.17 on 2026-08-31 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0044_government_block_jurisdiction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="governmentofficialprofile",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="governmentofficialprofile",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_govt_officials",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="governmentofficialprofile",
            name="id_number",
            field=models.CharField(
                blank=True,
                help_text="PEN / PAN / CIN / Employee ID, format depends on user_category",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="governmentofficialprofile",
            name="registration_status",
            field=models.CharField(
                choices=[
                    ("approved", "Approved"),
                    ("pending", "Pending Approval"),
                    ("rejected", "Rejected"),
                ],
                default="approved",
                help_text="Self-registered accounts start pending; admin-created accounts are auto-approved",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="governmentofficialprofile",
            name="user_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("agri_officer", "Agri Officer"),
                    ("university_official", "University Official"),
                    ("sfac_official", "SFAC Official"),
                    ("cbbo_personnel", "CBBO Personnel"),
                    ("nabard_official", "NABARD Official"),
                    ("atma_specialist", "ATMA Specialist"),
                ],
                help_text="Determines ID number format validation",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="governmentofficialprofile",
            name="assigned_block",
            field=models.CharField(
                blank=True,
                help_text="Block/taluk code, MasterLookup category: block - set when jurisdiction_type=block",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="governmentofficialprofile",
            name="assigned_district",
            field=models.CharField(
                blank=True,
                help_text="District code from constants.py - set when jurisdiction_type=district or block",
                max_length=10,
                null=True,
            ),
        ),
    ]
