# Generated by Django 5.2.17 on 2026-08-24 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0044_agroclimaticzone_soil_type_fpoweathersnapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="croprecommendation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                help_text="Tracks the async request lifecycle — pending while queued for Celery, processing while the FastAPI call is in flight, completed/failed once resolved.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="croprecommendation",
            name="recommendations",
            field=models.JSONField(
                default=list,
                help_text="[{crop, confidence, reasoning, estimated_yield}]",
            ),
        ),
    ]
