# Generated by Django 4.2.30 on 2026-08-24 14:48

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_auditlog_action"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("database", "0045_dprwastetype_dprtrainingarea_dprtechnologyreason_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DPRProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag. True means record is deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Public UUID identifier (use this in APIs instead of PK)",
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Working title. Full §2.2 fields added in Phase 2.",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_progress", "In Progress"),
                            ("submitted", "Submitted"),
                            ("generated", "PDF Generated"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who deleted this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fpo",
                    models.ForeignKey(
                        help_text="FPO that owns this DPR project",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dpr_projects",
                        to="database.fpo",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DPR — Project",
                "verbose_name_plural": "DPR — Projects",
                "db_table": "dpr_project",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DPRSectionRawMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "procurement_model_other",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "procurement_frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("seasonal", "Seasonal"),
                            ("as_required", "As Required"),
                        ],
                        max_length=20,
                    ),
                ),
                ("collection_method", models.CharField(blank=True, max_length=500)),
                (
                    "transportation_arrangement",
                    models.CharField(blank=True, max_length=500),
                ),
                (
                    "avg_procurement_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "loading_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "unloading_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "sorting_grading_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "handling_charges",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "is_complete",
                    models.BooleanField(
                        default=False,
                        help_text="FPO marked section complete (frontend flag; server also runs validators)",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "procurement_model",
                    models.ForeignKey(
                        blank=True,
                        help_text="Overall procurement model (per-material method is on DPRRawMaterial.procurement_method)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="database.dprprocurementmodel",
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_raw_material",
                        to="database.dprproject",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DPR — Raw Material Section",
                "verbose_name_plural": "DPR — Raw Material Sections",
                "db_table": "dpr_section_raw_material",
            },
        ),
        migrations.CreateModel(
            name="DPRRawMaterialRisk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "risk_type",
                    models.CharField(
                        choices=[
                            ("seasonal_shortage", "Seasonal Shortage"),
                            ("climate_risk", "Climate Risk"),
                            ("pest_disease", "Pest and Disease"),
                            ("price_fluctuation", "Price Fluctuation"),
                            ("transportation", "Transportation Issues"),
                            ("labour_shortage", "Labour Shortage"),
                            ("competition", "Competition for Raw Material"),
                            ("quality_variation", "Quality Variation"),
                            ("import_dependence", "Import Dependence"),
                            ("other", "Other (Specify)"),
                        ],
                        max_length=30,
                    ),
                ),
                ("risk_type_other", models.CharField(blank=True, max_length=200)),
                ("mitigation_strategy", models.TextField()),
                ("existing_practices", models.TextField(blank=True)),
                ("previous_experience", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risks",
                        to="database.dprsectionrawmaterial",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DPR — Raw Material Risk",
                "verbose_name_plural": "DPR — Raw Material Risks",
                "db_table": "dpr_raw_material_risk",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="DPRRawMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Display order in UI table"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Raw material name (required)", max_length=200
                    ),
                ),
                ("scientific_name", models.CharField(blank=True, max_length=200)),
                ("variety_grade", models.CharField(blank=True, max_length=200)),
                (
                    "estimated_annual_requirement",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=15, null=True
                    ),
                ),
                (
                    "approx_purchase_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("primary_source_other", models.CharField(blank=True, max_length=200)),
                (
                    "procurement_method_other",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "avg_procurement_radius_km",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "estimated_qty_available_annual",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=15, null=True
                    ),
                ),
                ("num_supplying_farmers", models.IntegerField(blank=True, null=True)),
                ("num_supplying_villages", models.IntegerField(blank=True, null=True)),
                (
                    "available_months",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("jan", "January"),
                                ("feb", "February"),
                                ("mar", "March"),
                                ("apr", "April"),
                                ("may", "May"),
                                ("jun", "June"),
                                ("jul", "July"),
                                ("aug", "August"),
                                ("sep", "September"),
                                ("oct", "October"),
                                ("nov", "November"),
                                ("dec", "December"),
                            ],
                            max_length=3,
                        ),
                        blank=True,
                        default=list,
                        help_text='Months available (e.g. ["jan","feb","mar"])',
                        size=None,
                    ),
                ),
                ("available_throughout_year", models.BooleanField(default=False)),
                ("peak_harvest_season", models.CharField(blank=True, max_length=100)),
                ("lean_season", models.CharField(blank=True, max_length=100)),
                (
                    "storage_required",
                    models.BooleanField(
                        blank=True,
                        help_text="Nullable — only asked when NOT available year-round",
                        null=True,
                    ),
                ),
                ("off_season_strategy", models.TextField(blank=True)),
                (
                    "estimated_annual_production_area",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=15, null=True
                    ),
                ),
                (
                    "avg_procurement_distance_km",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("preservation_method", models.CharField(blank=True, max_length=200)),
                ("quality_standards_applicable", models.BooleanField(default=False)),
                ("grade", models.CharField(blank=True, max_length=100)),
                ("certification_required", models.BooleanField(blank=True, null=True)),
                (
                    "quality_testing_required",
                    models.BooleanField(blank=True, null=True),
                ),
                ("quality_remarks", models.TextField(blank=True)),
                (
                    "current_purchase_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "price_estimation_basis",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("recent_purchase", "Recent Purchase"),
                            ("supplier_quotation", "Supplier Quotation"),
                            ("market_survey", "Market Survey"),
                            ("govt_price", "Government Price"),
                            ("other", "Other (Specify)"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "price_estimation_basis_other",
                    models.CharField(blank=True, max_length=200),
                ),
                ("price_varies_seasonally", models.BooleanField(default=False)),
                ("peak_price_season", models.CharField(blank=True, max_length=100)),
                ("lowest_price_season", models.CharField(blank=True, max_length=100)),
                (
                    "price_variation_range",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low (<10%)"),
                            ("moderate", "Moderate (10–25%)"),
                            ("high", "High (>25%)"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "expected_future_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("historical_price_trend", models.TextField(blank=True)),
                (
                    "transportation_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "loading_charges",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "unloading_charges",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "commission_charges",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "storage_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "commodity",
                    models.ForeignKey(
                        blank=True,
                        help_text="Commodity category from cross-platform master",
                        limit_choices_to={"category": "commodity", "is_active": True},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.masterlookup",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "primary_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="database.dprrawmaterialsource",
                    ),
                ),
                (
                    "procurement_method",
                    models.ForeignKey(
                        blank=True,
                        help_text="Per-material procurement method (section-level model on DPRSectionRawMaterial.procurement_model)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="database.dprprocurementmodel",
                    ),
                ),
                (
                    "quality_parameters",
                    models.ManyToManyField(
                        blank=True, related_name="+", to="database.dprqualityparameter"
                    ),
                ),
                (
                    "quality_standard",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="database.dprqualitystandard",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="database.dprsectionrawmaterial",
                    ),
                ),
                (
                    "unit_of_purchase",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="database.dprcapacityunit",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DPR — Raw Material",
                "verbose_name_plural": "DPR — Raw Materials",
                "db_table": "dpr_raw_material",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="DPRPackagingMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("material_name", models.CharField(max_length=200)),
                ("purpose", models.CharField(blank=True, max_length=500)),
                (
                    "estimated_annual_requirement",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=15, null=True
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("supplier", models.CharField(blank=True, max_length=200)),
                (
                    "procurement_frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("seasonal", "Seasonal"),
                            ("as_required", "As Required"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "quality_standard",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="database.dprqualitystandard",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packaging_materials",
                        to="database.dprsectionrawmaterial",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="database.dprcapacityunit",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DPR — Packaging Material",
                "verbose_name_plural": "DPR — Packaging Materials",
                "db_table": "dpr_packaging_material",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="DPRConsumable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("name", models.CharField(max_length=200)),
                ("purpose", models.CharField(blank=True, max_length=500)),
                (
                    "estimated_annual_requirement",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=15, null=True
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("supplier", models.CharField(blank=True, max_length=200)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consumables",
                        to="database.dprsectionrawmaterial",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="database.dprcapacityunit",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DPR — Consumable",
                "verbose_name_plural": "DPR — Consumables",
                "db_table": "dpr_consumable",
                "ordering": ["order", "id"],
            },
        ),
    ]
