# Generated by Django 5.2.17 on 2026-08-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0045_croprecommendation_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externalapisettings",
            name="service",
            field=models.CharField(
                choices=[
                    ("pan_verification", "PAN Verification (Income Tax Dept API)"),
                    ("gstin_verification", "GSTIN Verification (GST API / GSP)"),
                    ("cin_verification", "CIN Verification (MCA21 Portal API)"),
                    ("weather_api", "Weather API (OpenWeatherMap)"),
                ],
                max_length=30,
                unique=True,
            ),
        ),
    ]
