# Generated by Django 4.2.30 on 2026-08-24 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "database",
            "0046_dprproject_dprsectionrawmaterial_dprrawmaterialrisk_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DPRIntendedMarket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Stable machine-readable identifier used in FK references and API payloads",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "label_en",
                    models.CharField(help_text="English display label", max_length=200),
                ),
                (
                    "label_ml",
                    models.CharField(
                        blank=True,
                        help_text="Malayalam display label (optional)",
                        max_length=200,
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Display order in dropdowns (ascending)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Uncheck to hide from FPO-facing dropdowns without deleting",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DPR — Intended Market",
                "verbose_name_plural": "DPR — Intended Markets",
                "db_table": "dpr_intended_market",
                "ordering": ["order", "code"],
                "abstract": False,
            },
        ),
    ]
