# Generated by Django 4.2.30 on 2026-08-24 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("database", "0047_dprintendedmarket"),
    ]

    operations = [
        migrations.CreateModel(
            name="DPRSectionMarket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "demand_exists",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("yes", "Yes"),
                            ("no", "No"),
                            ("not_sure", "Not Sure"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "estimated_annual_demand",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=18, null=True
                    ),
                ),
                (
                    "demand_basis",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("market_survey", "Market Survey"),
                            ("existing_sales", "Existing Sales"),
                            ("buyer_enquiry", "Buyer Enquiry"),
                            ("secondary_data", "Secondary Data"),
                            ("industry_report", "Industry Report"),
                            ("govt_stats", "Government Statistics"),
                            ("previous_experience", "Previous Experience"),
                            ("other", "Others (Specify)"),
                        ],
                        max_length=30,
                    ),
                ),
                ("demand_basis_other", models.CharField(blank=True, max_length=200)),
                (
                    "current_supply",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=18, null=True
                    ),
                ),
                (
                    "supply_gap",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=18, null=True
                    ),
                ),
                (
                    "expected_demand_growth_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("seasonal_demand_pattern", models.TextField(blank=True)),
                ("peak_demand_period", models.CharField(blank=True, max_length=200)),
                ("off_season_demand", models.CharField(blank=True, max_length=200)),
                ("has_existing_buyers", models.BooleanField(default=False)),
                (
                    "pricing_basis",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cost_plus", "Cost Plus Pricing"),
                            ("market_price", "Market Price"),
                            ("competitive", "Competitive Pricing"),
                            ("govt_support", "Government Support Price"),
                            ("contract", "Contract Price"),
                            ("negotiated", "Negotiated Price"),
                            ("export", "Export Price"),
                            ("other", "Others (Specify)"),
                        ],
                        max_length=30,
                    ),
                ),
                ("pricing_basis_other", models.CharField(blank=True, max_length=200)),
                (
                    "existing_market_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "competitor_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "expected_annual_price_increase_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("promotional_pricing_notes", models.TextField(blank=True)),
                ("seasonal_price_variation", models.TextField(blank=True)),
                (
                    "credit_sales_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "cash_sales_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "has_competitors",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("yes", "Yes"),
                            ("no", "No"),
                            ("not_sure", "Not Sure"),
                        ],
                        max_length=10,
                    ),
                ),
                ("is_branded", models.BooleanField(default=False)),
                (
                    "brand_name",
                    models.CharField(
                        blank=True,
                        help_text="Company-level brand (per-product brand on DPRMarketingProduct.proposed_brand_name)",
                        max_length=200,
                    ),
                ),
                ("existing_brand_name", models.CharField(blank=True, max_length=200)),
                ("packaging_strategy", models.TextField(blank=True)),
                ("label_design_available", models.BooleanField(default=False)),
                ("certification_logo", models.CharField(blank=True, max_length=200)),
                ("website", models.URLField(blank=True)),
                ("social_media_presence", models.TextField(blank=True)),
                ("is_complete", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_market",
                        to="database.dprproject",
                    ),
                ),
                (
                    "promotional_activities",
                    models.ManyToManyField(
                        blank=True,
                        related_name="+",
                        to="database.dprpromotionalactivity",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DPR — Market Section",
                "verbose_name_plural": "DPR — Market Sections",
                "db_table": "dpr_section_market",
            },
        ),
        migrations.CreateModel(
            name="DPRMarketingRisk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "risk_type",
                    models.CharField(
                        choices=[
                            ("price_fluctuation", "Price Fluctuation"),
                            ("market_competition", "Market Competition"),
                            ("consumer_preference", "Consumer Preference Change"),
                            ("transportation", "Transportation Constraints"),
                            ("demand_reduction", "Demand Reduction"),
                            ("quality_issues", "Quality Issues"),
                            ("branding_challenges", "Branding Challenges"),
                            ("other", "Others (Specify)"),
                        ],
                        max_length=30,
                    ),
                ),
                ("risk_type_other", models.CharField(blank=True, max_length=200)),
                ("mitigation_strategy", models.TextField()),
                ("existing_practices", models.TextField(blank=True)),
                ("import_competition", models.TextField(blank=True)),
                ("export_restrictions", models.TextField(blank=True)),
                ("certification_issues", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risks",
                        to="database.dprsectionmarket",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DPR — Marketing Risk",
                "verbose_name_plural": "DPR — Marketing Risks",
                "db_table": "dpr_marketing_risk",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="DPRMarketingProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("name", models.CharField(max_length=200)),
                (
                    "geographic_market",
                    models.CharField(
                        blank=True,
                        help_text="Free text — cities / regions / states",
                        max_length=500,
                    ),
                ),
                (
                    "proposed_brand_name",
                    models.CharField(
                        blank=True,
                        help_text="Per-product brand (section-level company brand on DPRSectionMarket.brand_name)",
                        max_length=200,
                    ),
                ),
                ("existing_brand_name", models.CharField(blank=True, max_length=200)),
                (
                    "proposed_selling_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "year1_qty",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=18, null=True
                    ),
                ),
                (
                    "year2_qty",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=18, null=True
                    ),
                ),
                (
                    "year3_qty",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=18, null=True
                    ),
                ),
                (
                    "year4_qty",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=18, null=True
                    ),
                ),
                (
                    "year5_qty",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=18, null=True
                    ),
                ),
                (
                    "domestic_sales_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "export_sales_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "institutional_sales_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "retail_sales_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "wholesale_sales_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "online_sales_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer_categories",
                    models.ManyToManyField(
                        blank=True, related_name="+", to="database.dprcustomercategory"
                    ),
                ),
                (
                    "intended_market",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="database.dprintendedmarket",
                    ),
                ),
                (
                    "product_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="database.dprproductcategory",
                    ),
                ),
                (
                    "product_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Primary / Secondary / By-product",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="database.dprproducttype",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="database.dprsectionmarket",
                    ),
                ),
                (
                    "unit_of_sale",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="database.dprcapacityunit",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DPR — Marketing Product",
                "verbose_name_plural": "DPR — Marketing Products",
                "db_table": "dpr_marketing_product",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="DPRMarketingCompetitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("name", models.CharField(max_length=200)),
                (
                    "competitor_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("local", "Local"),
                            ("regional", "Regional"),
                            ("national", "National"),
                            ("international", "International"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "competitive_advantage",
                    models.TextField(
                        help_text="Advantage of our project over this competitor — spec requires at least one when competitors exist"
                    ),
                ),
                ("differentiation_strategy", models.TextField(blank=True)),
                ("num_competitors", models.IntegerField(blank=True, null=True)),
                (
                    "estimated_market_share_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("strengths", models.TextField(blank=True)),
                ("weaknesses", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competitors",
                        to="database.dprsectionmarket",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DPR — Marketing Competitor",
                "verbose_name_plural": "DPR — Marketing Competitors",
                "db_table": "dpr_marketing_competitor",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="DPRMarketingBuyer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "buyer_name",
                    models.CharField(
                        blank=True, help_text="Optional per spec", max_length=200
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=300)),
                (
                    "purchase_frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("seasonal", "Seasonal"),
                            ("as_required", "As Required"),
                        ],
                        max_length=20,
                    ),
                ),
                ("num_buyers", models.IntegerField(blank=True, null=True)),
                (
                    "avg_quantity_purchased",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=18, null=True
                    ),
                ),
                ("has_purchase_agreement", models.BooleanField(blank=True, null=True)),
                ("has_contract", models.BooleanField(blank=True, null=True)),
                ("credit_period_days", models.IntegerField(blank=True, null=True)),
                (
                    "buyer_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="database.dprbuyertype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buyers",
                        to="database.dprsectionmarket",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DPR — Marketing Buyer",
                "verbose_name_plural": "DPR — Marketing Buyers",
                "db_table": "dpr_marketing_buyer",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="DPRMarketingChannelSelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "channel_other",
                    models.CharField(
                        blank=True,
                        help_text='Only used when channel.code == "other"',
                        max_length=200,
                    ),
                ),
                (
                    "expected_share_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("existing_arrangement", models.TextField(blank=True)),
                ("remarks", models.TextField(blank=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="database.dprmarketingchannel",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channel_selections",
                        to="database.dprsectionmarket",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DPR — Marketing Channel Selection",
                "verbose_name_plural": "DPR — Marketing Channel Selections",
                "db_table": "dpr_marketing_channel_selection",
                "ordering": ["id"],
                "unique_together": {("section", "channel")},
            },
        ),
    ]
