# Generated by Django 4.2.30 on 2026-08-24 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("database", "0048_dprsectionmarket_dprmarketingrisk_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DPRSectionComponents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "other_primary_production",
                    models.CharField(blank=True, max_length=200),
                ),
                ("other_processing", models.CharField(blank=True, max_length=200)),
                ("other_storage", models.CharField(blank=True, max_length=200)),
                ("other_marketing", models.CharField(blank=True, max_length=200)),
                ("other_service", models.CharField(blank=True, max_length=200)),
                ("other_supporting", models.CharField(blank=True, max_length=200)),
                ("is_complete", models.BooleanField(default=False)),
                (
                    "components",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Selected project components (multi-select across 6 KAU groups)",
                        related_name="+",
                        to="database.dprcomponent",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_components",
                        to="database.dprproject",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DPR — Components Section",
                "verbose_name_plural": "DPR — Components Sections",
                "db_table": "dpr_section_components",
            },
        ),
    ]
