# Generated by Django 4.2.30 on 2026-08-24 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("database", "0049_dprsectioncomponents"),
    ]

    operations = [
        migrations.CreateModel(
            name="DPRSectionNatureOfBusiness",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "nature_other",
                    models.CharField(
                        blank=True,
                        help_text='Populated when the "other" master row is included in natures',
                        max_length=200,
                    ),
                ),
                ("is_complete", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "natures",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Selected nature(s) of business — multi-select",
                        related_name="+",
                        to="database.dprnatureofbusiness",
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_nature_of_business",
                        to="database.dprproject",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DPR — Nature of Business Section",
                "verbose_name_plural": "DPR — Nature of Business Sections",
                "db_table": "dpr_section_nature_of_business",
            },
        ),
    ]
