# Generated by Django 4.2.30 on 2026-08-24 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("database", "0050_dprsectionnatureofbusiness"),
    ]

    operations = [
        migrations.CreateModel(
            name="DPRSectionInvestment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "estimated_project_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Optional. If provided, system compares against auto-computed cost during DPR generation.",
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "basis_of_estimate",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("consultant", "Consultant Estimate"),
                            ("preliminary_fpo", "Preliminary Estimate by FPO"),
                            ("machinery_quote", "Machinery Quotations"),
                            ("civil_estimate", "Civil Estimate"),
                            ("govt_estimate", "Government Estimate"),
                            ("not_yet_estimated", "Not Yet Estimated"),
                        ],
                        max_length=30,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("is_complete", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_investment",
                        to="database.dprproject",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DPR — Investment Section",
                "verbose_name_plural": "DPR — Investment Sections",
                "db_table": "dpr_section_investment",
            },
        ),
    ]
