# Generated by Django 4.2.30 on 2026-08-24 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("database", "0052_dprsectionproducts_dprproductitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="DPRSectionLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "state",
                    models.CharField(blank=True, default="Kerala", max_length=100),
                ),
                ("district", models.CharField(blank=True, max_length=100)),
                ("taluk", models.CharField(blank=True, max_length=100)),
                ("block_panchayat", models.CharField(blank=True, max_length=100)),
                (
                    "local_body_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("grama_panchayat", "Grama Panchayat"),
                            ("municipality", "Municipality"),
                            ("corporation", "Corporation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("local_body_name", models.CharField(blank=True, max_length=200)),
                ("village", models.CharField(blank=True, max_length=100)),
                ("ward_number", models.CharField(blank=True, max_length=50)),
                ("survey_number", models.CharField(blank=True, max_length=100)),
                ("project_address", models.TextField(blank=True)),
                ("landmark", models.CharField(blank=True, max_length=200)),
                ("pin_code", models.CharField(blank=True, max_length=10)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("google_map_url", models.URLField(blank=True)),
                ("land_ownership_other", models.CharField(blank=True, max_length=200)),
                ("site_status_other", models.CharField(blank=True, max_length=200)),
                (
                    "dist_nearest_main_road_km",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "dist_nearest_market_km",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "dist_nearest_collection_centre_km",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "dist_railway_station_km",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "dist_airport_km",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "dist_seaport_km",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "road_connectivity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                        ],
                        max_length=20,
                    ),
                ),
                ("has_fibre", models.BooleanField(default=False)),
                ("has_broadband", models.BooleanField(default=False)),
                ("has_mobile_network", models.BooleanField(default=False)),
                ("internet_unavailable", models.BooleanField(default=False)),
                ("is_complete", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "land_ownership_types",
                    models.ManyToManyField(
                        blank=True, related_name="+", to="database.dprlandownershiptype"
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_location",
                        to="database.dprproject",
                    ),
                ),
                (
                    "site_statuses",
                    models.ManyToManyField(
                        blank=True, related_name="+", to="database.dprsitestatus"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DPR — Location Section",
                "verbose_name_plural": "DPR — Location Sections",
                "db_table": "dpr_section_location",
            },
        ),
    ]
