# Generated by Django 4.2.30 on 2026-08-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0054_dprsectionrationale_dprrationaleselection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dprrationaleselection",
            name="justification",
            field=models.TextField(
                blank=True,
                help_text="Brief justification, max 100 words per KAU spec §2.3.7. Enforced by validator, not by serializer, so readiness endpoint can report the actual error.",
            ),
        ),
    ]
