# Generated by Django 4.2.30 on 2026-08-24 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("database", "0055_alter_dprrationaleselection_justification"),
    ]

    operations = [
        migrations.CreateModel(
            name="DPRSectionBaseline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "currently_engaged",
                    models.BooleanField(
                        blank=True,
                        help_text="True = existing enterprise, False = new venture. Null = not yet answered.",
                        null=True,
                    ),
                ),
                (
                    "existing_products",
                    models.TextField(
                        blank=True, help_text="Existing product(s) / service(s)"
                    ),
                ),
                (
                    "existing_installed_capacity",
                    models.CharField(blank=True, max_length=300),
                ),
                (
                    "current_annual_production",
                    models.CharField(blank=True, max_length=300),
                ),
                (
                    "current_annual_turnover",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                ("existing_infrastructure", models.TextField(blank=True)),
                ("existing_machinery", models.TextField(blank=True)),
                ("num_employees", models.IntegerField(blank=True, null=True)),
                ("existing_market_coverage", models.TextField(blank=True)),
                ("major_challenges", models.TextField(blank=True)),
                (
                    "current_capacity_utilization_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("existing_certifications", models.TextField(blank=True)),
                ("reason_for_proposing", models.TextField(blank=True)),
                ("previous_experience", models.TextField(blank=True)),
                ("technical_guidance_available", models.TextField(blank=True)),
                ("proposed_implementation_approach", models.TextField(blank=True)),
                ("similar_projects_visited", models.TextField(blank=True)),
                ("is_complete", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_baseline",
                        to="database.dprproject",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DPR — Baseline Section",
                "verbose_name_plural": "DPR — Baseline Sections",
                "db_table": "dpr_section_baseline",
            },
        ),
    ]
