# Generated by Django 4.2.30 on 2026-08-24 17:17

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("database", "0056_dprsectionbaseline"),
    ]

    operations = [
        migrations.CreateModel(
            name="DPRSectionCapacity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "installed_capacity",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=18, null=True
                    ),
                ),
                (
                    "practical_operating_capacity",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=18, null=True
                    ),
                ),
                (
                    "first_year_capacity_utilisation_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("has_future_expansion", models.BooleanField(default=False)),
                ("working_days_per_year", models.IntegerField(blank=True, null=True)),
                ("shifts_per_day", models.IntegerField(blank=True, null=True)),
                (
                    "operating_hours_per_shift",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "operating_months_per_year",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "peak_production_seasons",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("jan", "January"),
                                ("feb", "February"),
                                ("mar", "March"),
                                ("apr", "April"),
                                ("may", "May"),
                                ("jun", "June"),
                                ("jul", "July"),
                                ("aug", "August"),
                                ("sep", "September"),
                                ("oct", "October"),
                                ("nov", "November"),
                                ("dec", "December"),
                            ],
                            max_length=3,
                        ),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "lean_production_seasons",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("jan", "January"),
                                ("feb", "February"),
                                ("mar", "March"),
                                ("apr", "April"),
                                ("may", "May"),
                                ("jun", "June"),
                                ("jul", "July"),
                                ("aug", "August"),
                                ("sep", "September"),
                                ("oct", "October"),
                                ("nov", "November"),
                                ("dec", "December"),
                            ],
                            max_length=3,
                        ),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "process_description",
                    models.TextField(
                        blank=True,
                        help_text="Max 150 words per KAU spec. Enforced by validator.",
                    ),
                ),
                (
                    "process_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("batch", "Batch Process"),
                            ("continuous", "Continuous Process"),
                            ("seasonal", "Seasonal Process"),
                            ("service_based", "Service-based Operation"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "automation_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("manual", "Manual"),
                            ("semi_auto", "Semi-Automatic"),
                            ("auto", "Automatic"),
                            ("fully_auto", "Fully Automatic"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "major_activities",
                    models.TextField(
                        blank=True,
                        help_text="Free text for Phase 2. Phase 3 will convert to component-driven M2M via dynamic questionnaire engine.",
                    ),
                ),
                ("technology_method", models.CharField(blank=True, max_length=300)),
                ("has_production_loss", models.BooleanField(default=False)),
                (
                    "production_loss_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "product_recovery_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "loss_sources",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("raw_material", "Raw Material"),
                                ("processing", "Processing"),
                                ("storage", "Storage"),
                                ("transportation", "Transportation"),
                                ("packaging", "Packaging"),
                                ("other", "Others (Specify)"),
                            ],
                            max_length=20,
                        ),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("loss_source_other", models.CharField(blank=True, max_length=200)),
                (
                    "expected_year_of_expansion",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "expansion_nature",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("capacity", "Capacity Expansion"),
                            ("product", "Product Diversification"),
                            ("infrastructure", "Infrastructure Expansion"),
                            ("technology", "Technology Upgradation"),
                            ("market", "Market Expansion"),
                            ("other", "Others (Specify)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "expansion_nature_other",
                    models.CharField(blank=True, max_length=200),
                ),
                ("expansion_description", models.TextField(blank=True)),
                ("is_complete", models.BooleanField(default=False)),
                (
                    "capacity_basis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="database.dprcapacitybasis",
                    ),
                ),
                (
                    "capacity_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="database.dprcapacityunit",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_capacity",
                        to="database.dprproject",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DPR — Capacity Section",
                "verbose_name_plural": "DPR — Capacity Sections",
                "db_table": "dpr_section_capacity",
            },
        ),
    ]
