# Generated by Django 4.2.30 on 2026-08-24 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("database", "0057_dprsectioncapacity"),
    ]

    operations = [
        migrations.CreateModel(
            name="DPRSectionTechnology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                ("is_complete", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_technology",
                        to="database.dprproject",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DPR — Technology Section",
                "verbose_name_plural": "DPR — Technology Sections",
                "db_table": "dpr_section_technology",
            },
        ),
        migrations.CreateModel(
            name="DPRTechnology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("name", models.CharField(max_length=200)),
                (
                    "nature",
                    models.CharField(
                        blank=True,
                        help_text="Nature of technology (free text)",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Max 150 words per KAU spec, enforced by validator",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True, help_text="Source of technology", max_length=200
                    ),
                ),
                ("technology_provider", models.CharField(blank=True, max_length=200)),
                ("country_of_origin", models.CharField(blank=True, max_length=100)),
                ("year_introduced", models.IntegerField(blank=True, null=True)),
                (
                    "technology_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("proven", "Proven Technology"),
                            ("commercial", "Commercially Established"),
                            ("pilot", "Pilot Technology"),
                            ("emerging", "Emerging Technology"),
                            ("indigenous", "Indigenous Technology"),
                            ("imported", "Imported Technology"),
                            ("traditional", "Traditional Technology"),
                            ("other", "Others (Specify)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "technology_status_other",
                    models.CharField(blank=True, max_length=200),
                ),
                ("reasons_other", models.CharField(blank=True, max_length=200)),
                (
                    "selection_justification",
                    models.TextField(
                        blank=True,
                        help_text="Brief justification, max 100 words per KAU spec",
                    ),
                ),
                ("process_description", models.TextField(blank=True)),
                (
                    "process_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("batch", "Batch Process"),
                            ("continuous", "Continuous Process"),
                            ("seasonal", "Seasonal Process"),
                            ("service_based", "Service-based Operation"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "automation_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("manual", "Manual"),
                            ("semi_auto", "Semi-Automatic"),
                            ("auto", "Automatic"),
                            ("fully_auto", "Fully Automatic"),
                        ],
                        max_length=20,
                    ),
                ),
                ("process_flow_sequence", models.TextField(blank=True)),
                ("critical_control_points", models.TextField(blank=True)),
                ("quality_control_points", models.TextField(blank=True)),
                ("bottleneck_operations", models.TextField(blank=True)),
                (
                    "expected_production_efficiency",
                    models.CharField(blank=True, max_length=200),
                ),
                ("expected_recovery", models.CharField(blank=True, max_length=200)),
                ("energy_efficiency", models.CharField(blank=True, max_length=200)),
                ("water_efficiency", models.CharField(blank=True, max_length=200)),
                ("labour_efficiency", models.CharField(blank=True, max_length=200)),
                ("machine_utilisation", models.CharField(blank=True, max_length=200)),
                ("maintenance_frequency", models.CharField(blank=True, max_length=200)),
                (
                    "expected_technology_life_years",
                    models.IntegerField(blank=True, null=True),
                ),
                ("quality_standards_applicable", models.BooleanField(default=False)),
                (
                    "product_quality_standard",
                    models.CharField(blank=True, max_length=200),
                ),
                ("certification_required", models.BooleanField(blank=True, null=True)),
                ("product_specification", models.TextField(blank=True)),
                ("testing_requirement", models.TextField(blank=True)),
                ("laboratory_requirement", models.TextField(blank=True)),
                ("traceability_requirement", models.TextField(blank=True)),
                ("food_safety_requirement", models.TextField(blank=True)),
                ("certifications_other", models.CharField(blank=True, max_length=200)),
                (
                    "requires_skilled_operators",
                    models.BooleanField(blank=True, null=True),
                ),
                ("requires_training", models.BooleanField(blank=True, null=True)),
                ("technical_expert_available", models.TextField(blank=True)),
                ("requires_consultant", models.BooleanField(blank=True, null=True)),
                ("tech_transfer_agreement", models.BooleanField(blank=True, null=True)),
                ("technical_collaboration", models.TextField(blank=True)),
                ("amc_requirement", models.BooleanField(blank=True, null=True)),
                (
                    "vendor_support_available",
                    models.BooleanField(blank=True, null=True),
                ),
                ("upgradation_planned", models.BooleanField(default=False)),
                ("upgradation_year", models.IntegerField(blank=True, null=True)),
                ("upgradation_description", models.TextField(blank=True)),
                (
                    "upgradation_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                ("additional_infra_required", models.TextField(blank=True)),
                ("additional_machinery_required", models.TextField(blank=True)),
                (
                    "certifications",
                    models.ManyToManyField(
                        blank=True, related_name="+", to="database.dprqualitystandard"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reasons",
                    models.ManyToManyField(
                        blank=True, related_name="+", to="database.dprtechnologyreason"
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technologies",
                        to="database.dprsectiontechnology",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DPR — Technology",
                "verbose_name_plural": "DPR — Technologies",
                "db_table": "dpr_technology",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="DPRTechnologyRisk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "risk_type",
                    models.CharField(
                        choices=[
                            ("obsolescence", "Technology Obsolescence"),
                            ("skilled_labour", "Skilled Labour Shortage"),
                            ("spare_parts", "Spare Parts Availability"),
                            ("breakdown", "Frequent Breakdown"),
                            ("high_maintenance", "High Maintenance Cost"),
                            ("vendor_dependency", "Vendor Dependency"),
                            ("utility_dependency", "Utility Dependency"),
                            ("quality_issues", "Product Quality Issues"),
                            ("other", "Others (Specify)"),
                        ],
                        max_length=30,
                    ),
                ),
                ("risk_type_other", models.CharField(blank=True, max_length=200)),
                (
                    "mitigation_measure",
                    models.TextField(
                        blank=True,
                        help_text="Required per KAU spec — enforced by validator, not model, so readiness can report it",
                    ),
                ),
                ("existing_practice", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "technology",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risks",
                        to="database.dprtechnology",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DPR — Technology Risk",
                "verbose_name_plural": "DPR — Technology Risks",
                "db_table": "dpr_technology_risk",
                "ordering": ["id"],
            },
        ),
    ]
