# Generated by Django 4.2.30 on 2026-08-24 17:33

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("database", "0058_dprsectiontechnology_dprtechnology_dprtechnologyrisk"),
    ]

    operations = [
        migrations.CreateModel(
            name="DPRSectionSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "terrain",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("plain", "Plain"),
                            ("undulating", "Undulating"),
                            ("hilly", "Hilly"),
                            ("coastal", "Coastal"),
                            ("river_basin", "River Basin"),
                            ("other", "Others (Specify)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("terrain_other", models.CharField(blank=True, max_length=200)),
                ("is_flood_prone", models.BooleanField(blank=True, null=True)),
                (
                    "water_available_year_round",
                    models.BooleanField(blank=True, null=True),
                ),
                ("topography", models.CharField(blank=True, max_length=200)),
                ("soil_type", models.CharField(blank=True, max_length=200)),
                ("soil_bearing_capacity", models.CharField(blank=True, max_length=200)),
                ("water_logging", models.CharField(blank=True, max_length=200)),
                ("drainage_condition", models.CharField(blank=True, max_length=200)),
                ("slope", models.CharField(blank=True, max_length=200)),
                ("ground_water_level", models.CharField(blank=True, max_length=200)),
                (
                    "dist_major_market_km",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "dist_major_raw_material_source_km",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "dist_all_weather_road_km",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "dist_state_highway_km",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "dist_national_highway_km",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "dist_railway_station_km",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "dist_airport_km",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "dist_seaport_km",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "dist_collection_centre_km",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "dist_processing_centre_km",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "electricity_availability",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("available", "Available"),
                            ("proposed", "Proposed"),
                            ("not_available", "Not Available"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "water_availability",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("available", "Available"),
                            ("not_available", "Not Available"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "road_connectivity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "water_sources",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("borewell", "Borewell"),
                                ("open_well", "Open Well"),
                                ("panchayat_supply", "Panchayat Supply"),
                                ("river", "River"),
                                ("canal", "Canal"),
                                ("tank", "Tank"),
                                ("other", "Others"),
                            ],
                            max_length=30,
                        ),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("water_source_other", models.CharField(blank=True, max_length=200)),
                ("has_fibre", models.BooleanField(default=False)),
                ("has_broadband", models.BooleanField(default=False)),
                ("has_mobile_network", models.BooleanField(default=False)),
                ("internet_unavailable", models.BooleanField(default=False)),
                (
                    "approvals_available",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("land_conversion", "Land Conversion"),
                                ("building_permit", "Building Permit"),
                                ("factory_licence", "Factory Licence"),
                                ("pollution_clearance", "Pollution Control Clearance"),
                                ("fire_safety", "Fire & Safety Approval"),
                                ("electrical_approval", "Electrical Approval"),
                                ("ground_water_permit", "Ground Water Permission"),
                                ("panchayat_approval", "Panchayat Approval"),
                                ("municipality_approval", "Municipality Approval"),
                                ("environmental_clearance", "Environmental Clearance"),
                                ("other", "Others (Specify)"),
                            ],
                            max_length=30,
                        ),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("approvals_other", models.CharField(blank=True, max_length=300)),
                ("pending_approvals_remarks", models.TextField(blank=True)),
                ("has_future_expansion", models.BooleanField(default=False)),
                (
                    "additional_land_available",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "area_reserved_for_expansion",
                    models.CharField(blank=True, max_length=200),
                ),
                ("future_buildings_planned", models.TextField(blank=True)),
                ("utility_expansion_feasibility", models.TextField(blank=True)),
                ("is_complete", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_site",
                        to="database.dprproject",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DPR — Site Section",
                "verbose_name_plural": "DPR — Site Sections",
                "db_table": "dpr_section_site",
            },
        ),
        migrations.CreateModel(
            name="DPRSiteConstraint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "constraint_type",
                    models.CharField(
                        choices=[
                            ("flooding", "Flooding"),
                            ("water_scarcity", "Water Scarcity"),
                            ("power_shortage", "Power Shortage"),
                            ("poor_road_access", "Poor Road Access"),
                            ("land_dispute", "Land Dispute"),
                            ("env_restriction", "Environmental Restriction"),
                            ("wildlife_restriction", "Wildlife Restriction"),
                            ("crz_restriction", "CRZ Restriction"),
                            ("forest_land", "Forest Land"),
                            ("high_transport_cost", "High Transportation Cost"),
                            ("labour_shortage", "Labour Shortage"),
                            ("other", "Others (Specify)"),
                        ],
                        max_length=30,
                    ),
                ),
                ("constraint_type_other", models.CharField(blank=True, max_length=200)),
                (
                    "mitigation_measure",
                    models.TextField(
                        blank=True,
                        help_text="Required per KAU spec — enforced by validator",
                    ),
                ),
                ("existing_situation", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="constraints",
                        to="database.dprsectionsite",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DPR — Site Constraint",
                "verbose_name_plural": "DPR — Site Constraints",
                "db_table": "dpr_site_constraint",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="DPRLandParcel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "total_land_available",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                (
                    "land_proposed_for_project",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                ("village", models.CharField(blank=True, max_length=100)),
                ("taluk", models.CharField(blank=True, max_length=100)),
                ("district", models.CharField(blank=True, max_length=100)),
                ("ownership_other", models.CharField(blank=True, max_length=200)),
                ("survey_number", models.CharField(blank=True, max_length=200)),
                ("resurvey_number", models.CharField(blank=True, max_length=200)),
                ("date_of_acquisition", models.DateField(blank=True, null=True)),
                ("present_land_use", models.CharField(blank=True, max_length=200)),
                ("previous_land_use", models.CharField(blank=True, max_length=200)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ownership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="database.dprlandownershiptype",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parcels",
                        to="database.dprsectionsite",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="database.dprcapacityunit",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DPR — Land Parcel",
                "verbose_name_plural": "DPR — Land Parcels",
                "db_table": "dpr_land_parcel",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="DPRExistingInfrastructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "infrastructure_type",
                    models.CharField(
                        choices=[
                            ("approach_road", "Approach Road"),
                            ("office_building", "Office Building"),
                            ("storage_building", "Storage Building"),
                            ("processing_shed", "Processing Shed"),
                            ("electricity", "Electricity"),
                            ("drinking_water", "Drinking Water"),
                            ("toilets", "Toilets"),
                            ("drainage", "Drainage"),
                            ("other", "Others (Specify)"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "infrastructure_type_other",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "condition",
                    models.CharField(
                        blank=True,
                        help_text="Existing condition (free text)",
                        max_length=200,
                    ),
                ),
                (
                    "approximate_area",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("year_of_construction", models.IntegerField(blank=True, null=True)),
                ("renovation_required", models.BooleanField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="existing_infrastructure",
                        to="database.dprsectionsite",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DPR — Existing Infrastructure",
                "verbose_name_plural": "DPR — Existing Infrastructure Items",
                "db_table": "dpr_existing_infrastructure",
                "ordering": ["order", "id"],
            },
        ),
    ]
