# Generated by Django 4.2.30 on 2026-08-24 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("database", "0059_dprsectionsite_dprsiteconstraint_dprlandparcel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DPRSectionCivil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                ("has_civil_cost_estimate", models.BooleanField(default=False)),
                (
                    "cost_site_development",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "cost_building_construction",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "cost_internal_roads",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "cost_compound_wall",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "cost_drainage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "cost_water_supply",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "cost_sanitation",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "cost_electrical",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "cost_fire_protection",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "cost_landscaping",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "cost_other_civil",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "basis_of_estimate",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("engineer", "Engineer's Estimate"),
                            ("contractor", "Contractor Quotation"),
                            ("similar", "Previous Similar Project"),
                            ("consultant", "Consultant Estimate"),
                            ("other", "Others (Specify)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "basis_of_estimate_other",
                    models.CharField(blank=True, max_length=200),
                ),
                ("has_future_expansion", models.BooleanField(default=False)),
                (
                    "space_reserved_for_expansion",
                    models.CharField(blank=True, max_length=200),
                ),
                ("future_buildings_planned", models.TextField(blank=True)),
                ("future_civil_works_required", models.TextField(blank=True)),
                (
                    "estimated_future_investment",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                ("is_complete", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_civil",
                        to="database.dprproject",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DPR — Civil Section",
                "verbose_name_plural": "DPR — Civil Sections",
                "db_table": "dpr_section_civil",
            },
        ),
        migrations.CreateModel(
            name="DPRSiteDevelopmentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("category_other", models.CharField(blank=True, max_length=200)),
                (
                    "estimated_quantity",
                    models.CharField(
                        blank=True,
                        help_text='Free text — e.g. "500 m", "2 units"',
                        max_length=200,
                    ),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="database.dprcivilcategory",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_development_items",
                        to="database.dprsectioncivil",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DPR — Site Development Item",
                "verbose_name_plural": "DPR — Site Development Items",
                "db_table": "dpr_site_development_item",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="DPRProposedBuilding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("building_type_other", models.CharField(blank=True, max_length=200)),
                ("purpose", models.CharField(blank=True, max_length=500)),
                (
                    "floor_area",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "area_unit",
                    models.CharField(
                        blank=True,
                        choices=[("sqft", "sq. ft."), ("sqm", "sq. m.")],
                        max_length=10,
                    ),
                ),
                (
                    "proposed_location_within_site",
                    models.CharField(blank=True, max_length=300),
                ),
                ("num_floors", models.IntegerField(blank=True, null=True)),
                (
                    "estimated_construction_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "estimated_completion_period",
                    models.CharField(
                        blank=True, help_text='e.g. "6 months"', max_length=100
                    ),
                ),
                (
                    "building_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="database.dprbuildingtype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposed_buildings",
                        to="database.dprsectioncivil",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DPR — Proposed Building",
                "verbose_name_plural": "DPR — Proposed Buildings",
                "db_table": "dpr_proposed_building",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="DPRExistingBuilding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("building_name", models.CharField(max_length=200)),
                ("purpose", models.CharField(blank=True, max_length=500)),
                (
                    "floor_area",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "area_unit",
                    models.CharField(
                        blank=True,
                        choices=[("sqft", "sq. ft."), ("sqm", "sq. m.")],
                        max_length=10,
                    ),
                ),
                ("present_condition", models.CharField(blank=True, max_length=200)),
                (
                    "ownership_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("fpo_owned", "FPO Owned"),
                            ("member_owned", "Member Owned"),
                            ("leased", "Leased"),
                            ("rented", "Rented"),
                            ("govt_allotted", "Government Allotted"),
                            ("other", "Others"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "proposed_action",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("continue", "Continue as Existing"),
                            ("renovate", "Renovate"),
                            ("expand", "Expand"),
                            ("demolish", "Demolish"),
                            ("convert_use", "Convert to Different Use"),
                        ],
                        max_length=20,
                    ),
                ),
                ("year_of_construction", models.IntegerField(blank=True, null=True)),
                ("num_floors", models.IntegerField(blank=True, null=True)),
                ("current_utilisation", models.CharField(blank=True, max_length=200)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="existing_buildings",
                        to="database.dprsectioncivil",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DPR — Existing Building",
                "verbose_name_plural": "DPR — Existing Buildings",
                "db_table": "dpr_existing_building",
                "ordering": ["order", "id"],
            },
        ),
    ]
