# Generated by Django 4.2.30 on 2026-08-24 17:48

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("database", "0060_dprsectioncivil_dprsitedevelopmentitem_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DPRSectionMachinery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "statutory_approvals",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("factory_inspector", "Factory Inspector Approval"),
                                (
                                    "electrical_inspector",
                                    "Electrical Inspector Approval",
                                ),
                                ("boiler_inspection", "Boiler Inspection"),
                                ("calibration", "Calibration"),
                                ("safety_cert", "Safety Certification"),
                                ("pollution_control", "Pollution Control Approval"),
                                ("food_safety", "Food Safety Compliance"),
                                ("other", "Others (Specify)"),
                            ],
                            max_length=30,
                        ),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "statutory_approvals_other",
                    models.CharField(blank=True, max_length=300),
                ),
                ("statutory_remarks", models.TextField(blank=True)),
                ("is_complete", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_machinery",
                        to="database.dprproject",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DPR — Machinery Section",
                "verbose_name_plural": "DPR — Machinery Sections",
                "db_table": "dpr_section_machinery",
            },
        ),
        migrations.CreateModel(
            name="DPRSupportingAssetItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "asset_name_other",
                    models.CharField(
                        blank=True,
                        help_text='Only when asset.code == "other" or free-text override',
                        max_length=200,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("purpose", models.CharField(blank=True, max_length=500)),
                (
                    "estimated_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="database.dprsupportingasset",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supporting_assets",
                        to="database.dprsectionmachinery",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DPR — Supporting Asset Item",
                "verbose_name_plural": "DPR — Supporting Asset Items",
                "db_table": "dpr_supporting_asset_item",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="DPRMachineryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("name", models.CharField(max_length=200)),
                ("purpose", models.CharField(blank=True, max_length=500)),
                (
                    "machine_category_other",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "quantity_required",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=15, null=True
                    ),
                ),
                ("process_stage", models.CharField(blank=True, max_length=200)),
                ("manufacturer", models.CharField(blank=True, max_length=200)),
                ("supplier", models.CharField(blank=True, max_length=200)),
                ("model_number", models.CharField(blank=True, max_length=100)),
                (
                    "country_of_manufacture",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "rated_capacity",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=15, null=True
                    ),
                ),
                ("power_source", models.CharField(blank=True, max_length=200)),
                (
                    "automation_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("manual", "Manual"),
                            ("semi_auto", "Semi-Automatic"),
                            ("auto", "Automatic"),
                            ("fully_auto", "Fully Automatic"),
                        ],
                        max_length=20,
                    ),
                ),
                ("operating_capacity", models.CharField(blank=True, max_length=200)),
                ("operating_principle", models.TextField(blank=True)),
                (
                    "power_requirement",
                    models.CharField(
                        blank=True, help_text='e.g. "5 kW"', max_length=200
                    ),
                ),
                ("fuel_requirement", models.CharField(blank=True, max_length=200)),
                ("water_requirement", models.CharField(blank=True, max_length=200)),
                (
                    "compressed_air_requirement",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "recommended_operating_hours",
                    models.CharField(blank=True, max_length=200),
                ),
                ("num_operators_required", models.IntegerField(blank=True, null=True)),
                (
                    "installation_area_required",
                    models.CharField(
                        blank=True, help_text='e.g. "50 sqm"', max_length=200
                    ),
                ),
                ("foundation_required", models.BooleanField(default=False)),
                ("foundation_type", models.CharField(blank=True, max_length=200)),
                (
                    "working_clearance_required",
                    models.CharField(blank=True, max_length=200),
                ),
                ("foundation_size", models.CharField(blank=True, max_length=200)),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "basic_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "gst",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "transportation_charges",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "loading_unloading_charges",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "installation_charges",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "commissioning_charges",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "insurance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "other_charges",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("supplier_identified", models.BooleanField(default=False)),
                ("supplier_name", models.CharField(blank=True, max_length=200)),
                ("supplier_location", models.CharField(blank=True, max_length=300)),
                (
                    "delivery_period",
                    models.CharField(
                        blank=True, help_text='e.g. "3 months"', max_length=100
                    ),
                ),
                ("warranty_period", models.CharField(blank=True, max_length=100)),
                ("amc_required", models.BooleanField(blank=True, null=True)),
                (
                    "amc_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("amc_duration", models.CharField(blank=True, max_length=100)),
                (
                    "annual_maintenance_required",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "spare_parts_availability",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("easily", "Easily Available"),
                            ("on_order", "Available on Order"),
                            ("imported", "Imported"),
                            ("limited", "Limited Availability"),
                        ],
                        max_length=20,
                    ),
                ),
                ("daily_maintenance_requirement", models.TextField(blank=True)),
                (
                    "preventive_maintenance_frequency",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "major_overhaul_frequency",
                    models.CharField(blank=True, max_length=200),
                ),
                ("useful_life_years", models.IntegerField(blank=True, null=True)),
                (
                    "residual_value_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "capacity_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dpr_machinery_capacity_unit",
                        to="database.dprcapacityunit",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "machine_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="database.dprmachinerycategory",
                    ),
                ),
                (
                    "project_component",
                    models.ForeignKey(
                        blank=True,
                        help_text="Must link to a selected project component per KAU spec",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="database.dprcomponent",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="database.dprsectionmachinery",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="database.dprcapacityunit",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DPR — Machinery Item",
                "verbose_name_plural": "DPR — Machinery Items",
                "db_table": "dpr_machinery_item",
                "ordering": ["order", "id"],
            },
        ),
    ]
