# Generated by Django 4.2.30 on 2026-08-24 17:57

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("database", "0061_dprsectionmachinery_dprsupportingassetitem_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DPRSectionUtilities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                ("electricity_required", models.BooleanField(default=False)),
                (
                    "existing_electricity_connection",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "electricity_supply_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("single_phase", "Single Phase"),
                            ("three_phase", "Three Phase"),
                            ("ht", "HT Connection"),
                            ("lt", "LT Connection"),
                        ],
                        max_length=20,
                    ),
                ),
                ("backup_power_required", models.BooleanField(blank=True, null=True)),
                ("consumer_number", models.CharField(blank=True, max_length=100)),
                (
                    "connected_load_kw",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "contract_demand_kva",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "additional_load_required",
                    models.CharField(blank=True, max_length=200),
                ),
                ("generator_capacity", models.CharField(blank=True, max_length=200)),
                ("dg_set_required", models.BooleanField(default=False)),
                ("ups_required", models.BooleanField(default=False)),
                ("solar_backup_proposed", models.BooleanField(default=False)),
                ("water_required", models.BooleanField(default=False)),
                (
                    "water_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("borewell", "Borewell"),
                            ("open_well", "Open Well"),
                            ("panchayat_supply", "Panchayat Water Supply"),
                            ("municipal_supply", "Municipal Water Supply"),
                            ("river", "River"),
                            ("canal", "Canal"),
                            ("tank", "Tank"),
                            ("rainwater_harvesting", "Rainwater Harvesting"),
                            ("private_supply", "Private Supply"),
                            ("other", "Others (Specify)"),
                        ],
                        max_length=30,
                    ),
                ),
                ("water_source_other", models.CharField(blank=True, max_length=200)),
                (
                    "water_available_year_round",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "daily_water_requirement",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "peak_water_requirement",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "annual_water_requirement",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "water_storage_capacity",
                    models.CharField(blank=True, max_length=200),
                ),
                ("water_treatment_required", models.TextField(blank=True)),
                ("refrigeration_required", models.BooleanField(default=False)),
                ("temperature_range", models.CharField(blank=True, max_length=200)),
                ("cooling_capacity", models.CharField(blank=True, max_length=200)),
                ("cold_room_size", models.CharField(blank=True, max_length=200)),
                ("num_chambers", models.IntegerField(blank=True, null=True)),
                ("refrigerant_type", models.CharField(blank=True, max_length=200)),
                (
                    "refrigeration_backup_arrangement",
                    models.CharField(blank=True, max_length=200),
                ),
                ("generates_effluent", models.BooleanField(default=False)),
                ("effluent_quantity", models.CharField(blank=True, max_length=200)),
                (
                    "effluent_treatment_required",
                    models.CharField(blank=True, max_length=200),
                ),
                ("effluent_treatment_method", models.TextField(blank=True)),
                (
                    "effluent_disposal_method",
                    models.CharField(blank=True, max_length=200),
                ),
                ("effluent_reuse_proposed", models.TextField(blank=True)),
                (
                    "communication_items",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("broadband_internet", "Broadband Internet"),
                                ("mobile_internet", "Mobile Internet"),
                                ("wifi", "Wi-Fi"),
                                ("cctv", "CCTV"),
                                ("fibre", "Fibre Connection"),
                                ("erp", "ERP Software"),
                                ("accounting", "Accounting Software"),
                                ("inventory", "Inventory Software"),
                                ("barcode", "Barcode System"),
                                ("qr_code", "QR Code System"),
                                ("digital_weighing", "Digital Weighing"),
                                ("biometric", "Biometric Attendance"),
                                ("cloud_backup", "Cloud Backup"),
                                ("other", "Others (Specify)"),
                            ],
                            max_length=30,
                        ),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("communication_other", models.CharField(blank=True, max_length=200)),
                (
                    "fire_safety_items",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("fire_extinguishers", "Fire Extinguishers"),
                                ("first_aid", "First Aid Kit"),
                                ("ppe", "PPE"),
                                ("emergency_exit", "Emergency Exit"),
                                ("fire_alarm", "Fire Alarm"),
                                ("fire_hydrant", "Fire Hydrant"),
                                ("smoke_detector", "Smoke Detector"),
                                ("emergency_lighting", "Emergency Lighting"),
                                ("safety_signage", "Safety Signage"),
                                ("other", "Others (Specify)"),
                            ],
                            max_length=30,
                        ),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("fire_safety_other", models.CharField(blank=True, max_length=200)),
                ("is_complete", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_utilities",
                        to="database.dprproject",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DPR — Utilities Section",
                "verbose_name_plural": "DPR — Utilities Sections",
                "db_table": "dpr_section_utilities",
            },
        ),
        migrations.CreateModel(
            name="DPRWasteManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                ("waste_other", models.CharField(blank=True, max_length=200)),
                (
                    "disposal_method",
                    models.TextField(
                        blank=True,
                        help_text="Required per KAU spec — enforced by validator",
                    ),
                ),
                ("estimated_quantity", models.CharField(blank=True, max_length=200)),
                ("utilisation_method", models.TextField(blank=True)),
                (
                    "revenue_from_byproducts",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wastes",
                        to="database.dprsectionutilities",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "waste",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="database.dprwastetype",
                    ),
                ),
            ],
            options={
                "verbose_name": "DPR — Waste Management",
                "verbose_name_plural": "DPR — Waste Management Items",
                "db_table": "dpr_waste_management",
                "ordering": ["id"],
                "unique_together": {("section", "waste")},
            },
        ),
        migrations.CreateModel(
            name="DPRRenewableInitiativeSelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                ("initiative_other", models.CharField(blank=True, max_length=200)),
                ("capacity", models.CharField(blank=True, max_length=200)),
                (
                    "estimated_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "expected_annual_savings",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "initiative",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="database.dprrenewableinitiative",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="renewable_initiatives",
                        to="database.dprsectionutilities",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DPR — Renewable Initiative Selection",
                "verbose_name_plural": "DPR — Renewable Initiative Selections",
                "db_table": "dpr_renewable_initiative_selection",
                "ordering": ["id"],
                "unique_together": {("section", "initiative")},
            },
        ),
        migrations.CreateModel(
            name="DPRProcessUtility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "utility_type",
                    models.CharField(
                        choices=[
                            ("compressed_air", "Compressed Air"),
                            ("steam", "Steam"),
                            ("boiler", "Boiler"),
                            ("hot_water", "Hot Water"),
                        ],
                        max_length=20,
                    ),
                ),
                ("purpose", models.CharField(blank=True, max_length=500)),
                ("capacity", models.CharField(blank=True, max_length=200)),
                ("source", models.CharField(blank=True, max_length=200)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="process_utilities",
                        to="database.dprsectionutilities",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DPR — Process Utility",
                "verbose_name_plural": "DPR — Process Utilities",
                "db_table": "dpr_process_utility",
                "ordering": ["id"],
                "unique_together": {("section", "utility_type")},
            },
        ),
        migrations.CreateModel(
            name="DPRFuelUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                ("fuel_other", models.CharField(blank=True, max_length=200)),
                ("purpose", models.CharField(blank=True, max_length=500)),
                ("daily_consumption", models.CharField(blank=True, max_length=200)),
                ("annual_consumption", models.CharField(blank=True, max_length=200)),
                (
                    "estimated_annual_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fuel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="database.dprfueltype",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuels",
                        to="database.dprsectionutilities",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DPR — Fuel Usage",
                "verbose_name_plural": "DPR — Fuel Usages",
                "db_table": "dpr_fuel_usage",
                "ordering": ["id"],
                "unique_together": {("section", "fuel")},
            },
        ),
    ]
