# Generated by Django 4.2.30 on 2026-08-24 18:09

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("database", "0062_dprsectionutilities_dprwastemanagement_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DPRSectionHR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                ("project_head", models.CharField(blank=True, max_length=200)),
                (
                    "operational_management_model",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("by_fpo", "Managed by FPO"),
                            ("professional_ceo", "Managed by Professional CEO"),
                            ("hired_manager", "Managed by Hired Manager"),
                            ("outsourced", "Outsourced Management"),
                            ("joint", "Joint Management"),
                            ("other", "Others (Specify)"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "operational_management_other",
                    models.CharField(blank=True, max_length=200),
                ),
                ("reporting_authority", models.CharField(blank=True, max_length=300)),
                ("org_structure_description", models.TextField(blank=True)),
                (
                    "decision_making_authority",
                    models.CharField(blank=True, max_length=300),
                ),
                ("has_existing_employees", models.BooleanField(default=False)),
                (
                    "existing_employees_total",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "existing_technical_staff",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "existing_administrative_staff",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "existing_marketing_staff",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "existing_skilled_operators",
                    models.IntegerField(blank=True, null=True),
                ),
                ("existing_qualification_notes", models.TextField(blank=True)),
                ("existing_experience_notes", models.TextField(blank=True)),
                (
                    "labour_availability",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("easily", "Easily Available"),
                            ("moderately", "Moderately Available"),
                            ("seasonal", "Seasonal"),
                            ("difficult", "Difficult to Obtain"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "primary_labour_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("local", "Local"),
                            ("nearby_villages", "Nearby Villages"),
                            ("other_districts", "Other Districts"),
                            ("other_states", "Other States"),
                            ("contract_labour", "Contract Labour"),
                        ],
                        max_length=30,
                    ),
                ),
                ("labour_remarks", models.TextField(blank=True)),
                (
                    "welfare_items",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("staff_room", "Staff Room"),
                                ("toilets", "Toilets"),
                                ("drinking_water", "Drinking Water"),
                                ("safety_equipment", "Safety Equipment"),
                                ("rest_area", "Rest Area"),
                                ("dining_area", "Dining Area"),
                                ("uniforms", "Uniforms"),
                                ("health_insurance", "Health Insurance"),
                                ("provident_fund", "Provident Fund"),
                                ("esi", "ESI"),
                                ("transportation", "Transportation"),
                                ("accommodation", "Accommodation"),
                                ("other", "Others (Specify)"),
                            ],
                            max_length=30,
                        ),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("welfare_other", models.CharField(blank=True, max_length=200)),
                (
                    "statutory_compliance",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("epf", "EPF"),
                                ("esi", "ESI"),
                                ("labour_registration", "Labour Registration"),
                                ("minimum_wages", "Minimum Wages Compliance"),
                                ("contract_labour_lic", "Contract Labour Licence"),
                                ("bonus_act", "Bonus Act"),
                                ("gratuity", "Gratuity"),
                                (
                                    "shops_establishments",
                                    "Shops & Establishments Registration",
                                ),
                                ("other", "Others (Specify)"),
                            ],
                            max_length=30,
                        ),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "statutory_compliance_other",
                    models.CharField(blank=True, max_length=200),
                ),
                ("has_future_manpower_expansion", models.BooleanField(default=False)),
                ("expansion_year", models.IntegerField(blank=True, null=True)),
                (
                    "additional_employees_planned",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "additional_technical_staff",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "additional_administrative_staff",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "additional_salary_requirement",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("is_complete", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_hr",
                        to="database.dprproject",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DPR — HR Section",
                "verbose_name_plural": "DPR — HR Sections",
                "db_table": "dpr_section_hr",
            },
        ),
        migrations.CreateModel(
            name="DPREmployeeCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("designation", models.CharField(max_length=200)),
                ("nature_of_work", models.CharField(blank=True, max_length=500)),
                ("number_required", models.IntegerField(blank=True, null=True)),
                (
                    "employment_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("permanent", "Permanent"),
                            ("contract", "Contract"),
                            ("daily_wage", "Daily Wage"),
                            ("seasonal", "Seasonal"),
                            ("part_time", "Part-time"),
                            ("outsourced", "Outsourced"),
                        ],
                        max_length=20,
                    ),
                ),
                ("qualification", models.CharField(blank=True, max_length=200)),
                ("experience_required", models.CharField(blank=True, max_length=200)),
                (
                    "monthly_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "annual_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("recruitment_stage", models.CharField(blank=True, max_length=200)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_categories",
                        to="database.dprsectionhr",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DPR — Employee Category",
                "verbose_name_plural": "DPR — Employee Categories",
                "db_table": "dpr_employee_category",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="DPRTrainingRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                ("training_area_other", models.CharField(blank=True, max_length=200)),
                ("duration", models.CharField(blank=True, max_length=100)),
                ("training_provider", models.CharField(blank=True, max_length=200)),
                (
                    "estimated_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_requirements",
                        to="database.dprsectionhr",
                    ),
                ),
                (
                    "training_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="database.dprtrainingarea",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DPR — Training Requirement",
                "verbose_name_plural": "DPR — Training Requirements",
                "db_table": "dpr_training_requirement",
                "ordering": ["id"],
                "unique_together": {("section", "training_area")},
            },
        ),
        migrations.CreateModel(
            name="DPRDepartmentStaffing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("administration", "Administration"),
                            ("technical", "Technical"),
                            ("production", "Production"),
                            ("quality_control", "Quality Control"),
                            ("warehouse", "Warehouse"),
                            ("sales_marketing", "Sales & Marketing"),
                            ("accounts_finance", "Accounts & Finance"),
                            ("other", "Others (Specify)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("department_other", models.CharField(blank=True, max_length=200)),
                ("num_persons", models.IntegerField(blank=True, null=True)),
                (
                    "annual_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="database.dprsectionhr",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DPR — Department Staffing",
                "verbose_name_plural": "DPR — Department Staffings",
                "db_table": "dpr_department_staffing",
                "ordering": ["id"],
                "unique_together": {("section", "department")},
            },
        ),
    ]
