# Generated by Django 4.2.30 on 2026-08-24 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("database", "0064_dprsectionfinance_dprrevenueassumption_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DPRSectionCompliance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                ("has_pending_legal_issues", models.BooleanField(default=False)),
                ("nature_of_case", models.TextField(blank=True)),
                ("possible_impact", models.TextField(blank=True)),
                ("present_status", models.CharField(blank=True, max_length=300)),
                (
                    "expected_resolution_timeline",
                    models.CharField(blank=True, max_length=200),
                ),
                ("is_complete", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_compliance",
                        to="database.dprproject",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DPR — Compliance Section",
                "verbose_name_plural": "DPR — Compliance Sections",
                "db_table": "dpr_section_compliance",
            },
        ),
        migrations.CreateModel(
            name="DPRComplianceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "custom_name",
                    models.CharField(
                        blank=True,
                        help_text='Used when registration is null — for "Others (Specify)" entries.',
                        max_length=300,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("available", "Available"),
                            ("proposed_to_obtain", "Proposed to Obtain"),
                            ("not_applicable", "Not Applicable"),
                            ("applied", "Applied"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        max_length=30,
                    ),
                ),
                ("issuing_authority", models.CharField(blank=True, max_length=300)),
                ("expected_date_of_approval", models.DateField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        blank=True,
                        help_text="FK to master item. Null when custom_name is used (Others Specify case).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="database.dprstatutoryregistration",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="database.dprsectioncompliance",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DPR — Compliance Item",
                "verbose_name_plural": "DPR — Compliance Items",
                "db_table": "dpr_compliance_item",
                "ordering": ["order", "id"],
            },
        ),
    ]
