# Generated by Django 4.2.30 on 2026-08-24 18:33

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("database", "0065_dprsectioncompliance_dprcomplianceitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="DPRSectionESS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "resources_used",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("electricity", "Electricity"),
                                ("water", "Water"),
                                ("fuel", "Fuel"),
                                ("raw_materials", "Raw Materials"),
                                ("packaging", "Packaging Materials"),
                            ],
                            max_length=30,
                        ),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "conservation_measures",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("water_conservation", "Water Conservation"),
                                ("energy_conservation", "Energy Conservation"),
                                ("waste_recycling", "Waste Recycling"),
                                ("rainwater_harvesting", "Rainwater Harvesting"),
                                ("solar_energy", "Solar Energy"),
                                ("biomass_utilisation", "Biomass Utilisation"),
                                ("other", "Others (Specify)"),
                            ],
                            max_length=30,
                        ),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("conservation_other", models.CharField(blank=True, max_length=200)),
                (
                    "annual_electricity_requirement",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "annual_water_requirement",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "annual_fuel_requirement",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "safety_measures",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("ppe", "Personal Protective Equipment (PPE)"),
                                ("fire_safety", "Fire Safety"),
                                ("first_aid", "First Aid"),
                                ("safety_signage", "Safety Signage"),
                                ("emergency_exit", "Emergency Exit"),
                                ("machine_guards", "Machine Guards"),
                                ("safety_training", "Safety Training"),
                                ("health_checkup", "Health Check-up"),
                                ("insurance", "Insurance"),
                                ("other", "Others (Specify)"),
                            ],
                            max_length=30,
                        ),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("safety_other", models.CharField(blank=True, max_length=200)),
                ("farmers_benefited", models.IntegerField(blank=True, null=True)),
                ("direct_jobs_created", models.IntegerField(blank=True, null=True)),
                ("indirect_jobs_created", models.IntegerField(blank=True, null=True)),
                ("women_beneficiaries", models.IntegerField(blank=True, null=True)),
                ("youth_beneficiaries", models.IntegerField(blank=True, null=True)),
                ("sc_st_beneficiaries", models.IntegerField(blank=True, null=True)),
                ("small_marginal_farmers", models.IntegerField(blank=True, null=True)),
                (
                    "expected_income_increase",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "expected_post_harvest_loss_reduction",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "sustainability_initiatives",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("renewable_energy", "Renewable Energy"),
                                ("organic_production", "Organic Production"),
                                ("natural_farming", "Natural Farming"),
                                ("waste_recycling", "Waste Recycling"),
                                ("water_reuse", "Water Reuse"),
                                ("eco_packaging", "Eco-friendly Packaging"),
                                ("circular_economy", "Circular Economy Practices"),
                                ("resource_recovery", "Resource Recovery"),
                                ("carbon_reduction", "Carbon Reduction Measures"),
                                ("other", "Others (Specify)"),
                            ],
                            max_length=30,
                        ),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("sustainability_other", models.CharField(blank=True, max_length=200)),
                ("environmental_initiatives", models.TextField(blank=True)),
                ("social_initiatives", models.TextField(blank=True)),
                ("governance_practices", models.TextField(blank=True)),
                ("is_complete", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_ess",
                        to="database.dprproject",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DPR — ESS Section",
                "verbose_name_plural": "DPR — ESS Sections",
                "db_table": "dpr_section_ess",
            },
        ),
        migrations.CreateModel(
            name="DPREnvironmentalImpactSelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                ("impact_other", models.CharField(blank=True, max_length=200)),
                ("estimated_quantity", models.CharField(blank=True, max_length=200)),
                ("source", models.CharField(blank=True, max_length=300)),
                ("existing_control_measure", models.TextField(blank=True)),
                ("proposed_mitigation_measure", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "impact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="database.dprenvironmentalimpact",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="environmental_impacts",
                        to="database.dprsectioness",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DPR — Environmental Impact Selection",
                "verbose_name_plural": "DPR — Environmental Impact Selections",
                "db_table": "dpr_environmental_impact_selection",
                "ordering": ["id"],
                "unique_together": {("section", "impact")},
            },
        ),
        migrations.CreateModel(
            name="DPRClimateRiskSelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                ("risk_other", models.CharField(blank=True, max_length=200)),
                ("expected_impact", models.TextField(blank=True)),
                ("proposed_mitigation_strategy", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "risk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="database.dprclimaterisk",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="climate_risks",
                        to="database.dprsectioness",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DPR — Climate Risk Selection",
                "verbose_name_plural": "DPR — Climate Risk Selections",
                "db_table": "dpr_climate_risk_selection",
                "ordering": ["id"],
                "unique_together": {("section", "risk")},
            },
        ),
    ]
