# Generated by Django 4.2.30 on 2026-08-24 18:38

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("database", "0066_dprsectioness_dprenvironmentalimpactselection_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DPRSectionImplementation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "procurement_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("direct_purchase", "Direct Purchase"),
                            ("tender", "Tender"),
                            ("quotation", "Quotation-based"),
                            ("rate_contract", "Rate Contract"),
                            ("empanelled", "Empanelled Supplier"),
                            ("other", "Others (Specify)"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "procurement_method_other",
                    models.CharField(blank=True, max_length=200),
                ),
                ("tender_required", models.BooleanField(blank=True, null=True)),
                ("num_quotations_proposed", models.IntegerField(blank=True, null=True)),
                (
                    "supplier_finalisation_method",
                    models.CharField(blank=True, max_length=300),
                ),
                (
                    "expected_procurement_period",
                    models.CharField(
                        blank=True, help_text='e.g. "3 months"', max_length=100
                    ),
                ),
                (
                    "responsibility_agencies",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("fpo_board", "FPO Board"),
                                ("ceo", "CEO"),
                                ("project_manager", "Project Manager"),
                                ("consultant", "Consultant"),
                                ("contractor", "Contractor"),
                                ("machinery_supplier", "Machinery Supplier"),
                                ("government_dept", "Government Department"),
                                ("bank", "Bank"),
                                ("other", "Other Agencies (Specify)"),
                            ],
                            max_length=30,
                        ),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "responsibility_agency_other",
                    models.CharField(blank=True, max_length=200),
                ),
                ("responsibility_remarks", models.TextField(blank=True)),
                (
                    "monitoring_frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("weekly", "Weekly"),
                            ("fortnightly", "Fortnightly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("monitoring_authority", models.CharField(blank=True, max_length=300)),
                ("reporting_mechanism", models.TextField(blank=True)),
                ("corrective_action_process", models.TextField(blank=True)),
                ("is_complete", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_implementation",
                        to="database.dprproject",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DPR — Implementation Section",
                "verbose_name_plural": "DPR — Implementation Sections",
                "db_table": "dpr_section_implementation",
            },
        ),
        migrations.CreateModel(
            name="DPRImplementationMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "milestone_type",
                    models.CharField(
                        choices=[
                            ("financial_closure", "Financial Closure"),
                            ("civil_completion", "Civil Work Completion"),
                            ("machinery_install", "Machinery Installation"),
                            ("trial_production", "Trial Production"),
                            ("commercial_production", "Commercial Production"),
                            ("first_sale", "First Sale"),
                            ("break_even", "Break-even Achievement"),
                            ("other", "Others (Specify)"),
                        ],
                        max_length=30,
                    ),
                ),
                ("milestone_type_other", models.CharField(blank=True, max_length=200)),
                ("expected_date", models.DateField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="database.dprsectionimplementation",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DPR — Implementation Milestone",
                "verbose_name_plural": "DPR — Implementation Milestones",
                "db_table": "dpr_implementation_milestone",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="DPRImplementationActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("activity_name", models.CharField(max_length=300)),
                ("proposed_start_date", models.DateField(blank=True, null=True)),
                ("proposed_completion_date", models.DateField(blank=True, null=True)),
                (
                    "estimated_duration",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "45 days", "2 months"',
                        max_length=100,
                    ),
                ),
                (
                    "responsible_person_or_agency",
                    models.CharField(blank=True, max_length=300),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="database.dprsectionimplementation",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DPR — Implementation Activity",
                "verbose_name_plural": "DPR — Implementation Activities",
                "db_table": "dpr_implementation_activity",
                "ordering": ["order", "id"],
            },
        ),
    ]
