# Generated by Django 4.2.30 on 2026-08-24 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "database",
            "0067_dprsectionimplementation_dprimplementationmilestone_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DPRSectionRisk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "overall_risk_rating",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low Risk"),
                            ("moderate", "Moderate Risk"),
                            ("high", "High Risk"),
                        ],
                        help_text="Auto-classified low/moderate/high at DPR generation based on cumulative assessment.",
                        max_length=20,
                    ),
                ),
                ("is_complete", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_risk",
                        to="database.dprproject",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DPR — Risk Section",
                "verbose_name_plural": "DPR — Risk Sections",
                "db_table": "dpr_section_risk",
            },
        ),
        migrations.CreateModel(
            name="DPRRiskItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "risk_category",
                    models.CharField(
                        choices=[
                            ("production", "Production Risk"),
                            ("market", "Market Risk"),
                            ("financial", "Financial Risk"),
                            ("institutional", "Institutional Risk"),
                            ("environmental", "Environmental Risk"),
                            ("regulatory", "Regulatory Risk"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "risk_code",
                    models.CharField(
                        choices=[
                            (
                                "raw_material_unavailable",
                                "Non-availability of Raw Materials",
                            ),
                            ("seasonal_supply", "Seasonal Raw Material Supply"),
                            ("poor_quality_material", "Poor Quality Raw Materials"),
                            ("pest_disease", "Pest and Disease Incidence"),
                            ("production_losses", "Production Losses"),
                            ("machinery_breakdown", "Machinery Breakdown"),
                            ("power_failure", "Power Failure"),
                            ("water_scarcity", "Water Scarcity"),
                            ("labour_shortage", "Labour Shortage"),
                            ("technology_failure", "Technology Failure"),
                            ("price_fluctuation", "Price Fluctuation"),
                            ("low_market_demand", "Low Market Demand"),
                            ("competition", "Competition"),
                            ("delayed_payments", "Delayed Payments"),
                            ("customer_concentration", "Customer Concentration"),
                            ("product_rejection", "Product Rejection"),
                            ("export_restrictions", "Export Restrictions"),
                            ("logistics_issues", "Logistics Issues"),
                            ("cost_escalation", "Cost Escalation"),
                            ("interest_rate_increase", "Interest Rate Increase"),
                            ("wc_shortage", "Working Capital Shortage"),
                            ("loan_delay", "Loan Delay"),
                            ("cash_flow_problems", "Cash Flow Problems"),
                            ("credit_recovery", "Credit Recovery Issues"),
                            ("inflation", "Inflation"),
                            ("weak_governance", "Weak Governance"),
                            ("low_member_participation", "Low Member Participation"),
                            ("management_issues", "Management Issues"),
                            ("skilled_manpower_shortage", "Skilled Manpower Shortage"),
                            ("staff_turnover", "Staff Turnover"),
                            ("decision_delays", "Decision-making Delays"),
                            ("flood", "Flood"),
                            ("drought", "Drought"),
                            ("cyclone", "Cyclone"),
                            ("landslide", "Landslide"),
                            ("water_pollution", "Water Pollution"),
                            ("fire", "Fire"),
                            ("climate_change", "Climate Change"),
                            ("delay_licences", "Delay in Licences"),
                            ("delay_subsidy", "Delay in Subsidy"),
                            ("policy_changes", "Policy Changes"),
                            ("tax_changes", "Tax Changes"),
                            ("env_regulations", "Environmental Regulations"),
                            ("labour_regulations", "Labour Regulations"),
                            ("other", "Others (Specify)"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "risk_code_other",
                    models.CharField(
                        blank=True,
                        help_text='Only when risk_code == "other"',
                        max_length=200,
                    ),
                ),
                ("risk_description", models.TextField(blank=True)),
                (
                    "mitigation_strategy",
                    models.TextField(
                        blank=True,
                        help_text="Required per KAU spec — enforced by validator",
                    ),
                ),
                (
                    "responsible_person_or_agency",
                    models.CharField(blank=True, max_length=300),
                ),
                (
                    "implementation_timeline",
                    models.CharField(blank=True, max_length=200),
                ),
                ("expected_outcome", models.TextField(blank=True)),
                (
                    "probability",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "impact",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=10,
                    ),
                ),
                ("existing_measures", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="database.dprsectionrisk",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DPR — Risk Item",
                "verbose_name_plural": "DPR — Risk Items",
                "db_table": "dpr_risk_item",
                "ordering": ["order", "id"],
                "unique_together": {("section", "risk_category", "risk_code")},
            },
        ),
    ]
