# Generated by Django 4.2.30 on 2026-08-28 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_auditlog_action"),
        ("database", "0068_dprsectionrisk_dprriskitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="dprproject",
            name="brief_description",
            field=models.TextField(
                blank=True,
                help_text="§2.2 field 3 — short description of the proposed project. Validator enforces min 50 chars on submit.",
            ),
        ),
        migrations.AddField(
            model_name="dprproject",
            name="expected_outcomes",
            field=models.ManyToManyField(
                blank=True,
                help_text="§2.2 field 7 — multi-select. At least one required on submit.",
                related_name="projects",
                to="database.dprprojectoutcome",
            ),
        ),
        migrations.AddField(
            model_name="dprproject",
            name="expected_outcomes_other",
            field=models.CharField(
                blank=True,
                help_text="Free-text 'Other' entry when a matching outcome is not in the master list.",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="dprproject",
            name="primary_commodity",
            field=models.ForeignKey(
                blank=True,
                help_text="§2.2 field 4. Points to MasterLookup category='commodity'.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dpr_projects_primary",
                to="core.masterlookup",
            ),
        ),
        migrations.AddField(
            model_name="dprproject",
            name="project_objectives",
            field=models.ManyToManyField(
                blank=True,
                help_text="§2.2 field 6 — multi-select. At least one required on submit.",
                related_name="projects",
                to="database.dprprojectobjective",
            ),
        ),
        migrations.AddField(
            model_name="dprproject",
            name="project_objectives_other",
            field=models.CharField(
                blank=True,
                help_text="Free-text 'Other' entry when a matching objective is not in the master list.",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="dprproject",
            name="project_types",
            field=models.ManyToManyField(
                blank=True,
                help_text="§2.2 field 2. Multi-select. New / Expansion / Diversification / …",
                related_name="projects",
                to="database.dprprojecttype",
            ),
        ),
        migrations.AddField(
            model_name="dprproject",
            name="secondary_commodities",
            field=models.ManyToManyField(
                blank=True,
                help_text="§2.2 field 5. Optional multi-select from MasterLookup category='commodity'.",
                related_name="dpr_projects_secondary",
                to="core.masterlookup",
            ),
        ),
        migrations.AlterField(
            model_name="dprproject",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="§2.2 field 1 — Proposed Project Title. Mandatory; validator enforces non-blank on submit.",
                max_length=255,
            ),
        ),
    ]
