# Generated by Django 4.2.30 on 2026-08-29 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0046_alter_externalapisettings_service"),
        ("database", "0069_dprproject_brief_description_and_more"),
    ]

    operations = []
