# Generated by Django 5.2.17 on 2026-09-04 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0046_alter_externalapisettings_service"),
        ("database", "0069_dprproject_brief_description_and_more"),
    ]

    operations = []
