# Generated by Django 5.2.17 on 2026-09-04 04:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_auditlog_action"),
        ("database", "0070_merge_20260904_0940"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ZoneBoundaryVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag. True means record is deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Public UUID identifier (use this in APIs instead of PK)",
                        unique=True,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="e.g. the uploaded filename, or a short description",
                        max_length=150,
                    ),
                ),
                (
                    "geojson_data",
                    models.JSONField(
                        help_text="The raw uploaded FeatureCollection — validated at upload time but not yet applied to live zones"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Only ONE version can be active at a time — activating applies this data to the live AgroClimaticZone rows",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zone Boundary Version",
                "verbose_name_plural": "Zone Boundary Versions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveField(
            model_name="aiserviceconfig",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="aiserviceconfig",
            name="deleted_by",
        ),
        migrations.RemoveField(
            model_name="aiserviceconfig",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="aiusagelog",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="aiusagelog",
            name="deleted_by",
        ),
        migrations.RemoveField(
            model_name="aiusagelog",
            name="fpo",
        ),
        migrations.RemoveField(
            model_name="aiusagelog",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="aiusagelog",
            name="user",
        ),
        migrations.RemoveField(
            model_name="dpraicontent",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="dpraicontent",
            name="deleted_by",
        ),
        migrations.RemoveField(
            model_name="dpraicontent",
            name="project",
        ),
        migrations.RemoveField(
            model_name="dpraicontent",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="dprcalculation",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="dprcalculation",
            name="deleted_by",
        ),
        migrations.RemoveField(
            model_name="dprcalculation",
            name="project",
        ),
        migrations.RemoveField(
            model_name="dprcalculation",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="dprdocument",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="dprdocument",
            name="deleted_by",
        ),
        migrations.RemoveField(
            model_name="dprdocument",
            name="project",
        ),
        migrations.RemoveField(
            model_name="dprdocument",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="dprmasterconfig",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="dprmasterconfig",
            name="deleted_by",
        ),
        migrations.RemoveField(
            model_name="dprmasterconfig",
            name="updated_by",
        ),
        migrations.AlterUniqueTogether(
            name="dprsection",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="dprsection",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="dprsection",
            name="deleted_by",
        ),
        migrations.RemoveField(
            model_name="dprsection",
            name="project",
        ),
        migrations.RemoveField(
            model_name="dprsection",
            name="updated_by",
        ),
        migrations.AlterModelOptions(
            name="dprproject",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "DPR — Project",
                "verbose_name_plural": "DPR — Projects",
            },
        ),
        migrations.RemoveField(
            model_name="dprproject",
            name="ai_suggestions",
        ),
        migrations.RemoveField(
            model_name="dprproject",
            name="financial_year",
        ),
        migrations.RemoveField(
            model_name="dprproject",
            name="nature_of_business",
        ),
        migrations.RemoveField(
            model_name="dprproject",
            name="project_components",
        ),
        migrations.RemoveField(
            model_name="dprproject",
            name="project_title",
        ),
        migrations.RemoveField(
            model_name="dprproject",
            name="project_type",
        ),
        migrations.RemoveField(
            model_name="dprproject",
            name="readiness_score",
        ),
        migrations.RemoveField(
            model_name="dprproject",
            name="risk_rating",
        ),
        migrations.RemoveField(
            model_name="dprproject",
            name="validation_errors",
        ),
        migrations.RemoveField(
            model_name="dprproject",
            name="validation_warnings",
        ),
        migrations.AddField(
            model_name="dprproject",
            name="brief_description",
            field=models.TextField(
                blank=True,
                help_text="§2.2 field 3 — short description of the proposed project. Validator enforces min 50 chars on submit.",
            ),
        ),
        migrations.AddField(
            model_name="dprproject",
            name="expected_outcomes",
            field=models.ManyToManyField(
                blank=True,
                help_text="§2.2 field 7 — multi-select. At least one required on submit.",
                related_name="projects",
                to="database.dprprojectoutcome",
            ),
        ),
        migrations.AddField(
            model_name="dprproject",
            name="expected_outcomes_other",
            field=models.CharField(
                blank=True,
                help_text="Free-text 'Other' entry when a matching outcome is not in the master list.",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="dprproject",
            name="project_objectives",
            field=models.ManyToManyField(
                blank=True,
                help_text="§2.2 field 6 — multi-select. At least one required on submit.",
                related_name="projects",
                to="database.dprprojectobjective",
            ),
        ),
        migrations.AddField(
            model_name="dprproject",
            name="project_objectives_other",
            field=models.CharField(
                blank=True,
                help_text="Free-text 'Other' entry when a matching objective is not in the master list.",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="dprproject",
            name="project_types",
            field=models.ManyToManyField(
                blank=True,
                help_text="§2.2 field 2. Multi-select. New / Expansion / Diversification / …",
                related_name="projects",
                to="database.dprprojecttype",
            ),
        ),
        migrations.AddField(
            model_name="dprproject",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="§2.2 field 1 — Proposed Project Title. Mandatory; validator enforces non-blank on submit.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="marketingstrategy",
            name="failure_reason",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="marketingstrategy",
            name="is_archived",
            field=models.BooleanField(
                default=False,
                help_text="Set True when superseded by a regeneration for the same fpo+commodity+financial_year (business rule 2).",
            ),
        ),
        migrations.AddField(
            model_name="marketingstrategy",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("generating", "Generating"),
                    ("ready", "Ready"),
                    ("failed", "Failed"),
                ],
                default="pending",
                help_text='Lets the client tell "still generating" apart from "failed" — the original stub had no way to distinguish these.',
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="croprecommendation",
            name="recommendations",
            field=models.JSONField(
                help_text="[{crop, confidence, reasoning, estimated_yield}]"
            ),
        ),
        migrations.AlterField(
            model_name="dprproject",
            name="fpo",
            field=models.ForeignKey(
                help_text="FPO that owns this DPR project",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dpr_projects",
                to="database.fpo",
            ),
        ),
        migrations.AlterField(
            model_name="dprproject",
            name="primary_commodity",
            field=models.ForeignKey(
                blank=True,
                help_text="§2.2 field 4. Points to MasterLookup category='commodity'.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dpr_projects_primary",
                to="core.masterlookup",
            ),
        ),
        migrations.AlterField(
            model_name="dprproject",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("in_progress", "In Progress"),
                    ("submitted", "Submitted"),
                    ("generated", "PDF Generated"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="externalapisettings",
            name="service",
            field=models.CharField(
                choices=[
                    ("pan_verification", "PAN Verification (Income Tax Dept API)"),
                    ("gstin_verification", "GSTIN Verification (GST API / GSP)"),
                    ("cin_verification", "CIN Verification (MCA21 Portal API)"),
                ],
                max_length=30,
                unique=True,
            ),
        ),
        migrations.AddIndex(
            model_name="marketingstrategy",
            index=models.Index(
                fields=["fpo", "commodity", "financial_year", "is_archived"],
                name="database_ma_fpo_id_1238f3_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="marketingstrategy",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_archived", False)),
                fields=("fpo", "commodity", "financial_year"),
                name="uniq_active_marketing_strategy_per_fpo_commodity_fy",
            ),
        ),
        migrations.AlterModelTable(
            name="dprproject",
            table="dpr_project",
        ),
        migrations.AddField(
            model_name="zoneboundaryversion",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="zoneboundaryversion",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who deleted this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deleted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="zoneboundaryversion",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last updated this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="zoneboundaryversion",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="zone_boundary_uploads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="AIServiceConfig",
        ),
        migrations.DeleteModel(
            name="AIUsageLog",
        ),
        migrations.DeleteModel(
            name="DPRAIContent",
        ),
        migrations.DeleteModel(
            name="DPRCalculation",
        ),
        migrations.DeleteModel(
            name="DPRDocument",
        ),
        migrations.DeleteModel(
            name="DPRMasterConfig",
        ),
        migrations.DeleteModel(
            name="DPRSection",
        ),
        migrations.AddField(
            model_name="dprproject",
            name="secondary_commodities",
            field=models.ManyToManyField(
                blank=True,
                help_text="§2.2 field 5. Optional multi-select from MasterLookup category='commodity'.",
                related_name="dpr_projects_secondary",
                to="core.masterlookup",
            ),
        ),
    ]
