# Generated by Django 5.2.17 on 2026-09-04 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0071_zoneboundaryversion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mlmodelversion",
            name="status",
            field=models.CharField(
                choices=[
                    ("training", "Training"),
                    ("ready", "Ready"),
                    ("failed", "Failed"),
                ],
                default="ready",
                help_text="training while a Celery retrain job is running; ready once the model file exists (or was uploaded directly); failed if training did not complete -- see training_error.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="mlmodelversion",
            name="training_error",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Why training failed, verbatim from the ML service or the task. Empty unless status is failed.",
            ),
        ),
        migrations.AddField(
            model_name="mlmodelversion",
            name="training_metrics",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text="Full metrics from the ml_service /train/ endpoint (accuracy, feature importances, leave-one-zone-out CV, class balance) when this version came from a CSV retrain. Null for versions registered via direct model-file upload, since that flow has no metrics.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="croprecommendation",
            name="recommendations",
            field=models.JSONField(
                default=list,
                help_text="[{crop, confidence, reasoning, estimated_yield}]",
            ),
        ),
    ]
