# Generated by Django 5.2.17 on 2026-09-07 06:25

import json

from django.db import migrations, models


def wrap_titles_as_json(apps, schema_editor):
    GalleryAlbum = apps.get_model("database", "GalleryAlbum")
    for album in GalleryAlbum.objects.all():
        if isinstance(album.title, str):
            album.title = json.dumps({"en": album.title})
            album.save(update_fields=["title"])


def unwrap_titles_to_string(apps, schema_editor):
    GalleryAlbum = apps.get_model("database", "GalleryAlbum")
    for album in GalleryAlbum.objects.all():
        try:
            parsed = json.loads(album.title)
        except (TypeError, ValueError):
            continue
        if isinstance(parsed, dict):
            album.title = parsed.get("en") or next(iter(parsed.values()), "")
            album.save(update_fields=["title"])


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0072_mlmodelversion_status_mlmodelversion_training_error_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryalbum',
            name='title',
            field=models.TextField(),
        ),
        migrations.RunPython(wrap_titles_as_json, unwrap_titles_to_string),
        migrations.AlterField(
            model_name='galleryalbum',
            name='title',
            field=models.JSONField(default=dict, help_text='{"en": "...", "ml": "..."}'),
        ),
    ]
