# Generated by Django 5.2.17 on 2026-09-10 16:59

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0073_gallery_album_title_multilang"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agroclimaticzone",
            name="soil_type",
        ),
        migrations.AddField(
            model_name="expert",
            name="user",
            field=models.OneToOneField(
                blank=True,
                help_text="Login account for this expert. Null until admin creates credentials.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expert_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="governmentofficialprofile",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="governmentofficialprofile",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_govt_officials",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="governmentofficialprofile",
            name="assigned_block",
            field=models.CharField(
                blank=True,
                help_text="Block/taluk code, MasterLookup category: block - set when jurisdiction_type=block",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="governmentofficialprofile",
            name="id_number",
            field=models.CharField(
                blank=True,
                help_text="PEN / PAN / CIN / Employee ID, format depends on user_category",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="governmentofficialprofile",
            name="registration_status",
            field=models.CharField(
                choices=[
                    ("approved", "Approved"),
                    ("pending", "Pending Approval"),
                    ("rejected", "Rejected"),
                ],
                default="approved",
                help_text="Self-registered accounts start pending; admin-created accounts are auto-approved",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="governmentofficialprofile",
            name="user_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("agri_officer", "Agri Officer"),
                    ("university_official", "University Official"),
                    ("sfac_official", "SFAC Official"),
                    ("cbbo_personnel", "CBBO Personnel"),
                    ("nabard_official", "NABARD Official"),
                    ("atma_specialist", "ATMA Specialist"),
                ],
                help_text="Determines ID number format validation",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="externalapisettings",
            name="service",
            field=models.CharField(
                choices=[
                    ("pan_verification", "PAN Verification (Income Tax Dept API)"),
                    ("gstin_verification", "GSTIN Verification (GST API / GSP)"),
                    ("cin_verification", "CIN Verification (MCA21 Portal API)"),
                    ("weather_api", "Weather API (OpenWeatherMap)"),
                ],
                max_length=30,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="governmentofficialprofile",
            name="assigned_district",
            field=models.CharField(
                blank=True,
                help_text="District code from constants.py - set when jurisdiction_type=district or block",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="governmentofficialprofile",
            name="jurisdiction_type",
            field=models.CharField(
                choices=[
                    ("district", "District"),
                    ("block", "Block"),
                    ("state", "State"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="AIServiceConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag. True means record is deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Public UUID identifier (use this in APIs instead of PK)",
                        unique=True,
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("dpr_narratives", "DPR Narrative Generation"),
                            ("chatbot", "AI Chatbot"),
                            ("marketing", "Marketing Strategy AI"),
                            ("translate", "Auto-Translate AI"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Admin toggle — when False the feature returns fallback/placeholder response",
                    ),
                ),
                (
                    "monthly_cap_inr",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Monthly spend limit in INR. 0 = no cap.",
                        max_digits=10,
                    ),
                ),
                (
                    "alert_at_pct",
                    models.IntegerField(
                        default=80,
                        help_text="Send alert email when usage reaches this % of monthly cap",
                    ),
                ),
                (
                    "current_month_cost_inr",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Cumulative cost this calendar month (INR)",
                        max_digits=10,
                    ),
                ),
                (
                    "current_month_tokens",
                    models.BigIntegerField(
                        default=0, help_text="Total tokens used this calendar month"
                    ),
                ),
                (
                    "current_month_calls",
                    models.IntegerField(
                        default=0, help_text="Total API calls made this calendar month"
                    ),
                ),
                (
                    "api_key_encrypted",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Anthropic API key — stored encrypted. Set via admin API.",
                    ),
                ),
                (
                    "usd_to_inr_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=84,
                        help_text="USD → INR conversion rate for cost tracking",
                        max_digits=8,
                    ),
                ),
                (
                    "alert_sent",
                    models.BooleanField(
                        default=False,
                        help_text="True once the 80% alert email has been sent this month — reset monthly",
                    ),
                ),
                (
                    "auto_disabled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this service was auto-disabled due to budget cap — cleared on monthly reset",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who deleted this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Service Config",
                "verbose_name_plural": "AI Service Configs",
                "ordering": ["service"],
            },
        ),
        migrations.CreateModel(
            name="Organisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag. True means record is deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Public UUID identifier (use this in APIs instead of PK)",
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "org_type",
                    models.CharField(
                        choices=[("cbbo", "CBBO"), ("ngo", "NGO")], max_length=10
                    ),
                ),
                ("contact_person", models.CharField(max_length=150)),
                ("contact_designation", models.CharField(blank=True, max_length=150)),
                ("contact_email", models.EmailField(max_length=254)),
                ("contact_phone", models.CharField(max_length=15)),
                (
                    "districts_covered",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of district codes this organisation operates in",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who deleted this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Organisation",
                "verbose_name_plural": "Organisations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CBBOOfficerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag. True means record is deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Public UUID identifier (use this in APIs instead of PK)",
                        unique=True,
                    ),
                ),
                ("designation", models.CharField(blank=True, max_length=200)),
                (
                    "registration_status",
                    models.CharField(
                        choices=[
                            ("approved", "Approved"),
                            ("pending", "Pending Approval"),
                            ("rejected", "Rejected"),
                        ],
                        default="approved",
                        help_text="Self-registered accounts start pending; admin-created accounts are auto-approved",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_cbbo_officers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who deleted this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cbbo_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="officers",
                        to="database.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "CBBO Officer Profile",
                "verbose_name_plural": "CBBO Officer Profiles",
            },
        ),
        migrations.CreateModel(
            name="SoilRegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag. True means record is deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Public UUID identifier (use this in APIs instead of PK)",
                        unique=True,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="e.g. laterite_central, alluvial_coastal",
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("name_en", models.CharField(max_length=200)),
                ("name_ml", models.CharField(max_length=200)),
                (
                    "boundary",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        help_text="Soil region polygon — independent of AgroClimaticZone boundaries",
                        srid=4326,
                    ),
                ),
                (
                    "soil_type",
                    models.CharField(
                        help_text="e.g. Laterite, Alluvial, Sandy loam", max_length=200
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who deleted this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Soil Region",
                "verbose_name_plural": "Soil Regions",
            },
        ),
        migrations.CreateModel(
            name="SoilRegionVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag. True means record is deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Public UUID identifier (use this in APIs instead of PK)",
                        unique=True,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="e.g. the uploaded filename, or a short description",
                        max_length=150,
                    ),
                ),
                (
                    "geojson_data",
                    models.JSONField(
                        help_text="The raw uploaded FeatureCollection — validated at upload time but not yet applied to live soil regions"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Only ONE version can be active at a time — activating replaces the live SoilRegion set with this data",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who deleted this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="soil_region_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Soil Region Version",
                "verbose_name_plural": "Soil Region Versions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubAdminFPOAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fpo_assignments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fpo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subadmin_assignment",
                        to="database.fpo",
                    ),
                ),
                (
                    "subadmin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fpo_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "subadmin_fpo_assignment",
            },
        ),
        migrations.CreateModel(
            name="AIUsageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag. True means record is deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Public UUID identifier (use this in APIs instead of PK)",
                        unique=True,
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("dpr_narratives", "DPR Narrative Generation"),
                            ("chatbot", "AI Chatbot"),
                            ("marketing", "Marketing Strategy AI"),
                            ("translate", "Auto-Translate AI"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "model_used",
                    models.CharField(
                        default="claude-sonnet-4-6",
                        help_text="Exact model ID used for this call",
                        max_length=100,
                    ),
                ),
                ("input_tokens", models.IntegerField(default=0)),
                ("output_tokens", models.IntegerField(default=0)),
                ("total_tokens", models.IntegerField(default=0)),
                (
                    "cost_usd",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                (
                    "cost_inr",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "reference_id",
                    models.CharField(
                        blank=True,
                        help_text="e.g. DPRProject ID or ChatConversation ID",
                        max_length=100,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who deleted this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fpo",
                    models.ForeignKey(
                        blank=True,
                        help_text="Which FPO triggered this call (null for system-level calls)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_usage_logs",
                        to="database.fpo",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_usage_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Usage Log",
                "verbose_name_plural": "AI Usage Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["service", "created_at"],
                        name="database_ai_service_006f0a_idx",
                    ),
                    models.Index(
                        fields=["fpo", "created_at"],
                        name="database_ai_fpo_id_6f99a7_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CBBOAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag. True means record is deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Public UUID identifier (use this in APIs instead of PK)",
                        unique=True,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[("district", "District"), ("state", "State")],
                        max_length=10,
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True,
                        help_text="District code (matches FPO.district, e.g. TSR, KLM). Blank when level=state.",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cbbo_assignments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cbbo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cbbo_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who deleted this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "CBBO Assignment",
                "verbose_name_plural": "CBBO Assignments",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True), ("level", "district")),
                        fields=("cbbo", "district"),
                        name="unique_active_district_assignment",
                    )
                ],
            },
        ),
    ]
