# Generated by Django 5.2.17 on 2026-09-03 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_auditlog_action"),
        ("database", "0074_remove_dpraicontent_created_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dpraicontent",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="dpraicontent",
            name="deleted_by",
        ),
        migrations.RemoveField(
            model_name="dpraicontent",
            name="project",
        ),
        migrations.RemoveField(
            model_name="dpraicontent",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="dprcalculation",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="dprcalculation",
            name="deleted_by",
        ),
        migrations.RemoveField(
            model_name="dprcalculation",
            name="project",
        ),
        migrations.RemoveField(
            model_name="dprcalculation",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="dprdocument",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="dprdocument",
            name="deleted_by",
        ),
        migrations.RemoveField(
            model_name="dprdocument",
            name="project",
        ),
        migrations.RemoveField(
            model_name="dprdocument",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="dprmasterconfig",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="dprmasterconfig",
            name="deleted_by",
        ),
        migrations.RemoveField(
            model_name="dprmasterconfig",
            name="updated_by",
        ),
        migrations.AlterUniqueTogether(
            name="dprsection",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="dprsection",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="dprsection",
            name="deleted_by",
        ),
        migrations.RemoveField(
            model_name="dprsection",
            name="project",
        ),
        migrations.RemoveField(
            model_name="dprsection",
            name="updated_by",
        ),
        migrations.AlterModelOptions(
            name="dprproject",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "DPR — Project",
                "verbose_name_plural": "DPR — Projects",
            },
        ),
        migrations.RemoveField(
            model_name="dprproject",
            name="ai_suggestions",
        ),
        migrations.RemoveField(
            model_name="dprproject",
            name="financial_year",
        ),
        migrations.RemoveField(
            model_name="dprproject",
            name="nature_of_business",
        ),
        migrations.RemoveField(
            model_name="dprproject",
            name="project_components",
        ),
        migrations.RemoveField(
            model_name="dprproject",
            name="project_title",
        ),
        migrations.RemoveField(
            model_name="dprproject",
            name="project_type",
        ),
        migrations.RemoveField(
            model_name="dprproject",
            name="readiness_score",
        ),
        migrations.RemoveField(
            model_name="dprproject",
            name="risk_rating",
        ),
        migrations.RemoveField(
            model_name="dprproject",
            name="validation_errors",
        ),
        migrations.RemoveField(
            model_name="dprproject",
            name="validation_warnings",
        ),
        migrations.AddField(
            model_name="dprproject",
            name="brief_description",
            field=models.TextField(
                blank=True,
                help_text="§2.2 field 3 — short description of the proposed project. Validator enforces min 50 chars on submit.",
            ),
        ),
        migrations.AddField(
            model_name="dprproject",
            name="expected_outcomes",
            field=models.ManyToManyField(
                blank=True,
                help_text="§2.2 field 7 — multi-select. At least one required on submit.",
                related_name="projects",
                to="database.dprprojectoutcome",
            ),
        ),
        migrations.AddField(
            model_name="dprproject",
            name="expected_outcomes_other",
            field=models.CharField(
                blank=True,
                help_text="Free-text 'Other' entry when a matching outcome is not in the master list.",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="dprproject",
            name="project_objectives",
            field=models.ManyToManyField(
                blank=True,
                help_text="§2.2 field 6 — multi-select. At least one required on submit.",
                related_name="projects",
                to="database.dprprojectobjective",
            ),
        ),
        migrations.AddField(
            model_name="dprproject",
            name="project_objectives_other",
            field=models.CharField(
                blank=True,
                help_text="Free-text 'Other' entry when a matching objective is not in the master list.",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="dprproject",
            name="project_types",
            field=models.ManyToManyField(
                blank=True,
                help_text="§2.2 field 2. Multi-select. New / Expansion / Diversification / …",
                related_name="projects",
                to="database.dprprojecttype",
            ),
        ),
        migrations.AddField(
            model_name="dprproject",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="§2.2 field 1 — Proposed Project Title. Mandatory; validator enforces non-blank on submit.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="marketingstrategy",
            name="failure_reason",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="marketingstrategy",
            name="is_archived",
            field=models.BooleanField(
                default=False,
                help_text="Set True when superseded by a regeneration for the same fpo+commodity+financial_year (business rule 2).",
            ),
        ),
        migrations.AddField(
            model_name="marketingstrategy",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("generating", "Generating"),
                    ("ready", "Ready"),
                    ("failed", "Failed"),
                ],
                default="pending",
                help_text='Lets the client tell "still generating" apart from "failed" — the original stub had no way to distinguish these.',
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="dprproject",
            name="fpo",
            field=models.ForeignKey(
                help_text="FPO that owns this DPR project",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dpr_projects",
                to="database.fpo",
            ),
        ),
        migrations.AlterField(
            model_name="dprproject",
            name="primary_commodity",
            field=models.ForeignKey(
                blank=True,
                help_text="§2.2 field 4. Points to MasterLookup category='commodity'.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dpr_projects_primary",
                to="core.masterlookup",
            ),
        ),
        migrations.RemoveField(
            model_name="dprproject",
            name="secondary_commodities",
        ),
        migrations.AlterField(
            model_name="dprproject",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("in_progress", "In Progress"),
                    ("submitted", "Submitted"),
                    ("generated", "PDF Generated"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="marketingstrategy",
            index=models.Index(
                fields=["fpo", "commodity", "financial_year", "is_archived"],
                name="database_ma_fpo_id_1238f3_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="marketingstrategy",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_archived", False)),
                fields=("fpo", "commodity", "financial_year"),
                name="uniq_active_marketing_strategy_per_fpo_commodity_fy",
            ),
        ),
        migrations.AlterModelTable(
            name="dprproject",
            table="dpr_project",
        ),
        migrations.DeleteModel(
            name="DPRAIContent",
        ),
        migrations.DeleteModel(
            name="DPRCalculation",
        ),
        migrations.DeleteModel(
            name="DPRDocument",
        ),
        migrations.DeleteModel(
            name="DPRMasterConfig",
        ),
        migrations.DeleteModel(
            name="DPRSection",
        ),
        migrations.AddField(
            model_name="dprproject",
            name="secondary_commodities",
            field=models.ManyToManyField(
                blank=True,
                help_text="§2.2 field 5. Optional multi-select from MasterLookup category='commodity'.",
                related_name="dpr_projects_secondary",
                to="core.masterlookup",
            ),
        ),
    ]
