"""
Hand-adjusted migration for KAU RCD Phase 2 wrap-up (2026-09-02).

**State-only sync.** The 5 stale DPR tables (DPRAIContent, DPRCalculation,
DPRDocument, DPRMasterConfig, DPRSection) and the DPRProject field churn
that Django's makemigrations wanted to include here are all already
resolved in the physical database — verified with a direct pg_tables +
information_schema.columns audit on 2026-09-02.

The drift is purely in Django's migration state. This migration syncs
state to match reality via `SeparateDatabaseAndState` with an empty
`database_operations` list — zero physical DDL, zero data loss risk.

After this migration:
- Django's migration state stops asking to delete 5 stale tables on future
  `makemigrations` runs
- Django's state matches the actual DPRProject columns (title, project_types,
  brief_description, etc. — added earlier without a migration during the V2
  rebuild)
- Future migrations against DPRProject / DPRConfig / etc. generate cleanly

See DPR_V2_BUILD_PLAN.md § "Migration drift finding" for the wider drift
narrative. 0071, 0072, 0073, 0074 handled the parts of the drift that
required physical DDL (new columns / M2M / table rename). This one handles
the last part — state-only bookkeeping.
"""
# Generated by Django 4.2.30 on 2026-09-02 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_auditlog_action"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("database", "0074_dprproject_field_sources"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
        migrations.RemoveField(
            model_name="dprcalculation",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="dprcalculation",
            name="deleted_by",
        ),
        migrations.RemoveField(
            model_name="dprcalculation",
            name="project",
        ),
        migrations.RemoveField(
            model_name="dprcalculation",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="dprdocument",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="dprdocument",
            name="deleted_by",
        ),
        migrations.RemoveField(
            model_name="dprdocument",
            name="project",
        ),
        migrations.RemoveField(
            model_name="dprdocument",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="dprmasterconfig",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="dprmasterconfig",
            name="deleted_by",
        ),
        migrations.RemoveField(
            model_name="dprmasterconfig",
            name="updated_by",
        ),
        migrations.AlterUniqueTogether(
            name="dprsection",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="dprsection",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="dprsection",
            name="deleted_by",
        ),
        migrations.RemoveField(
            model_name="dprsection",
            name="project",
        ),
        migrations.RemoveField(
            model_name="dprsection",
            name="updated_by",
        ),
        migrations.AlterModelOptions(
            name="dprproject",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "DPR — Project",
                "verbose_name_plural": "DPR — Projects",
            },
        ),
        migrations.RemoveField(
            model_name="dprproject",
            name="ai_suggestions",
        ),
        migrations.RemoveField(
            model_name="dprproject",
            name="financial_year",
        ),
        migrations.RemoveField(
            model_name="dprproject",
            name="nature_of_business",
        ),
        migrations.RemoveField(
            model_name="dprproject",
            name="project_components",
        ),
        migrations.RemoveField(
            model_name="dprproject",
            name="project_title",
        ),
        migrations.RemoveField(
            model_name="dprproject",
            name="project_type",
        ),
        migrations.RemoveField(
            model_name="dprproject",
            name="readiness_score",
        ),
        migrations.RemoveField(
            model_name="dprproject",
            name="risk_rating",
        ),
        migrations.RemoveField(
            model_name="dprproject",
            name="validation_errors",
        ),
        migrations.RemoveField(
            model_name="dprproject",
            name="validation_warnings",
        ),
        migrations.AddField(
            model_name="dprproject",
            name="brief_description",
            field=models.TextField(
                blank=True,
                help_text="§2.2 field 3 — short description of the proposed project. Validator enforces min 50 chars on submit.",
            ),
        ),
        migrations.AddField(
            model_name="dprproject",
            name="expected_outcomes",
            field=models.ManyToManyField(
                blank=True,
                help_text="§2.2 field 7 — multi-select. At least one required on submit.",
                related_name="projects",
                to="database.dprprojectoutcome",
            ),
        ),
        migrations.AddField(
            model_name="dprproject",
            name="expected_outcomes_other",
            field=models.CharField(
                blank=True,
                help_text="Free-text 'Other' entry when a matching outcome is not in the master list.",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="dprproject",
            name="project_objectives",
            field=models.ManyToManyField(
                blank=True,
                help_text="§2.2 field 6 — multi-select. At least one required on submit.",
                related_name="projects",
                to="database.dprprojectobjective",
            ),
        ),
        migrations.AddField(
            model_name="dprproject",
            name="project_objectives_other",
            field=models.CharField(
                blank=True,
                help_text="Free-text 'Other' entry when a matching objective is not in the master list.",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="dprproject",
            name="project_types",
            field=models.ManyToManyField(
                blank=True,
                help_text="§2.2 field 2. Multi-select. New / Expansion / Diversification / …",
                related_name="projects",
                to="database.dprprojecttype",
            ),
        ),
        migrations.AddField(
            model_name="dprproject",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="§2.2 field 1 — Proposed Project Title. Mandatory; validator enforces non-blank on submit.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="dprconfig",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Timestamp when record was created",
            ),
        ),
        migrations.AlterField(
            model_name="dprconfig",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="dprconfig",
            name="default_value",
            field=models.JSONField(
                help_text='Original seeded value — used for "reset to default" and audit comparisons.'
            ),
        ),
        migrations.AlterField(
            model_name="dprconfig",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="dprconfig",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp when record was last updated"
            ),
        ),
        migrations.AlterField(
            model_name="dprconfig",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last updated this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="dprproject",
            name="fpo",
            field=models.ForeignKey(
                help_text="FPO that owns this DPR project",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dpr_projects",
                to="database.fpo",
            ),
        ),
        migrations.AlterField(
            model_name="dprproject",
            name="primary_commodity",
            field=models.ForeignKey(
                blank=True,
                help_text="§2.2 field 4. Points to MasterLookup category='commodity'.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dpr_projects_primary",
                to="core.masterlookup",
            ),
        ),
        migrations.RemoveField(
            model_name="dprproject",
            name="secondary_commodities",
        ),
        migrations.AlterField(
            model_name="dprproject",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("in_progress", "In Progress"),
                    ("submitted", "Submitted"),
                    ("generated", "PDF Generated"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="DPRAIContent",
        ),
        migrations.DeleteModel(
            name="DPRCalculation",
        ),
        migrations.DeleteModel(
            name="DPRDocument",
        ),
        migrations.DeleteModel(
            name="DPRMasterConfig",
        ),
        migrations.DeleteModel(
            name="DPRSection",
        ),
        migrations.AddField(
            model_name="dprproject",
            name="secondary_commodities",
            field=models.ManyToManyField(
                blank=True,
                help_text="§2.2 field 5. Optional multi-select from MasterLookup category='commodity'.",
                related_name="dpr_projects_secondary",
                to="core.masterlookup",
            ),
        ),
    ],
            database_operations=[],
        ),
    ]
