# Generated by Django 5.2.17 on 2026-09-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0075_ml_model_version_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="mlmodelversion",
            name="status",
            field=models.CharField(
                choices=[
                    ("training", "Training"),
                    ("ready", "Ready"),
                    ("failed", "Failed"),
                ],
                default="ready",
                help_text="training while a Celery retrain job is running; ready once the model file exists (or was uploaded directly); failed if training did not complete -- see training_error.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="mlmodelversion",
            name="training_error",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Why training failed, verbatim from the ML service or the task. Empty unless status is failed.",
            ),
        ),
    ]
