# Generated by Django 4.2.30 on 2026-09-02 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("database", "0075_drift_cleanup_state_sync"),
    ]

    operations = [
        migrations.CreateModel(
            name="DPRCapitalTranche",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "tranche_type",
                    models.CharField(
                        choices=[
                            ("promoter_contribution", "Promoter contribution"),
                            ("loan_disbursement", "Loan disbursement"),
                            ("subsidy_release", "Subsidy release"),
                            ("grant_receipt", "Grant receipt"),
                            ("other_inflow", "Other inflow"),
                            ("capex_land", "Capex — land"),
                            ("capex_civil", "Capex — civil works"),
                            ("capex_machinery", "Capex — plant & machinery"),
                            ("capex_equipment", "Capex — equipment"),
                            ("capex_utilities", "Capex — utilities"),
                            ("capex_pre_operative", "Capex — pre-operative expenses"),
                            ("capex_other", "Capex — other"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount in ₹. Positive value for both inflows and outflows — direction is derived from tranche_type.",
                        max_digits=15,
                    ),
                ),
                (
                    "expected_month",
                    models.PositiveSmallIntegerField(
                        help_text="1-indexed month within the project implementation period. Month 1 = first month of construction / setup."
                    ),
                ),
                (
                    "is_actual",
                    models.BooleanField(
                        default=False,
                        help_text="False = projected (planned tranche not yet executed). True = actual (event has happened; timing is confirmed).",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text='Optional short label — e.g. "First loan drawdown", "SBI Rs 25L".',
                        max_length=255,
                    ),
                ),
                (
                    "finance_field",
                    models.CharField(
                        blank=True,
                        help_text='Optional cross-reference to a DPRSectionFinance field name (e.g. "cost_plant_machinery" or "mof_bank_term_loan"). Used by the calc engine to reconcile tranche sums against section totals.',
                        max_length=60,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capital_tranches",
                        to="database.dprproject",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DPR — Capital Tranche",
                "verbose_name_plural": "DPR — Capital Tranches",
                "db_table": "dpr_capital_tranche",
                "ordering": ["expected_month", "id"],
                "indexes": [
                    models.Index(
                        fields=["project", "expected_month"],
                        name="dpr_capital_project_ffec50_idx",
                    )
                ],
            },
        ),
    ]
