# Generated by Django 4.2.30 on 2026-09-02 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("database", "0076_dprcapitaltranche"),
    ]

    operations = [
        migrations.CreateModel(
            name="DPRRiskMatrixCell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "probability",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        help_text="Probability level from the user's risk assessment.",
                        max_length=10,
                    ),
                ),
                (
                    "impact",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        help_text="Impact level from the user's risk assessment.",
                        max_length=10,
                    ),
                ),
                (
                    "risk_class",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("moderate", "Moderate"),
                            ("high", "High"),
                        ],
                        help_text="Classification assigned when the (probability, impact) pair applies. Admin-editable via /api/admin/dpr/risk-matrix/.",
                        max_length=10,
                    ),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Optional numeric weight for future weighted aggregations. Not consumed by the current rule-based classifier.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DPR — Risk Matrix Cell",
                "verbose_name_plural": "DPR — Risk Matrix Cells",
                "db_table": "dpr_risk_matrix_cell",
                "ordering": ["probability", "impact"],
            },
        ),
        migrations.AddConstraint(
            model_name="dprriskmatrixcell",
            constraint=models.UniqueConstraint(
                fields=("probability", "impact"), name="dpr_risk_matrix_unique_cell"
            ),
        ),
    ]
