# Generated by Django 4.2.30 on 2026-09-03 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_auditlog_action"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("database", "0077_dprriskmatrixcell_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DPRKnowledgeEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("kau_pop", "KAU Package of Practices"),
                            ("scheme", "Government scheme / subsidy"),
                            ("sop", "Kefi Tech SOP"),
                            ("statutory", "Kerala statutory / regulatory"),
                            ("agmarknet", "AGMARKNET market prices"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "source_name",
                    models.CharField(
                        help_text='Human-readable source identifier — e.g. "KAU PoP: Turmeric 2024" or "PMKSY — Per Drop More Crop".',
                        max_length=200,
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional canonical URL to the source document / page.",
                    ),
                ),
                (
                    "source_version",
                    models.CharField(
                        blank=True,
                        help_text='Version indicator from the source — e.g. "2024 edition", "v3.2", release date. Used for audit trail when superseded.',
                        max_length=50,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="One-line summary shown in admin lists + retrieval preview.",
                        max_length=255,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="The actual retrievable text. Kept short (a few paragraphs) — large documents should be split into multiple entries so retrieval can pick the relevant slice."
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        db_index=True,
                        default="en",
                        help_text='Language code — "en" or "ml". Retrieval matches to project language preference; falls back to English if unavailable.',
                        max_length=10,
                    ),
                ),
                (
                    "section_keys",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='DPR section keys this entry is relevant to — e.g. ["market", "technology"]. Empty = applies to any section. Retrieval narrows by the section currently being generated.',
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Free-form tags for admin search — e.g. ["organic", "kerala-only"].',
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Only active entries are returned by retrieval. Deactivated entries stay for audit (old narratives may cite them).",
                    ),
                ),
                (
                    "ingested_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this entry was first added — separate from created_at so re-ingestion of the same source can preserve original date.",
                    ),
                ),
                (
                    "business_types",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Nature-of-business categories this entry is relevant to. Blank = applies to any business type.",
                        related_name="knowledge_entries",
                        to="database.dprnatureofbusiness",
                    ),
                ),
                (
                    "commodities",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Commodities this entry is relevant to (MasterLookup category='commodity'). Blank = applies to any commodity.",
                        related_name="knowledge_entries_by_commodity",
                        to="core.masterlookup",
                    ),
                ),
                (
                    "components",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Project components this entry is relevant to. Blank = applies to any component.",
                        related_name="knowledge_entries",
                        to="database.dprcomponent",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "superseded_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="If set, this entry has been replaced by a newer version. Marking superseded_by automatically sets is_active=False.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supersedes",
                        to="database.dprknowledgeentry",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DPR — Knowledge Entry",
                "verbose_name_plural": "DPR — Knowledge Entries",
                "db_table": "dpr_knowledge_entry",
                "ordering": ["-ingested_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["source_type", "is_active"],
                        name="dpr_knowled_source__11e38c_idx",
                    ),
                    models.Index(
                        fields=["language", "is_active"],
                        name="dpr_knowled_languag_c443db_idx",
                    ),
                ],
            },
        ),
    ]
