# Generated by Django 4.2.30 on 2026-09-03 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("database", "0078_dprknowledgeentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="DPRAIContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "chapter",
                    models.CharField(
                        choices=[
                            ("executive_summary", "Executive Summary"),
                            ("project_background", "Project Background"),
                            ("promoter_profile", "Promoter Profile"),
                            ("market_analysis", "Market Analysis"),
                            ("technical_feasibility", "Technical Feasibility"),
                            ("implementation_plan", "Implementation Plan"),
                            ("financial_analysis", "Financial Analysis"),
                            ("risk_analysis", "Risk Analysis"),
                            ("swot", "SWOT Analysis"),
                            ("environmental_impact", "Environmental Impact"),
                            ("conclusion", "Conclusion"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "original_ai",
                    models.TextField(
                        blank=True,
                        help_text="FIRST AI-generated text — frozen after first write. Used in the diff view as the historical baseline.",
                    ),
                ),
                (
                    "user_edited",
                    models.TextField(
                        blank=True,
                        help_text="The current live version — either the original AI text or the user's edit of it. This is what the DPR PDF renders.",
                    ),
                ),
                (
                    "candidate_regen",
                    models.TextField(
                        blank=True,
                        help_text="Latest regeneration output waiting for user Accept/Keep/Merge decision. Empty when there is no pending candidate.",
                    ),
                ),
                (
                    "original_ai_kb_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="DPRKnowledgeEntry ids cited when the original AI text was generated. Historical trace.",
                    ),
                ),
                (
                    "candidate_regen_kb_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="DPRKnowledgeEntry ids cited by the latest regeneration.",
                    ),
                ),
                (
                    "active_kb_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="DPRKnowledgeEntry ids the currently-active text is grounded in. Set on generate (matches original_ai_kb_ids) and updated on accept (from candidate_regen_kb_ids).",
                    ),
                ),
                (
                    "active_version",
                    models.CharField(
                        choices=[
                            ("original_ai", "Original AI"),
                            ("user_edited", "User-edited"),
                        ],
                        default="user_edited",
                        help_text='Which slot is the live version. Only "user_edited" is used in practice; enum kept for future admin recovery flow.',
                        max_length=20,
                    ),
                ),
                (
                    "is_stale",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True when an upstream section field has changed since the current active text was generated. Cleared on accept/regen.",
                    ),
                ),
                (
                    "stale_reason",
                    models.CharField(
                        blank=True,
                        help_text='Which section change marked this chapter stale — e.g. "market section updated 2026-09-05". For FE tooltip.',
                        max_length=200,
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the original AI text was first generated.",
                        null=True,
                    ),
                ),
                (
                    "candidate_generated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the current candidate_regen was generated.",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_content",
                        to="database.dprproject",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DPR — AI Content",
                "verbose_name_plural": "DPR — AI Content",
                "db_table": "dpr_ai_content",
                "ordering": ["project", "chapter"],
                "indexes": [
                    models.Index(
                        fields=["project", "chapter"],
                        name="dpr_ai_cont_project_de3355_idx",
                    ),
                    models.Index(
                        fields=["project", "is_stale"],
                        name="dpr_ai_cont_project_af14a5_idx",
                    ),
                ],
                "unique_together": {("project", "chapter")},
            },
        ),
    ]
