# Generated by Django 4.2.30 on 2026-09-03 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0079_dpraicontent"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiserviceconfig",
            name="model_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Provider-specific model ID. Examples: anthropic → "claude-sonnet-4-6"; openai → "gpt-4o-mini"; google → "gemini-2.5-flash". Blank uses the provider\'s current default (see llm_gateway.DEFAULT_MODELS).',
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="aiserviceconfig",
            name="provider",
            field=models.CharField(
                choices=[
                    ("mock", "Deterministic mock (no external API)"),
                    ("anthropic", "Anthropic Claude"),
                    ("openai", "OpenAI GPT"),
                    ("google", "Google Gemini"),
                ],
                default="mock",
                help_text="Which LLM provider handles this feature. Change to switch vendors without a code deploy. Requires the matching API key + model name below.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="aiusagelog",
            name="provider",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Which LLM vendor served this call — mirrors AIServiceConfig.provider at the time of the call. Useful for cost breakdown when a service switches provider mid-month.",
                max_length=20,
            ),
        ),
    ]
