# Generated by Django 4.2.30 on 2026-09-03 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("database", "0080_aiserviceconfig_provider"),
    ]

    operations = [
        migrations.CreateModel(
            name="DPRFieldRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "data_element_key",
                    models.CharField(
                        db_index=True,
                        help_text="Section key this rule applies to.",
                        max_length=50,
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        db_index=True,
                        help_text="Name of the field WITHIN the section — matches the field key used in the section serializer / FE form schema.",
                        max_length=100,
                    ),
                ),
                (
                    "recipe_type",
                    models.CharField(
                        choices=[
                            ("component_in", "Component selected"),
                            ("field_equals", "Sibling field value"),
                        ],
                        help_text="Which recipe shape this rule uses. Determines which of the type-specific fields below are meaningful.",
                        max_length=20,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("show_when", "Show when condition met"),
                            ("hide_when", "Hide when condition met"),
                        ],
                        default="show_when",
                        help_text="Direction — do we show or hide when the condition is met?",
                        max_length=10,
                    ),
                ),
                (
                    "trigger_field",
                    models.CharField(
                        blank=True,
                        help_text="For recipe 'field_equals' — sibling field in the same section whose value we check.",
                        max_length=100,
                    ),
                ),
                (
                    "trigger_value",
                    models.CharField(
                        blank=True,
                        help_text="For recipe 'field_equals' — the value trigger_field must equal for this rule to fire. Compared as string.",
                        max_length=200,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text='Admin-visible explanation — e.g. "steam_capacity only shown when boiler component selected".',
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "required_components",
                    models.ManyToManyField(
                        blank=True,
                        help_text="For recipe 'component_in' — the rule fires when the project has ANY of these components selected. Ignored for other recipes.",
                        related_name="field_rules",
                        to="database.dprcomponent",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DPR — Field Rule",
                "verbose_name_plural": "DPR — Field Rules",
                "db_table": "dpr_field_rule",
                "ordering": ["data_element_key", "field_name", "id"],
                "indexes": [
                    models.Index(
                        fields=["data_element_key", "field_name"],
                        name="dpr_field_r_data_el_5f8ce7_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DPRComponentApplicability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "data_element_key",
                    models.CharField(
                        db_index=True,
                        help_text="Section key from DPR_SECTIONS in src/lib/api/dpr.ts — e.g. 'raw-material', 'utilities', 'finance'. Free-text rather than enum so admin can add rules for new sections without a migration.",
                        max_length=50,
                    ),
                ),
                (
                    "applicability",
                    models.CharField(
                        choices=[
                            ("M", "Mandatory"),
                            ("O", "Optional / Conditional"),
                            ("H", "Hidden"),
                        ],
                        db_index=True,
                        help_text="M = mandatory (must complete to submit). O = optional/conditional (shown but not required). H = hidden (not shown in wizard).",
                        max_length=1,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text='Admin-visible explanation for why this rule exists — e.g. "Cold Storage: no raw material processed onsite".',
                    ),
                ),
                (
                    "component",
                    models.ForeignKey(
                        help_text="Which project component this rule applies to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applicability_rules",
                        to="database.dprcomponent",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DPR — Component Applicability",
                "verbose_name_plural": "DPR — Component Applicability Rules",
                "db_table": "dpr_component_applicability",
                "ordering": ["component", "data_element_key"],
                "indexes": [
                    models.Index(
                        fields=["data_element_key", "applicability"],
                        name="dpr_compone_data_el_f12b61_idx",
                    )
                ],
                "unique_together": {("component", "data_element_key")},
            },
        ),
    ]
