# Generated by Django 4.2.30 on 2026-09-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0081_dprcomponentapplicability"),
    ]

    operations = [
        migrations.AddField(
            model_name="dprmarketingproduct",
            name="customer_categories_other",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
