# Generated by Django 4.2.30 on 2026-09-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0082_dprmarketingproduct_customer_categories_other"),
    ]

    operations = [
        migrations.AddField(
            model_name="dprsectionfinance",
            name="repayment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "reducing_balance",
                        "Reducing Balance (Equal Principal Instalments)",
                    ),
                    ("emi", "EMI (Equated Monthly Instalments)"),
                ],
                default="reducing_balance",
                help_text="Reducing-balance (default, NABARD convention) or EMI (opt-in when a specific financing scheme requires it).",
                max_length=20,
            ),
        ),
    ]
