# Generated by Django 4.2.30 on 2026-09-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0083_loan_repayment_method_h1"),
    ]

    operations = [
        migrations.AddField(
            model_name="dprsectionfinance",
            name="cost_interest_during_construction",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Interest During Construction — capitalised into the depreciable asset base per KAU pre-UAT reply §2.6. Typically computed as loan_amount × rate × construction_period_months / (12 × 100).",
                max_digits=18,
                null=True,
            ),
        ),
    ]
