# Generated by Django 4.2.30 on 2026-09-08 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("database", "0084_idc_field_h2"),
    ]

    operations = [
        migrations.CreateModel(
            name="DPRDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag. True means record is deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Public UUID identifier (use this in APIs instead of PK)",
                        unique=True,
                    ),
                ),
                (
                    "version_number",
                    models.IntegerField(
                        help_text="Monotonically increasing per-project version. NEVER resets when a new PDF is generated (per KAU pre-UAT reply §7.2). Combined with `project` = unique."
                    ),
                ),
                (
                    "file_url",
                    models.CharField(
                        help_text="URL / path to the generated PDF. Local dev = MEDIA_ROOT relative path; prod = S3 pre-signed URL.",
                        max_length=1000,
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        default=0,
                        help_text="PDF size in bytes. Shown in the FPO-facing download list so users can see how big the file is before download.",
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Server-side timestamp when the PDF was generated. Rendered next to the version number in the download list per KAU §7.2.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("user_edited", "User-edited"),
                            ("final", "Final version generated by FPO"),
                        ],
                        default="draft",
                        help_text="Status label shown next to the version in the download list per KAU §7.2 (Draft / User-edited / Final).",
                        max_length=20,
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True when this version has been retired by newer versions (past the retention cap in DPRConfig). Row NOT deleted — retained for audit per KAU §7.1.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who deleted this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="database.dprproject",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DPR — Generated Document",
                "verbose_name_plural": "DPR — Generated Documents",
                "db_table": "dpr_document",
                "ordering": ["-version_number"],
                "indexes": [
                    models.Index(
                        fields=["project", "-version_number"],
                        name="idx_dprdoc_proj_ver_desc",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="dprdocument",
            constraint=models.UniqueConstraint(
                fields=("project", "version_number"),
                name="uq_dprdocument_project_version",
            ),
        ),
    ]
