# Generated by Django 4.2.30 on 2026-09-08 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0085_h3_dprdocument_recreation"),
    ]

    operations = [
        migrations.AddField(
            model_name="dprsectionfinance",
            name="wc_is_seasonal",
            field=models.BooleanField(
                default=False,
                help_text="True if the project has a seasonal working-capital pattern (agri harvest cycle, festival demand spike, etc.). Enables the peak-month WC uplift preview in the calc engine.",
            ),
        ),
        migrations.AddField(
            model_name="dprsectionfinance",
            name="wc_peak_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Peak-month working-capital requirement (₹). Only used when wc_is_seasonal is True. If provided, the calc engine surfaces both the annual-average WC and this peak value on the WC card + PDF for banker reference.",
                max_digits=18,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dprsectionfinance",
            name="wc_peak_period_notes",
            field=models.TextField(
                blank=True,
                default="",
                help_text='Free-text description of the peak period — e.g. "Oct-Dec harvest procurement cycle" or "Onam demand spike".',
            ),
        ),
    ]
