# Generated by Django 4.2.30 on 2026-09-08 23:22

import json

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


def wrap_gallery_titles_as_json(apps, schema_editor):
    """Convert existing plain-text GalleryAlbum.title values into
    ``{"en": "<original text>"}`` JSON so the subsequent JSONField swap
    doesn't reject them. Ported from Aravind's original
    ``0073_gallery_album_title_multilang.py``."""
    GalleryAlbum = apps.get_model("database", "GalleryAlbum")
    for album in GalleryAlbum.objects.all():
        if isinstance(album.title, str):
            album.title = json.dumps({"en": album.title})
            album.save(update_fields=["title"])


def unwrap_gallery_titles_to_string(apps, schema_editor):
    GalleryAlbum = apps.get_model("database", "GalleryAlbum")
    for album in GalleryAlbum.objects.all():
        try:
            parsed = json.loads(album.title)
        except (TypeError, ValueError):
            continue
        if isinstance(parsed, dict):
            album.title = parsed.get("en") or next(iter(parsed.values()), "")
            album.save(update_fields=["title"])


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("database", "0086_c3_seasonal_wc_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZoneBoundaryVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag. True means record is deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Public UUID identifier (use this in APIs instead of PK)",
                        unique=True,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="e.g. the uploaded filename, or a short description",
                        max_length=150,
                    ),
                ),
                (
                    "geojson_data",
                    models.JSONField(
                        help_text="The raw uploaded FeatureCollection — validated at upload time but not yet applied to live zones"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Only ONE version can be active at a time — activating applies this data to the live AgroClimaticZone rows",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zone Boundary Version",
                "verbose_name_plural": "Zone Boundary Versions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="marketingstrategy",
            name="failure_reason",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="marketingstrategy",
            name="is_archived",
            field=models.BooleanField(
                default=False,
                help_text="Set True when superseded by a regeneration for the same fpo+commodity+financial_year (business rule 2).",
            ),
        ),
        migrations.AddField(
            model_name="marketingstrategy",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("generating", "Generating"),
                    ("ready", "Ready"),
                    ("failed", "Failed"),
                ],
                default="pending",
                help_text='Lets the client tell "still generating" apart from "failed" — the original stub had no way to distinguish these.',
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="mlmodelversion",
            name="status",
            field=models.CharField(
                choices=[
                    ("training", "Training"),
                    ("ready", "Ready"),
                    ("failed", "Failed"),
                ],
                default="ready",
                help_text="training while a Celery retrain job is running; ready once the model file exists (or was uploaded directly); failed if training did not complete -- see training_error.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="mlmodelversion",
            name="training_error",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Why training failed, verbatim from the ML service or the task. Empty unless status is failed.",
            ),
        ),
        migrations.AddField(
            model_name="mlmodelversion",
            name="training_metrics",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text="Full metrics from the ml_service /train/ endpoint (accuracy, feature importances, leave-one-zone-out CV, class balance) when this version came from a CSV retrain. Null for versions registered via direct model-file upload, since that flow has no metrics.",
                null=True,
            ),
        ),
        # Gallery album title: CharField → JSONField 3-step conversion
        # (per Aravind's original 0073_gallery_album_title_multilang.py). Doing
        # this in one step fails because existing rows contain plain text like
        # "test" that Postgres can't parse as JSON.
        migrations.AlterField(
            model_name="galleryalbum",
            name="title",
            field=models.TextField(),
        ),
        migrations.RunPython(
            wrap_gallery_titles_as_json,
            unwrap_gallery_titles_to_string,
        ),
        migrations.AlterField(
            model_name="galleryalbum",
            name="title",
            field=models.JSONField(
                default=dict, help_text='{"en": "...", "ml": "..."}'
            ),
        ),
        migrations.AddIndex(
            model_name="marketingstrategy",
            index=models.Index(
                fields=["fpo", "commodity", "financial_year", "is_archived"],
                name="database_ma_fpo_id_1238f3_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="marketingstrategy",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_archived", False)),
                fields=("fpo", "commodity", "financial_year"),
                name="uniq_active_marketing_strategy_per_fpo_commodity_fy",
            ),
        ),
        migrations.AddField(
            model_name="zoneboundaryversion",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="zoneboundaryversion",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who deleted this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deleted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="zoneboundaryversion",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last updated this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="zoneboundaryversion",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="zone_boundary_uploads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
