# Generated by Django 4.2.30 on 2026-09-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "database",
            "0087_zoneboundaryversion_marketingstrategy_failure_reason_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="dprriskitem",
            name="impact",
            field=models.CharField(
                blank=True,
                choices=[
                    ("very_low", "Very Low"),
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("very_high", "Very High"),
                ],
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="dprriskitem",
            name="probability",
            field=models.CharField(
                blank=True,
                choices=[
                    ("very_low", "Very Low"),
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("very_high", "Very High"),
                ],
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="dprriskmatrixcell",
            name="impact",
            field=models.CharField(
                choices=[
                    ("very_low", "Very Low"),
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("very_high", "Very High"),
                ],
                help_text="Impact level from the user's risk assessment.",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="dprriskmatrixcell",
            name="probability",
            field=models.CharField(
                choices=[
                    ("very_low", "Very Low"),
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("very_high", "Very High"),
                ],
                help_text="Probability level from the user's risk assessment.",
                max_length=12,
            ),
        ),
    ]
