# Generated by Django 4.2.30 on 2026-09-12 11:56

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("database", "0089_expert_user_governmentofficialprofile_approved_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agroclimaticzone",
            name="soil_type",
        ),
        migrations.CreateModel(
            name="SoilRegionVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag. True means record is deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Public UUID identifier (use this in APIs instead of PK)",
                        unique=True,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="e.g. the uploaded filename, or a short description",
                        max_length=150,
                    ),
                ),
                (
                    "geojson_data",
                    models.JSONField(
                        help_text="The raw uploaded FeatureCollection — validated at upload time but not yet applied to live soil regions"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Only ONE version can be active at a time — activating replaces the live SoilRegion set with this data",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who deleted this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="soil_region_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Soil Region Version",
                "verbose_name_plural": "Soil Region Versions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SoilRegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag. True means record is deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Public UUID identifier (use this in APIs instead of PK)",
                        unique=True,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="e.g. laterite_central, alluvial_coastal",
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("name_en", models.CharField(max_length=200)),
                ("name_ml", models.CharField(max_length=200)),
                (
                    "boundary",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        help_text="Soil region polygon — independent of AgroClimaticZone boundaries",
                        srid=4326,
                    ),
                ),
                (
                    "soil_type",
                    models.CharField(
                        help_text="e.g. Laterite, Alluvial, Sandy loam", max_length=200
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who deleted this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Soil Region",
                "verbose_name_plural": "Soil Regions",
            },
        ),
    ]
