# Generated by Django 4.2.30 on 2026-09-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "database",
            "0090_remove_agroclimaticzone_soil_type_soilregionversion_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="dprproductitem",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Optional product photo shown on the DPR PDF.",
                null=True,
                upload_to="dpr/products/%Y/%m/",
            ),
        ),
    ]
