# Generated by Django 4.2.30 on 2026-09-14 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("database", "0091_dprproductitem_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="buyerdirectory",
            name="fpo",
            field=models.ForeignKey(
                blank=True,
                help_text="Set only when this row is an FPO registering itself to buy from other FPOs. Null for regular external buyers added by admin.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buyer_registration",
                to="database.fpo",
            ),
        ),
        migrations.AddField(
            model_name="buyerdirectory",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("verified", "Verified"),
                    ("rejected", "Rejected"),
                ],
                default="verified",
                help_text="pending = FPO self-registration awaiting KAU review; verified = approved / admin-added directly; rejected = denied.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="buyerdirectory",
            name="user",
            field=models.OneToOneField(
                blank=True,
                help_text="Login account for this buyer, when they have one (external buyer self-registration). Null for FPO-linked buyer rows and for legacy admin-added external buyers with no login.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buyer_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
