# Generated by Django 4.2.30 on 2026-09-15 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("database", "0092_buyerdirectory_fpo_buyerdirectory_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CropZoneProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag. True means record is deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Public UUID identifier (use this in APIs instead of PK)",
                        unique=True,
                    ),
                ),
                (
                    "crop_name",
                    models.CharField(
                        db_index=True,
                        help_text="Should match the crop_name used elsewhere (CropPackageOfPractices, ml_service's commodity crosswalk) so a crop's data lines up across systems.",
                        max_length=150,
                    ),
                ),
                (
                    "crop_group",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "kau_zone",
                    models.CharField(
                        choices=[
                            ("Coastal Plain", "Coastal Plain"),
                            ("Midland Laterites", "Midland Laterites"),
                            ("Foothills", "Foothills"),
                            ("High Hills", "High Hills"),
                            ("Palakkad Plain", "Palakkad Plain"),
                            ("General (all zones)", "General (all zones)"),
                        ],
                        help_text="The KAU book's own physiographic zone this profile documents -- expanded into 1-5 service zones at export time via a fixed crosswalk.",
                        max_length=30,
                    ),
                ),
                (
                    "temp_lo",
                    models.FloatField(
                        help_text="Documented minimum temperature (°C) this crop tolerates."
                    ),
                ),
                (
                    "temp_hi",
                    models.FloatField(
                        help_text="Documented maximum temperature (°C) this crop tolerates."
                    ),
                ),
                (
                    "ph_lo",
                    models.FloatField(
                        help_text="Documented minimum soil pH this crop tolerates."
                    ),
                ),
                (
                    "ph_hi",
                    models.FloatField(
                        help_text="Documented maximum soil pH this crop tolerates."
                    ),
                ),
                (
                    "seasons_text",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Free-text season/planting-window description shown in a recommendation's reasoning.",
                    ),
                ),
                (
                    "temp_is_real",
                    models.BooleanField(
                        default=True,
                        help_text="False if temp_lo/hi is a zone-default fallback rather than the book's own stated range.",
                    ),
                ),
                (
                    "ph_is_real",
                    models.BooleanField(
                        default=True,
                        help_text="False if ph_lo/hi is a crop-group-median fallback rather than the book's own stated range.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Only active rows are exported to ml_service. Defaults False so a new/edited entry can be reviewed before it affects live recommendations.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who deleted this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Crop Zone Profile",
                "verbose_name_plural": "Crop Zone Profiles",
                "ordering": ["crop_name", "kau_zone"],
            },
        ),
        migrations.CreateModel(
            name="CropPackageOfPractices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag. True means record is deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Public UUID identifier (use this in APIs instead of PK)",
                        unique=True,
                    ),
                ),
                (
                    "crop_name",
                    models.CharField(
                        db_index=True,
                        help_text="Must match the `crop` string ml_service's predict_crops() returns (crop_name in ml_service/data/crop_prediction_dataset_with_commodity_codes.csv). Looked up case-insensitively.",
                        max_length=150,
                        unique=True,
                    ),
                ),
                (
                    "crop_group",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("season", models.TextField(blank=True, default="")),
                (
                    "varieties",
                    models.JSONField(
                        blank=True, default=list, help_text="[{name, description?}]"
                    ),
                ),
                ("spacing", models.TextField(blank=True, default="")),
                ("manuring_fertilizer", models.TextField(blank=True, default="")),
                ("plant_protection", models.TextField(blank=True, default="")),
                ("harvesting", models.TextField(blank=True, default="")),
                (
                    "expected_yield",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "sections",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Ordered [{heading, body}] -- preserves book structure that doesn't fit the fixed fields above (e.g. a tree crop's named propagation/pruning/intercropping sub-sections).",
                    ),
                ),
                (
                    "source_reference",
                    models.CharField(
                        blank=True,
                        default="KAU Package of Practices Recommendations: Crops 2024 (16th ed.)",
                        max_length=255,
                    ),
                ),
                (
                    "source_page_range",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="PDF page range this entry was transcribed from, e.g. '15-57' -- for audit/spot-check.",
                        max_length=50,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Visible to FPOs only when True. Defaults False so a newly transcribed entry can be cross-checked against the source PDF before publishing.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who deleted this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Crop Package of Practices",
                "verbose_name_plural": "Crop Packages of Practices",
                "ordering": ["crop_name"],
            },
        ),
        migrations.AddConstraint(
            model_name="cropzoneprofile",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("crop_name"),
                models.F("kau_zone"),
                name="cropzoneprofile_crop_zone_ci_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="croppackageofpractices",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("crop_name"),
                name="croppop_crop_name_ci_unique",
            ),
        ),
    ]
