# Generated by Django 4.2.30 on 2026-09-15 03:52

from django.conf import settings
import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("database", "0093_cropzoneprofile_croppackageofpractices_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatKnowledgeEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag. True means record is deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Public UUID identifier (use this in APIs instead of PK)",
                        unique=True,
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        help_text="Short label for admin UI (e.g. 'FPO Registration', 'Reset Password')",
                        max_length=200,
                    ),
                ),
                (
                    "audiences",
                    models.JSONField(
                        default=list,
                        help_text="List of audience tokens. Each token is either 'public', 'all', or a Django auth.Group name (e.g. 'fpo_manager', 'super_admin'). Adding a new portal role = create the Group + tag entries with its name here — no code change needed.",
                    ),
                ),
                (
                    "pages",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Glob patterns of routes this entry is most relevant on — used as a retrieval boost, not a filter. Example: ['/fpo/register*']",
                    ),
                ),
                (
                    "body_en",
                    models.TextField(
                        help_text="The answer text (English). Keep it 1–3 sentences and concrete — the QA model quotes literal spans, so long rambling entries produce worse answers."
                    ),
                ),
                (
                    "body_ml",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Malayalam translation of body_en. Filled in Phase 3.",
                    ),
                ),
                (
                    "keywords",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Extra search terms not in the body — synonyms, misspellings, alternate phrasings. Included in the FTS index.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Inactive entries are hidden from retrieval — use for content that's outdated but you want to keep for history.",
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0,
                        help_text="Tiebreaker for equal-relevance retrievals. Lower = earlier.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who deleted this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Chatbot Knowledge Entry",
                "verbose_name_plural": "Chatbot Knowledge Entries",
                "ordering": ["display_order", "topic"],
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        django.contrib.postgres.search.SearchVector(
                            "topic", config="english", weight="A"
                        ),
                        django.contrib.postgres.search.SearchVector(
                            "keywords", config="english", weight="B"
                        ),
                        django.contrib.postgres.search.SearchVector(
                            "body_en", config="english", weight="C"
                        ),
                        name="chat_kb_search_idx",
                    )
                ],
            },
        ),
    ]
