# Generated by Django 4.2.30 on 2026-09-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0094_chatknowledgeentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
    ]
