# Generated by Django 4.2.30 on 2026-09-16 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0095_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="dprrevenueassumption",
            name="year1_sales_unit",
            field=models.ForeignKey(
                blank=True,
                help_text="Unit of measurement for the sales quantity (kg / quintal / MT / etc.).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="database.dprcapacityunit",
            ),
        ),
    ]
