# Generated by Django 4.2.30 on 2026-09-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0098_alter_product_image_inquiry"),
    ]

    operations = [
        migrations.AddField(
            model_name="dpraicontent",
            name="needs_review",
            field=models.BooleanField(
                default=False,
                help_text="True when the last generation contained placeholder tokens that had to be scrubbed. Surfaced as a review badge on the admin viewer and FPO AI-content page.",
            ),
        ),
        migrations.AddField(
            model_name="dpraicontent",
            name="placeholder_hits",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='List of scrubber matches from the last generation. Each entry is {"raw": "[X MT per day]", "replacement": "Not available", "count": 3}. Cleared on next successful regeneration with zero hits.',
            ),
        ),
    ]
