# Generated by Django 4.2.30 on 2026-09-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0099_dpraicontent_needs_review_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dprproject",
            name="board_meeting_frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("monthly", "Monthly"),
                    ("quarterly", "Quarterly"),
                    ("half_yearly", "Half-yearly"),
                    ("annually", "Annually"),
                ],
                help_text="How often the Board of Directors meets.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="dprproject",
            name="ceo_experience_years",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Years of relevant experience the CEO brings to the FPO.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dprproject",
            name="ceo_name",
            field=models.CharField(
                blank=True,
                help_text="Full name of the FPO CEO / Chief Executive at the time of this DPR.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="dprproject",
            name="ceo_qualification",
            field=models.CharField(
                blank=True,
                help_text="CEO qualification (e.g. B.Sc Agri, MBA Agri-business).",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="dprproject",
            name="landholding_summary",
            field=models.TextField(
                blank=True,
                help_text="Free-text summary of member landholding pattern — e.g. '70% smallholders under 2 acres, 25% medium 2-5 acres, 5% above 5 acres'. Used verbatim in the DPR narrative.",
            ),
        ),
        migrations.AddField(
            model_name="dprproject",
            name="psc_members",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Project Steering Committee membership: list of {name, role, affiliation} dicts. Empty list = no PSC constituted.",
            ),
        ),
        migrations.AddField(
            model_name="dprproject",
            name="total_area_acreage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total farming area (in acres) covered by all member farmers of the FPO.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dprproject",
            name="women_shareholding_pct",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Share of total paid-up capital held by women members (%). Distinct from FPO.women_directors which is a governance count.",
                max_digits=5,
                null=True,
            ),
        ),
    ]
