# Generated by Django 4.2.30 on 2026-09-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0100_dprproject_board_meeting_frequency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dpraicontent",
            name="consistency_warnings",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Mismatches between narrative numbers and the calc-engine `CalculationResult` for this chapter. Populated by apps.fpo.services.dpr.consistency_check. Empty list = clean.",
            ),
        ),
    ]
