# Generated by Django 4.2.30 on 2026-09-21 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0101_dpraicontent_consistency_warnings"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingsession",
            name="time",
            field=models.CharField(
                blank=True,
                help_text="e.g. 10:00 -- start time of the session",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="trainingsession",
            name="trainer_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the person who actually conducted the session, if different from the logged-in official",
                max_length=200,
            ),
        ),
    ]
