# Generated by Django 4.2.30 on 2026-09-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0102_trainingsession_time_trainingsession_trainer_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="buyersellermatch",
            name="message",
            field=models.TextField(blank=True),
        ),
    ]
