# Generated by Django 4.2.30 on 2026-09-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0103_buyersellermatch_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="dprproject",
            name="submitted_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="UTC timestamp of the most recent transition to SUBMITTED. Null while the DPR has never been finished.",
                null=True,
            ),
        ),
    ]
