# Generated by Django 4.2.30 on 2026-09-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0104_dpr_submitted_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buyersellermatch",
            name="message",
            field=models.TextField(
                blank=True,
                help_text="Buyer-submitted message, only populated for rows created via the public Market Hub anonymous inquiry flow (PublicProductInquireView). Blank for algorithmic suggested matches from run_matching().",
            ),
        ),
    ]
