# Generated by Django 4.2.30 on 2026-09-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0105_alter_buyersellermatch_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammember",
            name="is_patrons",
            field=models.BooleanField(
                default=False,
                help_text="Patrons are shown on the landing page; others on the Our Team page",
            ),
        ),
    ]
