# Generated by Django 4.2.30 on 2026-09-25 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0106_teammember_is_patrons"),
    ]

    operations = [
        migrations.AddField(
            model_name="expertavailability",
            name="is_custom",
            field=models.BooleanField(
                default=False,
                help_text="True once the expert has manually set/edited this specific date. Custom dates are skipped by the weekly-default cascade.",
            ),
        ),
    ]
