# Generated by Django 4.2.30 on 2026-09-25 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("database", "0107_expertavailability_is_custom"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammember",
            name="section",
            field=models.CharField(
                blank=True,
                choices=[
                    ("patron", "Patron"),
                    ("principal_investigator", "Principal Investigator"),
                    ("co_investigator", "Co-Investigator"),
                    ("pic_member", "Project Implementation Committee Member"),
                    ("technical_consultant", "Technical Consultant"),
                ],
                help_text="Patrons are shown on the landing page; other sections on the Our Team page",
                max_length=40,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="is_patrons",
            field=models.BooleanField(
                default=False,
                help_text="Derived from section — kept for backward compatibility",
            ),
        ),
        migrations.CreateModel(
            name="YoutubePlaylist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag. True means record is deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Public UUID identifier (use this in APIs instead of PK)",
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"en": "...", "ml": "..."} — falls back to the YouTube playlist title',
                    ),
                ),
                ("playlist_id", models.CharField(max_length=64)),
                ("playlist_url", models.URLField(max_length=500)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who deleted this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
