# Generated by Django 4.2.30 on 2026-09-25 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("database", "0108_teammember_section_alter_teammember_is_patrons_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatconversation",
            options={
                "ordering": ["-started_at"],
                "verbose_name": "Chatbot Conversation",
                "verbose_name_plural": "Chatbot Conversations",
            },
        ),
        migrations.AlterModelOptions(
            name="chatmessage",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Chatbot Message",
                "verbose_name_plural": "Chatbot Messages",
            },
        ),
        migrations.RemoveField(
            model_name="chatconversation",
            name="language",
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="claude_model",
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="tokens_used",
        ),
        migrations.AddField(
            model_name="chatconversation",
            name="audience",
            field=models.CharField(
                blank=True,
                default="",
                help_text="'public' for anonymous, else the Django Group name we served this session under. Denormalised for cheap admin filtering.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="chatconversation",
            name="session_id",
            field=models.CharField(
                db_index=True,
                default="",
                help_text="UUID from the FE widget. Kept in localStorage so a return visit reuses the same conversation. Reset endpoint creates a new session_id.",
                max_length=64,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="confidence",
            field=models.FloatField(
                blank=True,
                help_text="Model / retrieval confidence 0-1. Null for user turns.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when record was soft deleted",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who deleted this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deleted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="generator",
            field=models.CharField(
                blank=True,
                choices=[
                    ("gemini", "Gemini (RAG grounded)"),
                    ("extractive", "Extractive QA (fallback)"),
                    ("small_talk", "Canned small-talk reply"),
                    ("none", "No context found — static fallback"),
                ],
                default="",
                help_text="Which generator produced this reply. Blank for user turns.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Soft delete flag. True means record is deleted.",
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="source_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of ChatKnowledgeEntry ids used as context. Empty for user turns and small-talk replies.",
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last updated this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="uuid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text="Public UUID identifier (use this in APIs instead of PK)",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="chatconversation",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Null when the session is anonymous (public widget).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_conversations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="role",
            field=models.CharField(
                choices=[("user", "User"), ("assistant", "Assistant")], max_length=10
            ),
        ),
        migrations.AddIndex(
            model_name="chatconversation",
            index=models.Index(
                fields=["user", "-started_at"], name="database_ch_user_id_7cf657_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatconversation",
            index=models.Index(
                fields=["session_id"], name="database_ch_session_4611d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["conversation", "created_at"],
                name="database_ch_convers_70d67e_idx",
            ),
        ),
    ]
