# Generated by Django 4.2.30 on 2026-09-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0109_alter_chatconversation_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatconversation",
            name="session_id",
            field=models.CharField(
                db_index=True,
                default="",
                help_text="UUID from the FE widget. Kept in localStorage so a return visit reuses the same conversation. Reset endpoint creates a new session_id. Default empty just for the schema — the API layer always writes a real UUID before saving.",
                max_length=64,
            ),
        ),
    ]
