# Generated by Django 4.2.30 on 2026-09-28 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("database", "0111_kvklink"),
    ]

    operations = [
        migrations.CreateModel(
            name="TierUpgradeTip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag. True means record is deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Public UUID identifier (use this in APIs instead of PK)",
                        unique=True,
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            (
                                "score_below_max",
                                "Answer score below max for the question",
                            ),
                            ("boolean_no", 'Boolean answer is "no"'),
                            ("value_below_threshold", "Numeric value below threshold"),
                            ("value_above_threshold", "Numeric value above threshold"),
                            ("answer_equals", "Answer exactly matches trigger_value"),
                            ("answer_not_in", "Answer not in trigger_value (list)"),
                            ("unanswered", "Question was skipped or empty"),
                            ("always", "Always fire (for maintain-tier tips)"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "trigger_value",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Depends on trigger_type:\n  value_below_threshold / value_above_threshold: {"threshold": 33}\n  answer_equals: {"value": "no"}\n  answer_not_in: {"values": ["yes", "partial"]}\nEmpty for score_below_max, boolean_no, unanswered, always.',
                    ),
                ),
                ("tip_en", models.TextField(help_text="English recommendation text")),
                (
                    "tip_ml",
                    models.TextField(
                        blank=True, help_text="Malayalam recommendation text (optional)"
                    ),
                ),
                (
                    "target_tier",
                    models.CharField(
                        choices=[
                            ("A", "Tier A"),
                            ("B", "Tier B"),
                            ("C", "Tier C"),
                            ("D", "Tier D"),
                        ],
                        help_text="Which tier this tip helps the FPO reach (or maintain).",
                        max_length=1,
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=5,
                        help_text="1 (highest) to 10 (lowest). Top-N are shown to the FPO.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "criterion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upgrade_tips",
                        to="database.tiercriterion",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who deleted this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upgrade_tips",
                        to="database.tierquestion",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tier Upgrade Tip",
                "verbose_name_plural": "Tier Upgrade Tips",
                "ordering": ["target_tier", "priority", "id"],
            },
        ),
    ]
