# Generated by Django 4.2.30 on 2026-09-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0112_tierupgradetip"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quicklink",
            options={"ordering": ["order", "id"]},
        ),
        migrations.AddField(
            model_name="quicklink",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Display order — lower first"
            ),
        ),
    ]
