# Generated by Django 4.2.30 on 2026-09-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0113_alter_quicklink_options_quicklink_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externalapisettings",
            name="service",
            field=models.CharField(
                choices=[
                    ("pan_verification", "PAN Verification (Income Tax Dept API)"),
                    ("gstin_verification", "GSTIN Verification (GST API / GSP)"),
                    ("cin_verification", "CIN Verification (MCA21 Portal API)"),
                    ("weather_api", "Weather API (OpenWeatherMap)"),
                    ("youtube_api", "YouTube Data API v3"),
                ],
                max_length=30,
                unique=True,
            ),
        ),
    ]
