# Generated by Django 4.2.30 on 2026-09-30 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("database", "0114_alter_externalapisettings_service"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubAdminConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag. True means record is deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Public UUID identifier (use this in APIs instead of PK)",
                        unique=True,
                    ),
                ),
                ("key", models.CharField(max_length=50, unique=True)),
                ("value", models.IntegerField()),
                ("description", models.CharField(blank=True, max_length=200)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who deleted this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "subadmin_config",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="SubAdminDistrictTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "from_district",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("TVM", "Thiruvananthapuram"),
                            ("KLM", "Kollam"),
                            ("PTA", "Pathanamthitta"),
                            ("ALP", "Alappuzha"),
                            ("KTM", "Kottayam"),
                            ("IDK", "Idukki"),
                            ("EKM", "Ernakulam"),
                            ("TSR", "Thrissur"),
                            ("PKD", "Palakkad"),
                            ("MLP", "Malappuram"),
                            ("KZD", "Kozhikode"),
                            ("WYD", "Wayanad"),
                            ("KNR", "Kannur"),
                            ("KSD", "Kasaragod"),
                        ],
                        help_text="Blank on first assignment.",
                        max_length=5,
                    ),
                ),
                (
                    "to_district",
                    models.CharField(
                        choices=[
                            ("TVM", "Thiruvananthapuram"),
                            ("KLM", "Kollam"),
                            ("PTA", "Pathanamthitta"),
                            ("ALP", "Alappuzha"),
                            ("KTM", "Kottayam"),
                            ("IDK", "Idukki"),
                            ("EKM", "Ernakulam"),
                            ("TSR", "Thrissur"),
                            ("PKD", "Palakkad"),
                            ("MLP", "Malappuram"),
                            ("KZD", "Kozhikode"),
                            ("WYD", "Wayanad"),
                            ("KNR", "Kannur"),
                            ("KSD", "Kasaragod"),
                        ],
                        max_length=5,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                (
                    "subadmin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="district_transfers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transferred_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "subadmin_district_transfer",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["subadmin", "-created_at"],
                        name="subadmin_di_subadmi_5e616f_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SubAdminDistrictAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag. True means record is deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Public UUID identifier (use this in APIs instead of PK)",
                        unique=True,
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        choices=[
                            ("TVM", "Thiruvananthapuram"),
                            ("KLM", "Kollam"),
                            ("PTA", "Pathanamthitta"),
                            ("ALP", "Alappuzha"),
                            ("KTM", "Kottayam"),
                            ("IDK", "Idukki"),
                            ("EKM", "Ernakulam"),
                            ("TSR", "Thrissur"),
                            ("PKD", "Palakkad"),
                            ("MLP", "Malappuram"),
                            ("KZD", "Kozhikode"),
                            ("WYD", "Wayanad"),
                            ("KNR", "Kannur"),
                            ("KSD", "Kasaragod"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who deleted this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subadmin",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="district_assignment",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "subadmin_district_assignment",
                "indexes": [
                    models.Index(
                        fields=["district"], name="subadmin_di_distric_5c4742_idx"
                    )
                ],
            },
        ),
    ]
