# Generated by Django 4.2.30 on 2026-09-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0116_seed_subadmin_config_defaults"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheme",
            name="deadline",
            field=models.DateField(
                blank=True,
                help_text="Application deadline. Auto-expires scheme_expiry_days after this date.",
                null=True,
            ),
        ),
    ]
