# Generated by Django 4.2.30 on 2026-09-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0117_scheme_deadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingsession",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Auto-hidden by Celery task N days after date (training_expiry_days).",
            ),
        ),
    ]
