# Generated by Django 4.2.30 on 2026-09-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0118_trainingsession_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="kvklink",
            name="contact_email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="Direct contact email shown in the chatbot fallback message.",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="kvklink",
            name="contact_phone",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Direct contact phone shown in the chatbot fallback message.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="kvklink",
            name="district",
            field=models.CharField(
                blank=True,
                default="",
                help_text="3-letter Kerala district code (TSR, PKD, ...) for chatbot fallback routing.",
                max_length=5,
            ),
        ),
    ]
