# Generated by Django 4.2.30 on 2026-09-30 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("database", "0119_kvklink_contact_email_kvklink_contact_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cropzoneprofile",
            name="seasons",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Structured service seasons this crop suits here, e.g. ['southwest_monsoon']. Empty = not specified (scorer treats all seasons as mildly suitable). Drives the season component of ml_service's fit scorer; seasons_text stays as display text.",
            ),
        ),
        migrations.AddField(
            model_name="cropzoneprofile",
            name="suitable_soils",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Soil categories (ml_service's 6 canonical names) this crop suits here. Empty = not specified (all soils mildly suitable). Drives the soil component of ml_service's fit scorer.",
            ),
        ),
        migrations.AlterField(
            model_name="aiserviceconfig",
            name="service",
            field=models.CharField(
                choices=[
                    ("dpr_narratives", "DPR Narrative Generation"),
                    ("chatbot", "AI Chatbot"),
                    ("marketing", "Marketing Strategy AI"),
                    ("translate", "Auto-Translate AI"),
                    ("business_plan", "Business Plan Generation"),
                ],
                max_length=30,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="aiusagelog",
            name="service",
            field=models.CharField(
                choices=[
                    ("dpr_narratives", "DPR Narrative Generation"),
                    ("chatbot", "AI Chatbot"),
                    ("marketing", "Marketing Strategy AI"),
                    ("translate", "Auto-Translate AI"),
                    ("business_plan", "Business Plan Generation"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="BusinessPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag. True means record is deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Public UUID identifier (use this in APIs instead of PK)",
                        unique=True,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("ml", "Malayalam")],
                        default="en",
                        max_length=5,
                    ),
                ),
                (
                    "financial_year",
                    models.CharField(help_text="e.g. 2026-27", max_length=10),
                ),
                (
                    "input_snapshot",
                    models.JSONField(
                        default=dict,
                        help_text="Commodities, location, zone, soil, members and tier the plan was grounded in",
                    ),
                ),
                (
                    "content",
                    models.JSONField(
                        default=dict,
                        help_text="Structured plan sections as returned by the LLM (see business_plan.REQUIRED_KEYS)",
                    ),
                ),
                ("provider", models.CharField(blank=True, default="", max_length=20)),
                (
                    "model_used",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who deleted this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fpo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_plans",
                        to="database.fpo",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_business_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Business Plan",
                "verbose_name_plural": "Business Plans",
            },
        ),
        migrations.AddConstraint(
            model_name="businessplan",
            constraint=models.UniqueConstraint(
                fields=("fpo", "language"), name="businessplan_fpo_language_unique"
            ),
        ),
    ]
