# Generated by Django 4.2.30 on 2026-09-30 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("database", "0121_headerlogo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="available_from",
        ),
        migrations.RemoveField(
            model_name="product",
            name="available_until",
        ),
        migrations.RemoveField(
            model_name="product",
            name="is_ondc_listed",
        ),
        migrations.RemoveField(
            model_name="product",
            name="is_public",
        ),
        migrations.RemoveField(
            model_name="product",
            name="ondc_product_id",
        ),
        migrations.RemoveField(
            model_name="product",
            name="price_per_unit",
        ),
        migrations.RemoveField(
            model_name="product",
            name="quality_certification",
        ),
        migrations.RemoveField(
            model_name="product",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="product",
            name="status",
        ),
        migrations.RemoveField(
            model_name="product",
            name="unit",
        ),
        migrations.CreateModel(
            name="ProductStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag. True means record is deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Public UUID identifier (use this in APIs instead of PK)",
                        unique=True,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("kg", "Kilogram"),
                            ("quintal", "Quintal"),
                            ("mt", "Metric Tonne"),
                            ("litre", "Litre"),
                            ("piece", "Piece"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "price_per_unit",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "quality_certification",
                    models.CharField(
                        blank=True,
                        help_text="Free text — e.g. FSSAI, NPOP Organic, ISO 22000",
                        max_length=200,
                    ),
                ),
                ("available_from", models.DateField()),
                ("available_until", models.DateField(blank=True, null=True)),
                ("is_ondc_listed", models.BooleanField(default=False)),
                (
                    "ondc_product_id",
                    models.CharField(
                        blank=True,
                        help_text="Assigned by ONDC after listing",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, help_text="Visible on public Market Hub (P2-12)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("sold", "Sold"),
                            ("expired", "Expired"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("expiry_reminder_sent", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who deleted this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock",
                        to="database.product",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Stock",
                "verbose_name_plural": "Product Stock",
                "ordering": ["-created_at"],
            },
        ),
    ]
