# Generated by Django 4.2.30 on 2026-10-01 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0123_recommendationfeedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productstock",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stocks",
                to="database.product",
            ),
        ),
    ]
