# Generated by Django 4.2.30 on 2026-10-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0124_alter_productstock_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="end_date",
            field=models.DateField(
                blank=True,
                help_text="Optional expiry date — once passed, expire_public_cms_content flips is_active=False so the item vanishes from public pages. Null = indefinite.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="newssource",
            name="end_date",
            field=models.DateField(
                blank=True,
                help_text="Optional expiry date — once passed, expire_public_cms_content flips is_active=False so the source vanishes from public pages. Null = indefinite.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="quicklink",
            name="end_date",
            field=models.DateField(
                blank=True,
                help_text="Optional expiry date — once passed, expire_public_cms_content flips is_active=False so the link vanishes from public pages. Null = indefinite.",
                null=True,
            ),
        ),
    ]
