# Generated by Django 4.2.30 on 2026-10-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0125_add_end_date_to_cms_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="productstock",
            name="contact_phone",
            field=models.CharField(
                blank=True,
                help_text='Direct seller phone for this batch — buyers see a tel: link on the product card. Blank means "no direct line, inquiries route via the Market Hub form only".',
                max_length=20,
            ),
        ),
    ]
