# Generated by Django 4.2.30 on 2026-10-05 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0126_add_contact_phone_to_productstock"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SubAdminFPOAssignment",
        ),
    ]
