# Generated by Django 4.2.30 on 2026-10-06 04:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("database", "0127_delete_subadminfpoassignment"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingSessionCommentRead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                ("last_read_at", models.DateTimeField()),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_reads",
                        to="database.trainingsession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_comment_reads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Training Comment Read",
                "verbose_name_plural": "Training Comment Reads",
            },
        ),
        migrations.CreateModel(
            name="TrainingSessionComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                ("author_name", models.CharField(max_length=200)),
                (
                    "author_designation",
                    models.CharField(
                        help_text='e.g. "Super Admin" or "Sub-Admin, Thrissur"',
                        max_length=200,
                    ),
                ),
                ("comment", models.TextField()),
                (
                    "edited_at",
                    models.DateTimeField(
                        blank=True,
                        help_text='Set when the author edits the text; shown as "(edited)" and re-flags the comment as unread.',
                        null=True,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="training_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_comments",
                        to="database.trainingsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Training Session Comment",
                "verbose_name_plural": "Training Session Comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="trainingsessioncommentread",
            constraint=models.UniqueConstraint(
                fields=("session", "user"), name="uniq_training_comment_read"
            ),
        ),
    ]
