# Generated by Django 4.2.30 on 2026-10-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0128_training_session_comments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="governmentofficialprofile",
            name="assigned_district",
        ),
        migrations.AddField(
            model_name="governmentofficialprofile",
            name="assigned_districts",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='District codes from constants.py (e.g. ["TSR", "EKM"]) - set when jurisdiction_type=district',
            ),
        ),
        migrations.AlterField(
            model_name="governmentofficialprofile",
            name="assigned_block",
            field=models.CharField(
                blank=True,
                help_text="Legacy - block/taluk jurisdiction was removed (migration 0131); always empty now",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="governmentofficialprofile",
            name="jurisdiction_type",
            field=models.CharField(
                choices=[("district", "District"), ("state", "State")], max_length=20
            ),
        ),
    ]
