# Generated by Django 4.2.30 on 2026-10-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0129_government_official_multi_district"),
    ]

    operations = [
        migrations.AddField(
            model_name="dprsectionfinance",
            name="op_lease_rent",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=18, null=True
            ),
        ),
    ]
