"""
DPR generated-PDF snapshot record.

Per KAU pre-UAT reply §7.1 + §7.2 (2026-09-08):
  * Up to N PDFs retained per project (default 10 via DPRConfig
    `pdf_retention_count`); older versions marked `is_archived=True` rather
    than deleted, so the audit trail is preserved.
  * Filename convention: `DPR_<FPO-slug>_v<version_number>.pdf`.
  * `version_number` is monotonic per project — **never resets** when a new
    PDF is generated. So a project on version 5 that has never been reset
    is on version 5, not "v1 of the new batch".
  * Each row is associated with the project, generation date/time and
    status (Draft / User-edited / Final), so the FPO can distinguish
    successive drafts in the download list.

Was previously created in migration 0041 and deleted in migration 0044
during the DPR V2 rebuild. Re-created here to satisfy the KAU §7.1/§7.2
requirements. Deliberately kept minimal — no file-storage abstraction,
just a URL/path string so we can point at local `MEDIA_ROOT` in dev and
S3 presigned URLs in prod without a schema change.
"""

from django.db import models

from apps.core.models.base import BaseModel


class DPRDocument(BaseModel):
    """One generated DPR PDF snapshot per project.

    Do NOT delete rows here — use `is_archived=True` to retire an older
    version once the retention cap is exceeded. Deletion loses the audit
    trail KAU expects for retained DPRs.
    """

    class Status(models.TextChoices):
        DRAFT       = 'draft',       'Draft'
        USER_EDITED = 'user_edited', 'User-edited'
        FINAL       = 'final',       'Final version generated by FPO'

    project = models.ForeignKey(
        'database.DPRProject',
        on_delete=models.CASCADE,
        related_name='documents',
    )
    version_number = models.IntegerField(
        help_text='Monotonically increasing per-project version. NEVER '
                  'resets when a new PDF is generated (per KAU pre-UAT '
                  'reply §7.2). Combined with `project` = unique.',
    )
    file_url = models.CharField(
        max_length=1000,
        help_text='URL / path to the generated PDF. Local dev = '
                  'MEDIA_ROOT relative path; prod = S3 pre-signed URL.',
    )
    file_size = models.BigIntegerField(
        default=0,
        help_text='PDF size in bytes. Shown in the FPO-facing download '
                  'list so users can see how big the file is before '
                  'download.',
    )
    generated_at = models.DateTimeField(
        auto_now_add=True,
        db_index=True,
        help_text='Server-side timestamp when the PDF was generated. '
                  'Rendered next to the version number in the download '
                  'list per KAU §7.2.',
    )
    status = models.CharField(
        max_length=20,
        choices=Status.choices,
        default=Status.DRAFT,
        help_text='Status label shown next to the version in the download '
                  'list per KAU §7.2 (Draft / User-edited / Final).',
    )
    is_archived = models.BooleanField(
        default=False,
        db_index=True,
        help_text='True when this version has been retired by newer '
                  'versions (past the retention cap in DPRConfig). '
                  'Row NOT deleted — retained for audit per KAU §7.1.',
    )

    class Meta:
        db_table = 'dpr_document'
        verbose_name = 'DPR — Generated Document'
        verbose_name_plural = 'DPR — Generated Documents'
        ordering = ['-version_number']
        constraints = [
            models.UniqueConstraint(
                fields=['project', 'version_number'],
                name='uq_dprdocument_project_version',
            ),
        ]
        indexes = [
            models.Index(fields=['project', '-version_number'],
                         name='idx_dprdoc_proj_ver_desc'),
        ]

    def __str__(self):
        return f'{self.project_id} v{self.version_number} ({self.status})'

    # ── Class helpers ────────────────────────────────────────────────────

    @classmethod
    def next_version_for_project(cls, project) -> int:
        """Return the next monotonic version_number for this project.

        Never resets — always max(existing)+1. If the project has 4 versions,
        the next is 5 regardless of how many have been archived. Guarantees
        KAU §7.2's "version numbering shall not be reset when a new PDF
        is generated".
        """
        current_max = cls.objects.filter(project=project).aggregate(
            models.Max('version_number')
        )['version_number__max']
        return (current_max or 0) + 1
